### ISSUE TITLE
os_test.c bad memory access test - calling function at address  0xffffffff is wrongly syntaxed

### ISSUE THREAD

**Issue by ayesuraj** [OP-TEE/optee_test#104]
case 5:
        {
            static const uint32_t my_undef = 0xffffffff;
            ((void (*)(void))(uintptr_t) &my_undef) ();
        }

Here it  has to be as,
case 5:
        {
            static const uint32_t my_undef = 0xffffffff;
            ((void (*)(void))(uintptr_t) my_undef) ();
        }

if your are trying to simulate a function call at address 0xffffffff. Instead it is actually calling a function at address which falls in stack area.

**Comment by d3zd3z** [comment]
Indeed, this is wrong, although because it is a static const, I would guess that the address it is actually using is somewhere in the data segment.  But, still, it isn't testing what it looks like it is trying to test.

**Comment by jenswi-linaro** [comment]
No, I'm trying to execute an undefined instruction.

**Comment by d3zd3z** [comment]
I wonder if we should comment that, since the name of the function does look like it is testing memory accesses. Do we know if ARM has an official undefined instruction that won't get used by something else in a future version?

**Comment by d3zd3z** [comment]
Digging a little further, I believe 0xf7ffffff is defined by ARM as a permanently undefined instruction, and we won't have to worry about it acquiring meaning on some future chip.

**Comment by d3zd3z** [comment]
Digging even further, the f7... instruction is a permanently undefined "media" instruction, whereas 0xe7ffffff is the explicity "UDF" instruction itself. gas doesn't seem to support this, but ARM has a mnemonic for it.

**Comment by jenswi-linaro** [comment]
You're right David, we should comment on that. Sure, we can change the instruction too. Do you know if 0xe7ffffff also is defined as a permanently undefined instruction for Aarch64?

**Comment by d3zd3z** [comment]
The 0xe7ffffff is defined as undefined in ARM v4 through v8. There are other encodings for v7, but this is the only one defined that way across all 32-bit architectures.

As far as I can tell, aarch64 doesn't define an explicit undefined instruction, and this particular encoding falls under "unallocated" in the opcode decoding.

For thumb mode, the undefined instruction is 0xde00.

Oh, and the "UDF" instruction works fine when compiling 32-bit or thumb code, so it does seem to match ARM not defining it for aarch64.

**Comment by jenswi-linaro** [comment]
A proper fix for this would be to move the undefined instruction into an ARM assembly file that can be common for both Aarch64 and ARM Aarch32. Since gas doesn't have the UDF mnemonic we'll have to supply the machine code directly, but that wouldn't be much of a problem.

Do you agree?

**Comment by d3zd3z** [comment]
I think the hard part is figuring out which arch we are on. I don't think we've ever built for thumb, so maybe that isn't an issue. I can try to find out from someone at ARM if there is something we should be using for the Aarch64 UDF equivalent.

**Comment by jforissier** [comment]
FWIW, ARM-TF seems to imply that opcode 0x00000000 is necessarily an invalid A64 instruction. See https://github.com/ARM-software/arm-trusted-firmware/blob/bc469a8/include/common/asm_macros.S#L69-L80.

**Comment by jenswi-linaro** [comment]
Thanks, Jerome. That means two assembly files to keep it clean.
To check arch there's `$(CFG_ARM32_$(sm))` and `$(CFG_ARM64_$(sm))`.

**Comment by jenswi-linaro** [comment]
Fix in https://github.com/OP-TEE/optee_test/pull/106

**Comment by d3zd3z** [comment]
I put a comment in #106 that the undef is indeed not allocated for Aarch64. The ARM person suggested using BRK, but I'm not sure that will give the same behavior for us to test.

Should we go ahead and close this issue?

**Comment by jenswi-linaro** [comment]
The point is to test that executing an undefined instruction is handled correctly, I think it's as good as it can get now.

**Comment by d3zd3z** [comment]
I agree, I'll close it.
