### ISSUE TITLE
xml_crypto_api.h contains multiple free of unallocated errors

### ISSUE THREAD

**Issue by d3zd3z** [OP-TEE/optee_test#117]
In `host/xtest/xml/include/xml_crypto_api.h`, the macros `ALLOCATE_SHARED_MEMORY` and `ALLOCATE_AND_FILL_SHARED_MEMORY` goto an `exit` label upon allocation failure. In apparently all uses of these macros, this label is followed by a free of the attempted allocation, which will cause a free of unallocated data.

My suggestion would be to pass the label as a parameter to the macros, and add additional labels so that the exit cleanup is correct. (there are instances of multiple macro calls, so multiple labels are needed).

**Comment by jforissier** [comment]
I also think that passing the label is a reasonable option.
