### ISSUE TITLE
Wrong flag for OPTEE_CLIENT path in README.md

### ISSUE THREAD

**Issue by elektrischermoench** [OP-TEE/optee_test#146]
It is called OPTEE_CLIENT_PATH in README.md but called OPTEE_CLIENT_EXPORT in Makefile:

```shell
# By default we expect optee_client exported folder to be on a certain relative
# path, but if the client specifies the OPTEE_CLIENT_EXPORT then that path will
# be used instead.
OPTEE_CLIENT_EXPORT ?= ../../../optee_client/out/export
```

**Comment by jforissier** [comment]
Hi @elektrischermoench ,

Thanks for reporting this. The issue was addressed in https://github.com/OP-TEE/optee_test/pull/110, which was around for some time but which I merged just now.
