### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_test#154]
Hi -

The README.md has some small problems it seems to me.

1) There is no more any `optee_armtz` module referenced in there.  It looks like it would be called "optee" now.

2) There is a missing step in the instructions, that the `*.ta` must be copied into the rootfs, at /lib/optee_armtz (this name seems inconsistent since the module name changed, but it works) for non-Android anyway.  `tee-supplicant` will go fish them out of there and autoload them when the client side asks for the UUID.

Do we agree that these things should be fixed / added to README.md, in which case I can make a PR?  Or we think it's super as it is?

**Comment by jenswi-linaro** [comment]
Thanks, please go ahead and make a PR. :-)
