### ISSUE TITLE
Question about adding test TAs

### ISSUE THREAD

**Issue by leesera** [OP-TEE/optee_test#198]
I want to add some simple TAs for testing and studying about TrustZone. (like printing 'helloworld' at TA)
But when I saw the README of this repo, I think I should buy test suites license at https://www.globalplatform.org/store.asp. but it is quite expensive for me :(
then, is there other way to put test TAs at TEE only for testing?

**Comment by etienne-lms** [comment]
OP-TEE comes with a free test suite: https://github.com/OP-TEE/optee_test.
For a basic "hello world" test, have a look at https://github.com/linaro-swg/hello_world.

**Comment by vchong** [comment]
Hi Sera,

The purchase is only for the extended (GP) tests, which is sort of like an addon to `optee_test`. You don't need it if all you want are simple TAs for testing and studying.

**Comment by leesera** [comment]
Thank you for kind answers:)
you mean that I should pay for GP license to add (extended) TAs and just running existing tests is free.
am I right?

**Comment by vchong** [comment]
yes, right

**Comment by leesera** [comment]
okay I see :)

**Comment by leesera** [comment]
I have some issues. I cloned default `hikey_debian.xml` version and I changed the file `hello_world/ta/hello_world_ta.c` before compiling whole files. I just put `DMSG("HIHI\n");` before the default code line `DMSG("Increase value to: %u", params[0].value.a);`.

I put commands `make flash` to put optee on my hikey board and 'IP=xxx make send'.
And then, I boot up my board and put command `tee-supplicant &` and `hello_world` on hikey board.

but the output of command `hello_world` is the default one which omitted my message "HIHI".

I tried reboot my hikey board after that but the screen(out device) is not working.
the log by using uart is like this.

what is the matter of that case? :( please help me


<img width="724" alt="2017-04-09 10 53 36" src="https://cloud.githubusercontent.com/assets/4794692/24837828/7ccb90b8-1d77-11e7-947c-398686d1396b.png">

**Comment by vchong** [comment]
Looking at the makefile, you should run `make deb` first to put the new hello_world into the package before running `make send`.

There's been a couple of reports regarding issues rebooting after flashing a debian build (e.g. https://github.com/OP-TEE/optee_os/issues/1397), but no one has had the chance to look into it yet.

**Comment by leesera** [comment]
@vchong thank you for kind reply!
but I already did `make all` which includes `deb`.

I will try again with `make deb`.

**Comment by leesera** [comment]
oh I can change standard tests! Really thank you for helping me:) @vchong

**Comment by vchong** [comment]
You're welcome! So `make all` didn't trigger `deb`?
