### ISSUE TITLE
how to use TEE_OpenTASession

### ISSUE THREAD

**Issue by clark-chen** [OP-TEE/optee_test#205]
i want to communicate between user TAs, so in a TA‘s cmd，i invoke TEE_OpenTASession to open a session  with another TA‘s uuid，but it report something wrong in rpc_load？
 https://github.com/OP-TEE/optee_os/blob/62ede146cd05fc17421728debc5f9d9c6c614d76/core/arch/arm/kernel/user_ta.c#L810

**Comment by jforissier** [comment]
`TEE_OpenTASession()` does work, if that's your question (it's used by `xtest 1011` for instance).

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
