### ISSUE TITLE
regression: all regression_9xxx test fail

### ISSUE THREAD

**Issue by jiaheng-fan** [OP-TEE/optee_test#220]
I find the following issue while doing regression test. Would you please help on this issue? 
thanks.
 
root@ls1021atsn:~# ./xtest 9001
Test ID: 9001
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################

* regression_9001 Sanity Test Corrupt Meta Encrypted Key
o regression_9001.1 | filename: file_4097B , data size: 4097 byte(s)
/home/fanjiaheng/ls1021atsn/optee_upstream/optee_os/optee_test/host/xtest/regression_9000.c:515: obj_create(&sess, filename, (sizeof(filename) / sizeof((filename)[0])), 0x00000002, 0, filedata, tv->data_len, &obj_id) has an unexpected value: 0xffff0003, expected 0x0
  regression_9001.1 FAILED
  regression_9001 FAILED
+-----------------------------------------------------
Result of testsuite regression filtered by "9001":
regression_9001.1 FAILED first error at /home/fanjiaheng/ls1021atsn/optee_upstream/optee_os/optee_test/host/xtest/regression_9000.c:515
regression_9001 FAILED
+-----------------------------------------------------
4 subtests of which 1 failed
1 test case of which 1 failed
76 test cases was skipped
TEE test application done!

Secure world output:
DEBUG:   [0x0] TEE-CORE:tee_ta_init_pseudo_ta_session:262:    Lookup for pseudo TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0x05
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:679:    Load dynamic TA
DEBUG:   [0x0] TEE-CORE:ta_load:460: ELF load address 0x101000
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:685:       dyn TA : b689f2a7-8adf-477a-9f99-32e90c0ad0a2
FLOW:    [0x0] TEE-CORE:trace_syscall:144: syscall #42 (syscall_storage_obj_create)
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0xE1
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0x9B
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0xCB
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0x68
DEBUG:   [0x0] TEE-CORE:tee_ta_invoke_command:616:   => Error: ffff0003 of 4
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:371: tee_ta_close_session(0xbc057e90)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:390:    ... Destroy session
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:414:    ... Destroy TA ctx

**Comment by jenswi-linaro** [comment]
Please provide a bit more information about what you're testing with, platform, software versions etc.

**Comment by jiaheng-fan** [comment]
platform is plat-ls , optee-os optee_client and optee_test all are 2.4.0

**Comment by vchong** [comment]
Does xtest have write access to /data/tee?
Maybe try deleting everything under /data/tee and run test again.

**Comment by jiaheng-fan** [comment]
yes  It has wirte access  and creates /data/tee directory. but there is not /data/tee/0 file that was replaced by garbage code file.
root@ls1021atsn:/data/tee# ls -l
total 1
drwx------ 2 root root 1024 Jan  9 12:34 A7F289B6DF8A7A479F9932E90C0AD0A2

**Comment by jenswi-linaro** [comment]
It sounds like optee_os isn't at 2.4.0

**Comment by jiaheng-fan** [comment]
below log is optee sercure output , that indicate optee is 2.4.0

DEBUG:   [0x0] TEE-CORE:add_phys_mem:353: CFG_SHMEM_START 4 0xbfe00000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:353: CFG_TA_RAM_START 3 0xbc100000 size 0x03d00000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:353: CFG_TEE_RAM_START 1 0xbc000000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:353: GIC_BASE 8 0x01400000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:353: CONSOLE_UART_BASE 7 0x02100000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:add_va_space:390: type 9 size 0x00a00000
DEBUG:   [0x0] TEE-CORE:init_mem_map:539: type va 9 0xb7500000..0xb7efffff pa 0x00000000..0x009fffff size 0xa00000
DEBUG:   [0x0] TEE-CORE:init_mem_map:539: type va 8 0xb7f00000..0xb7ffffff pa 0x01400000..0x014fffff size 0x100000
DEBUG:   [0x0] TEE-CORE:init_mem_map:539: type va 7 0xb8000000..0xb81fffff pa 0x02100000..0x022fffff size 0x200000
DEBUG:   [0x0] TEE-CORE:init_mem_map:539: type va 4 0xb8200000..0xb82fffff pa 0xbfe00000..0xbfefffff size 0x100000
DEBUG:   [0x0] TEE-CORE:init_mem_map:539: type va 3 0xb8300000..0xbbffffff pa 0xbc100000..0xbfdfffff size 0x3d00000
DEBUG:   [0x0] TEE-CORE:init_mem_map:539: type va 1 0xbc000000..0xbc0fffff pa 0xbc000000..0xbc0fffff size 0x100000
INFO:    TEE-CORE: Initializing (2.4.0-1-geec941c #1 2017å¹´ 06æ 29æ¥ ææåTC arm)

**Comment by jforissier** [comment]
Or maybe `xtest` is not at 2.4.0.

**Comment by jiaheng-fan** [comment]
I checked xtest verison and upgraded it to 2.4.0.  All tests passed but optee still has error log 
24003 subtests of which 0 failed
76 test cases of which 0 failed
0 test case was skipped
TEE test application done!

optee output:
*********** TESTBENCH ***********
***     ALL TESTS PASSED      ***
*********************************
ta_entry_panic: enterERROR:   TEE-CORE: TA panicked with code 0xbeef usr_sp 0x102750 usr_lr 0x11cdb9
ta_entry_client: enter[ta log] ta_entry_wait: waiting 2000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
ERROR:   TEE-CORE: Failed. Return error 0xffff0000
[ta log] ta_entry_wait: waiting 100
[ta log] ta_entry_wait: waiting 500
[ta log] ta_entry_wait: waiting 2000
[ta log] ta_entry_wait: waiting 2000
ERROR:   TEE-CORE:
ERROR:   TEE-CORE: user TA data-abort at address 0x0 (translation fault)
ERROR:   TEE-CORE:  fsr 0x00000805  ttbr0 0xbc05a06a  ttbr1 0xbc05406a  cidr 0x1
ERROR:   TEE-CORE:  cpu #0          cpsr 0x80000030
ERROR:   TEE-CORE:  r0 0x00000001      r4 0x001260f0    r8 0x0020a2a0   r12 0x001027b8
ERROR:   TEE-CORE:  r1 0x00000000      r5 0x001027a0    r9 0x0000000a    sp 0x00102768
ERROR:   TEE-CORE:  r2 0x00000000      r6 0x001027b8   r10 0x00000002    lr 0x00118619
ERROR:   TEE-CORE:  r3 0x00000aff      r7 0x00102790   r11 0xbc053590    pc 0x00104a1e
ERROR:   TEE-CORE: Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b (0xbc0536a0) (active)
ERROR:   TEE-CORE: - load addr : 0x103000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 10240
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0xbc209000 0x3000
ERROR:   TEE-CORE: sect 1 : va 0x103000 pa 0xbc100000 0x1d000
ERROR:   TEE-CORE: sect 2 : va 0x120000 pa 0xbc11d000 0x6000
ERROR:   TEE-CORE: sect 3 : va 0x126000 pa 0xbc123000 0xe6000
ERROR:   TEE-CORE: sect 4 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 5 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 6 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 7 : va 0 pa 0 0
ERROR:   TEE-CORE:
ERROR:   TEE-CORE: user TA data-abort at address 0x40102768 (translation fault)
ERROR:   TEE-CORE:  fsr 0x00000805  ttbr0 0xbc05a06a  ttbr1 0xbc05406a  cidr 0x1
ERROR:   TEE-CORE:  cpu #0          cpsr 0x80000030
ERROR:   TEE-CORE:  r0 0x00000001      r4 0x001260f0    r8 0x0020a2a0   r12 0x001027b8
ERROR:   TEE-CORE:  r1 0x00000001      r5 0x001027a0    r9 0x0000000a    sp 0x00102768
ERROR:   TEE-CORE:  r2 0x00000000      r6 0x001027b8   r10 0x00000002    lr 0x00118619
ERROR:   TEE-CORE:  r3 0x40102768      r7 0x00102790   r11 0xbc053590    pc 0x00104a26
ERROR:   TEE-CORE: Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b (0xbc0536a0) (active)
ERROR:   TEE-CORE: - load addr : 0x103000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 10240
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0xbc209000 0x3000
ERROR:   TEE-CORE: sect 1 : va 0x103000 pa 0xbc100000 0x1d000
ERROR:   TEE-CORE: sect 2 : va 0x120000 pa 0xbc11d000 0x6000
ERROR:   TEE-CORE: sect 3 : va 0x126000 pa 0xbc123000 0xe6000
ERROR:   TEE-CORE: sect 4 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 5 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 6 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 7 : va 0 pa 0 0
ERROR:   TEE-CORE:
ERROR:   TEE-CORE: user TA prefetch-abort at address 0x0 (translation fault)
ERROR:   TEE-CORE:  fsr 0x00000005  ttbr0 0xbc05a06a  ttbr1 0xbc05406a  cidr 0x1
ERROR:   TEE-CORE:  cpu #0          cpsr 0x80000010
ERROR:   TEE-CORE:  r0 0x00000001      r4 0x001260f0    r8 0x0020a2a0   r12 0x001027b8
ERROR:   TEE-CORE:  r1 0x00000002      r5 0x001027a0    r9 0x0000000a    sp 0x00102768
ERROR:   TEE-CORE:  r2 0x00000000      r6 0x001027b8   r10 0x00000002    lr 0x00104a2d
ERROR:   TEE-CORE:  r3 0x00000aff      r7 0x00102790   r11 0xbc053590    pc 0x00000000
ERROR:   TEE-CORE: Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b (0xbc0536a0) (active)
ERROR:   TEE-CORE: - load addr : 0x103000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 10240
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0xbc209000 0x3000
ERROR:   TEE-CORE: sect 1 : va 0x103000 pa 0xbc100000 0x1d000
ERROR:   TEE-CORE: sect 2 : va 0x120000 pa 0xbc11d000 0x6000
ERROR:   TEE-CORE: sect 3 : va 0x126000 pa 0xbc123000 0xe6000
ERROR:   TEE-CORE: sect 4 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 5 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 6 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 7 : va 0 pa 0 0
ERROR:   TEE-CORE:
ERROR:   TEE-CORE: user TA prefetch-abort at address 0x40102768 (translation fault)
ERROR:   TEE-CORE:  fsr 0x00000005  ttbr0 0xbc05a06a  ttbr1 0xbc05406a  cidr 0x1
ERROR:   TEE-CORE:  cpu #0          cpsr 0x80000010
ERROR:   TEE-CORE:  r0 0x00000001      r4 0x001260f0    r8 0x0020a2a0   r12 0x001027b8
ERROR:   TEE-CORE:  r1 0x00000003      r5 0x001027a0    r9 0x0000000a    sp 0x00102768
ERROR:   TEE-CORE:  r2 0x00000000      r6 0x001027b8   r10 0x00000002    lr 0x00104a35
ERROR:   TEE-CORE:  r3 0x40102768      r7 0x00102790   r11 0xbc053590    pc 0x40102768
ERROR:   TEE-CORE: Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b (0xbc0536a0) (active)
ERROR:   TEE-CORE: - load addr : 0x103000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 10240
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0xbc209000 0x3000
ERROR:   TEE-CORE: sect 1 : va 0x103000 pa 0xbc100000 0x1d000
ERROR:   TEE-CORE: sect 2 : va 0x120000 pa 0xbc11d000 0x6000
ERROR:   TEE-CORE: sect 3 : va 0x126000 pa 0xbc123000 0xe6000
ERROR:   TEE-CORE: sect 4 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 5 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 6 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 7 : va 0 pa 0 0
ERROR:   TEE-CORE:
ERROR:   TEE-CORE: user TA undef-abort at address 0x104a36
ERROR:   TEE-CORE:  fsr 0x00000000  ttbr0 0xbc05a06a  ttbr1 0xbc05406a  cidr 0x1
ERROR:   TEE-CORE:  cpu #0          cpsr 0x60000030
ERROR:   TEE-CORE:  r0 0x00000001      r4 0x001260f0    r8 0x0020a2a0   r12 0x001027b8
ERROR:   TEE-CORE:  r1 0x00000004      r5 0x001027a0    r9 0x0000000a    sp 0x00102768
ERROR:   TEE-CORE:  r2 0x00000000      r6 0x001027b8   r10 0x00000002    lr 0x00118619
ERROR:   TEE-CORE:  r3 0x00000aff      r7 0x00102790   r11 0xbc053590    pc 0x00104a36
ERROR:   TEE-CORE: Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b (0xbc0536a0) (active)
ERROR:   TEE-CORE: - load addr : 0x103000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 10240
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0xbc209000 0x3000
ERROR:   TEE-CORE: sect 1 : va 0x103000 pa 0xbc100000 0x1d000
ERROR:   TEE-CORE: sect 2 : va 0x120000 pa 0xbc11d000 0x6000
ERROR:   TEE-CORE: sect 3 : va 0x126000 pa 0xbc123000 0xe6000
ERROR:   TEE-CORE: sect 4 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 5 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 6 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 7 : va 0 pa 0 0
ERROR:   USER-TA: Panic 0x0
ERROR:   TEE-CORE: TA panicked with code 0x0 usr_sp 0x100f00 usr_lr 0x104faf
ERROR:   USER-TA: Panic 0x0
ERROR:   TEE-CORE: TA panicked with code 0x0 usr_sp 0x100f00 usr_lr 0x104faf
ERROR:   USER-TA: Panic 0x0
ERROR:   TEE-CORE: TA panicked with code 0x0 usr_sp 0x100f00 usr_lr 0x104faf
ERROR:   USER-TA: Panic 0x0
ERROR:   TEE-CORE: TA panicked with code 0x0 usr_sp 0x100f00 usr_lr 0x104faf
ERROR:   USER-TA: Panic 0xffff000f
ERROR:   TEE-CORE: TA panicked with code 0xffff000f usr_sp 0x100ed8 usr_lr 0x10936f
ERROR:   USER-TA: Panic 0xffff0006
ERROR:   TEE-CORE: TA panicked with code 0xffff0006 usr_sp 0x100f48 usr_lr 0x107fe7
ERROR:   USER-TA: Panic 0xffff0006
ERROR:   TEE-CORE: TA panicked with code 0xffff0006 usr_sp 0x100ef0 usr_lr 0x107fe7
ERROR:   USER-TA: Panic 0xffff0007
ERROR:   TEE-CORE: TA panicked with code 0xffff0007 usr_sp 0x100ef0 usr_lr 0x107fe7
ERROR:   USER-TA: Panic 0xffff0006
ERROR:   TEE-CORE: TA panicked with code 0xffff0006 usr_sp 0x100f48 usr_lr 0x107fe7
ERROR:   USER-TA: Panic 0xffff0006
ERROR:   TEE-CORE: TA panicked with code 0xffff0006 usr_sp 0x100ef0 usr_lr 0x107fe7
ERROR:   USER-TA: Panic 0xffff0007
ERROR:   TEE-CORE: TA panicked with code 0xffff0007 usr_sp 0x100ef0 usr_lr 0x107fe7
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Head corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Error code=f0100001
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Head corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Error code=f0100001
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Head corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Error code=f0100001
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Head corrupt
ERROR:   TEE-CORE: Object corrupt
ERROR:   TEE-CORE: Error code=f0100001
ERROR:   TEE-CORE: Object corrupt

**Comment by jforissier** [comment]
@jiaheng-fan all is good. The error messages are expected because the regression suite tests error cases, too.

**Comment by jiaheng-fan** [comment]
@jforissier Ok,  thank you for your support

**Comment by ashwinnirantar** [comment]
[``](https://github.com/OP-TEE/optee_test/issues/220#issuecomment-312205695)

How can I find out my xtest version?

**Comment by jbech-linaro** [comment]
> How can I find out my xtest version?

Run `$ git describe` ... the first part there is the release version and the last part is how many commits and the current commit.

**Comment by ashwinnirantar** [comment]
> > How can I find out my xtest version?
> 
> Run `$ git describe` ... the first part there is the release version and the last part is how many commits and the current commit.

Thank you!
