### ISSUE TITLE
Type: modprobe optee_armtz , there is an error: modprobe : can't change directory to '/lib/modules': No such file or directory

### ISSUE THREAD

**Issue by j824737450** [OP-TEE/optee_test#235]
The QEMU , Normal world and Secure world are started, then type: modprobe optee_armtz , there is an error: modprobe : can't change directory to '/lib/modules': No such file or directory(the P1)) . But if I type "xtest" directly,it will run like that(the P2).Is it OK?
![p1](https://user-images.githubusercontent.com/33032927/32135104-07252f0a-bc2c-11e7-82e7-5604f9a8c5fb.jpg)
![p2](https://user-images.githubusercontent.com/33032927/32135105-0c2f5b60-bc2c-11e7-8b7d-6475bba73f45.jpg)

**Comment by jforissier** [comment]
Hi @j824737450 ,

`modprobe` is not needed, because the OP-TEE driver is statically linked.

**Comment by j824737450** [comment]
So the result of  running xtest is successful ?
![normal](https://user-images.githubusercontent.com/33032927/32135194-8828932a-bc2d-11e7-96c9-fc937e37c8b0.jpg)
![secure](https://user-images.githubusercontent.com/33032927/32135199-99595328-bc2d-11e7-932d-dd21fb8927bf.jpg)

I'm a green hand.Thank you!

**Comment by jforissier** [comment]
> So the result of  running xtest is successful ?

Yes it is! Don't worry about the error message that are printed along the way. They are expected, because the test suite checks error cases, too. What matters is the "OK" status printed after each test, and in the end, the message "78 test cases of which 0 failed". "0 failed" is really what you want.

**Comment by j824737450** [comment]
It's OK.  
Thank you very much!
