### ISSUE TITLE
Android5.1 compile error

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_test#236]
Hi all, 
Android5.1 compile error.  Please help to solve it, thanks

In file included from device/hisilicon/bigfish/HiSTBSDKV6R2/source/tee/core/optee/optee_test/host/xtest/regression_1000.c:23:0:
device/hisilicon/bigfish/HiSTBSDKV6R2/source/tee/core/optee/optee_test/host/xtest/xtest_helpers.h:110:25: error: unknown type name 'pthread_barrier_t'
 void xtest_barrier_init(pthread_barrier_t *barrier, unsigned count);

**Comment by vchong** [comment]
Please see https://github.com/OP-TEE/optee_test/commit/170a1ee60a98b407790d97dc682568981d344ca3#commitcomment-22371817 for some reference and background info.

**Comment by airbak** [comment]
Thanks for your reply.
