### ISSUE TITLE
Link error when compiling with GP test suite

### ISSUE THREAD

**Issue by tinycornX** [OP-TEE/optee_test#243]
I tried to compile the optee_test with the command:
```
make CFG_GP_PACKAGE_PATH=path_to_gp_package CROSS_COMPILE=aarch64-linux-gnu-
```
And it results in a link error says:
```
 LD      /xxx/optee_test/out/xtest/xtest
/usr/lib/gcc-cross/aarch64-linux-gnu/6/../../../../aarch64-linux-gnu/bin/ld: ../lib/armv8/libcrypto.a(lhash.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against external symbol `strcmp@@GLIBC_2.17' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc-cross/aarch64-linux-gnu/6/../../../../aarch64-linux-gnu/bin/ld: ../lib/armv8/libcrypto.a(lhash.o)(.text+0x194): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `strcmp@@GLIBC_2.17'
/usr/lib/gcc-cross/aarch64-linux-gnu/6/../../../../aarch64-linux-gnu/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:163: recipe for target 'xtest' failed
make[1]: *** [xtest] Error 1
```

The static library libcrypto.a is originally included in the folder optee_test/host/lib/armv8/ , and therefore I am not able to re-compile it with -fPIC.

The cross-compiler I have been using is aarch64-linux-gnu-gcc (Debian 6.3.0-18) 6.3.0 20170516

Any suggestions on how to solve the problem?

**Comment by jforissier** [comment]
Hi @tinycornX, 

I don't have this problem with http://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/aarch64-linux-gnu/gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tar.xz, can you try it?

**Comment by tinycornX** [comment]
Hi @jforissier ,
Thanks for the quick reply. It works.
I could successfully compile the optee_test now. But how could I run the updated xtest?

I pushed all the TAs(optee_test/out/ta) and xtest (optee_test/out/xtest/xtest) to the board, but failed to run the executable file on the board. xtest is pushed to /system/bin/xtest on the board. The error message is:
```
root@hikey:/ # xtest
/system/bin/sh: /system/bin/xtest: No such file or directory
```

The generated xtest executable file information is:
```
$ file out/xtest/xtest
out/xtest/xtest: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=19b937b456ca4e694b1bf80d4b230a327ed6217f, not stripped
```

**Comment by vchong** [comment]
Which rootfs did you flash to the board? Are you maybe using a 32-bit user space? What is the output of say `file /bin/ls`?

**Comment by tinycornX** [comment]
The userspace is also 64-bit, the output of `file /bin/ls` is
```
$ file ls
ls: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, BuildID[md5/uuid]=30de983738e98d266bdd7b9ad98e3370, stripped
```

**Comment by jforissier** [comment]
This message:
```
/system/bin/sh: /system/bin/xtest: No such file or directory
```
...is quite typical of a missing shared library.

**Comment by tinycornX** [comment]
@jforissier the read-elf indicates that 4 shared libraries are needed, and it seems that libpthread.so.0 is missing. All other 3 could be located at /system/lib/ or /system/lib64/

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
