### ISSUE TITLE
Compile issue for current optee_test code

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_test#246]
Can't find the macro definition.

optee_test/host/xtest/regression_1000.c:371:10: error: 'PTA_INVOKE_TESTS_CMD_MUTEX' undeclared (first use in this function)
          PTA_INVOKE_TESTS_CMD_MUTEX,

Can some one tell me how to fix it?

**Comment by jbech-linaro** [comment]
Hi @jingdlu , you are probably not running latest on everything. Our cron job, building ~8 platforms all passed 7 hours ago and I cannot recall that any other patches has been merged since then:
https://travis-ci.org/OP-TEE/build/builds/319475288

// Joakim

**Comment by jingdlu** [comment]
OK, thank you.
