### ISSUE TITLE
Format specifier compilation error

### ISSUE THREAD

**Issue by goatshriek** [OP-TEE/optee_test#256]
I'm getting compilation errors on lines 892 and 896 in host/xtest/regression_1000.c due to some format specifier width problems with size_t (I've resolved it locally by just adding a 'z' to the specifier). Easy fix, just thought you might want to know. I'd submit a pull request myself but I think by the time I figured all that out you'd already have it resolved.

**Comment by jenswi-linaro** [comment]
Please go ahead and create a pull request. Patches are welcome. :-)
Thanks

**Comment by jbech-linaro** [comment]
That would solve all [current Travis errors](https://travis-ci.org/OP-TEE/build/), so I'm chiming in with Jens, please go ahead.

**Comment by jenswi-linaro** [comment]
Fixed by https://github.com/OP-TEE/optee_test/pull/257

**Comment by goatshriek** [comment]
My apologies, I missed these notifications. In the future I'll go ahead and create the pull request as well.
