### ISSUE TITLE
Some wrong buffer part compared in host/xtest/regression_6000.c

### ISSUE THREAD

**Issue by mel-f** [OP-TEE/optee_test#260]
In regression test 6010, line 1369, the wrong part of _out_ buffer is compared to _data_ buffer: the last sizeof(data) / 2 bytes are compared, whereas the first sizeof(data) / 2 were filled line 1366
``fs_read(&sess, o1, out, sizeof(out) / 2, &n) ``

We should have:
``
        ADBG_EXPECT_BUFFER(c,
                data + sizeof(data) / 2, sizeof(data) / 2,
                out, n);
 ``
Instead of:
``
         ADBG_EXPECT_BUFFER(c,
                data + sizeof(data) / 2, sizeof(data) / 2,
                out + sizeof(data) / 2, n);
``

**Comment by jforissier** [comment]
Hi @mel-f,

You're right. Would you please create a pull request?
