### ISSUE TITLE
Error while building the optee_test

### ISSUE THREAD

**Issue by vabbarap** [OP-TEE/optee_test#265]
Hi,
I am trying to build the optee_test and ran these
/scratch/devel/optee/optee_test> % export TA_DEV_KIT_DIR=$PWD/../optee_os/out/arm-plat-zynqmp/export-ta_arm32
/scratch/devel/optee/optee_test> % export TA_CROSS_COMPILE=$PWD/../toolchains/aarch32/bin/arm-linux-gnueabihf-
/scratch/devel/optee/optee_test> % export HOST_CROSS_COMPILE=$PWD/../toolchains/aarch32/bin/arm-linux-gnueabihf-
/scratch/devel/optee/optee_test> % export TEEC_EXPORT=$PWD/../optee_client/out/export
/scratch/devel/optee/optee_test> %  make

make[1]: Entering directory `/scratch/devel/optee/optee_test/host/xtest'
  CC      /scratch/devel/optee/optee_test/host/xtest/install_ta.c
In file included from /usr/include/sys/stat.h:106:0,
                 from /scratch/devel/optee/optee_test/host/xtest/install_ta.c:19:
/usr/include/bits/stat.h:106:31: error: expected identifier or ‘(’ before ‘[’ token
     __syscall_slong_t __unused[3];
                               ^
make[1]: *** [/scratch/devel/optee/optee_test/out/xtest/install_ta.o] Error 1
make[1]: Leaving directory `/scratch/devel/optee/optee_test/host/xtest'
make: *** [xtest] Error 2

Thanks
Venkatesh

**Comment by jenswi-linaro** [comment]
Try to replace `HOST_CROSS_COMPILE` with `CROSS_COMPILE_HOST` and `TA_CROSS_COMPILE` with `CROSS_COMPILE_TA`.
Also actually taking a look in `optee_test/Makefile` could give some clues.

**Comment by jbech-linaro** [comment]
And besides the `optee_test/Makefile` the main makefile kicking of the build for xtest in build.git will also give answers: https://github.com/OP-TEE/build/blob/master/common.mk#L327-L353

**Comment by vabbarap** [comment]
Replacing HOST_CROSS_COMPILE with CROSS_COMPILE_HOST and TA_CROSS_COMPILE with CROSS_COMPILE_TA worked.

Thanks for the support.
