### ISSUE TITLE
Problem with saved_cipher_iv variable in xml_crypto_api.h

### ISSUE THREAD

**Issue by mel-f** [OP-TEE/optee_test#266]
Hi,
I think there is a misuse of variable `saved_cipher_iv` in host/xtest/xml/include/xml_crypto_api.h.
This variable is intended to be used in `cipher_do_final()` (i.e. `Invoke_Crypto_CipherDoFinal()`) after being filled in `Invoke_Crypto_CipherInit()`. The point is it is reset/filled only if iv != NULL (cf l. 2133), but used anyway. So if you launch two consecutive tests, the first with iv != NULL and the second with iv == NULL, then the second test will use `saved_cipher_iv` from first test.
Example: ./xtest 9176 9177

Note that if you launch these tests separately (i.e. ./xtest 9176 && ./xtest 9177), there is obviously no issue.

I would recommend to take CRYPTO_FREE(saved_cipher_iv); l. 2134 out of the if.

The same remark applies also for `saved_mac_iv`, even if the problematic case is never encountered as the only GP test with iv != NULL is a skipped one.

**Comment by jforissier** [comment]
Hi @mel-f 

I think your analysis is correct, although I fail to understand why I don't see any failure when I run `xtest 9176 9177` on QEMU for instance.
Would you mind creating a pull request with the fix you are proposing?

**Comment by mel-f** [comment]
Hi,
You don't see any failure when launching `xtest 9176 9177` because optee ignores the IV passed in test 9177: cf `syscall_cipher_init()` in optee_os/core/lib/libtomcrypt/src/tee_ltc_provider.c case TEE_ALG_DES3_ECB_NOPAD.

**Comment by jforissier** [comment]
OK makes sense. Thanks for the PR.

**Comment by jbech-linaro** [comment]
Fixed in #269 , closing the issue, thanks!
