### ISSUE TITLE
Socket Communication

### ISSUE THREAD

**Issue by Christian56** [OP-TEE/optee_test#272]
Hi, 
I'm trying to communicate with another device via socket like in regression_2000 (https://github.com/OP-TEE/optee_test/blob/213ca8aaf4eafe9d26af76db7b31d9595ce57e6f/host/xtest/regression_2000.c). however when i try to compile i get the error that some libraries like "tee_isocket.h" are not known, when i try to compile the file. From my understanding it should be included when i exported TA_DEV_KIT_DIR with "export TA_DEV_KIT_DIR=~/devel/optee/optee_os/out/arm/export-ta_arm32/". 
Is my understanding wrong or do you have any suggestions?

**Comment by jenswi-linaro** [comment]
The file you're linking to is the host part of the test. Some of the things done there are just for testing purposes, for instance including "tee_isocket.h". The .h file you mention is only supposed to be used from a TA.
