### ISSUE TITLE
xtest failed to build on android environment

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_test#275]
Hi experts,

As I know, building xtest needs config files from optee-os. And Android.mk in optee-test project add `LOCAL_ADDITIONAL_DEPENDENCIES := $(OPTEE_BIN)` to ask build system to build optee-os first.

Here is the problem, optee-test use the following code to include conf.mk that should be produced from building optee-os. But when makefile read this line, ths conf.mk has not been generated. So this line does not import configs from optee-os.
```
-include $(TA_DEV_KIT_DIR)/host_include/conf.mk
```

This results following code not workable.
```
ifeq ($(CFG_SECSTOR_TA_MGMT_PTA),y)
srcs += install_ta.c
endif

ifeq ($(CFG_SECURE_DATA_PATH),y)
srcs += sdp_basic.c
endif
```

At last, it should build failed with errors:

> vendor/asr/optee/optee_test/host/xtest/xtest_main.c:105: error: undefined reference to 'install_ta_runner_cmd_parser'
> clang.real: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> 15:27:45 ninja failed with: exit status 1

If we build optee-os before build optee-test, the problem disappeared.

**Comment by vchong** [comment]
@zhizhouzh Yes this is a known issue but no good solution has been proposed yet. We've been working around this using `make CFG_SECSTOR_TA_MGMT_PTA=y CFG_SECURE_DATA_PATH=y...`.

@liuyq fyi

**Comment by zhizhouzh** [comment]
@vchong I see, thanks!

**Comment by jforissier** [comment]
If `CFG_SECSTOR_TA_MGMT_PTA` is not defined, why would the linker complain about `install_ta_runner_cmd_parser`? There is an `#ifdef` in xtest_main.c so the function should not be called. Are we talking about parallel build maybe? So that there is a race condition?

If this is indeed a race condition at build time, then fix the build: add a dependency. optee-test should depend on optee-os.

**Comment by zhizhouzh** [comment]
@jforissier I think dependency has been added for this. But before build optee-os, optee-test include configure file that has not been generated. To my understanding, android build system parse whole Android.mk to decide dependence relationship. At parse Makefile phase, this config file doesn't exist. So it lead optee-test doesn't get right config to build itself.

**Comment by jforissier** [comment]
@zhizhouzh ah, I see. Unfortunately I don't know the Android build system well enough to propose a fix :disappointed:

**Comment by jbech-linaro** [comment]
To my knowledge, xtest works on our Android setup, so I'm closing the ticket, having that said, feel free to re-open the ticket if you have more to add to the ticket.
