### ISSUE TITLE
optee_test build problem with android

### ISSUE THREAD

**Issue by casionwoo** [OP-TEE/optee_test#280]
Hello, I'm trying to build optee_test on android

when I try to build it, there's an error message 
**export-ta_arm64/mk/compile.mk:146: error: Automatic variable `$?' isn't supported yet**

Does anybody experience like me or  knows how to solve this problem?

thank you previously..

**Comment by vchong** [comment]
I've been building recently without issues. How are you actually building, and which branch/tag of optee_test?

Some research seems to show that you're using kati for the build? If so, it would appear that kati isn't mature enough to support the build since it doesn't support automatic variable $?.

**Comment by casionwoo** [comment]
@vchong  Thank you foro your reply.

I'm working on 1.1.0 tag cause of my company doesn't want to change to recent version.
and as you mentioned I'm using ckati.

**export-ta_arm64/mk/compile.mk:146: error: Automatic variable `$?' isn't supported yet
18:13:40 ckati failed with: exit status 1**

then do you have any idea how to resolve this problem?

**Comment by vchong** [comment]
Np.

Have you referenced our Androidk makefiles for github.com/OP-TEE/optee_*?

https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey-o is how we build optee_* for aosp. I suppose the build is still using make, and also that the optee_* components are built under the aosp src tree, as part of the full aosp build.

Are you trying to build optee_test outside of aosp src tree? We've not tried that so not much help there. The Android makefiles were written for in-tree builds only.

**Comment by casionwoo** [comment]
Thank you @vchong ,

Actually I situation is a little bit different.
I working on R-car platform. and company has a workspace which includes every optee_* projects except optee_test.

I had to implement on optee projects to make a solution and it's time to test with optee_test.
But unfortunately this workspace have an really old version even have a linux driver as a external module which is deprecated.

So I had to git clone optee_test and checkout to tag 1.1.0 (this version seems the latest version for linux driver)
So I success to build xtest but ta..

If you also have a experience like me or advice, please let me know.
And also I'm trying to download from [https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey-o](https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey-o)

And I will tell you the result

**Comment by vchong** [comment]
Which tag are you using for optee_os/client? optee_test should match that tag, or else the tests might not work properly.

Yes, TAs can be more difficult to build because they depend on the dev kit (export-ta_arm64). In any case, since they're not platform dependent, you should be able to use those built from https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey-o on your platform. Just make sure you check out tag 1.1.0 (or the tag that matches your optee_os/client) before you run make. Also, you don't need to build everything. Just run `make <options> <uuid1>.ta <uuid2>.ta ...` and you can save some time. Obviously this is a hack, but I don't have any better ideas.

**Comment by vchong** [comment]
Forgot to mention, you need to checkout out the proper tags too for optee_os and _client before running make.

**Comment by vchong** [comment]
> If i checkout and build with same tag as my workspace from work, can i use that ta built from hikey workspace to rcar?

I've never tried but I think it should work. Are you building 64- or 32-bit version of optee_os? What's the toolchain used in your workspace from work? https://github.com/linaro-swg/optee_android_manifest/tree/lcr-ref-hikey-o uses the ones in `prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin` and `prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin` in the aosp src tree.

> And one more question is optee_test has a tag 1.1.0 and also other projects have a same tag
> Does It have a proper relationship? If checkout to same tag with other projects? 

Yes, you can see the tags on github. All relevant repos are tagged with a version after testing and verification for each release to ensure compatibility. See https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md for release notes.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
