### ISSUE TITLE
optee_test build failed, os_test TA build error.

### ISSUE THREAD

**Issue by chaozhu1** [OP-TEE/optee_test#297]
Build os_test/ta/os_test failed, who can help me, Thanks~ 
ninja: no work to do.
ninja: no work to do.
vendor/asr/optee/optee_test/product.mk was modified, regenerating...
[684/1057] including ./system/sepolicy/Android.mk ...
./system/sepolicy/Android.mk:111: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[1053/1057] including ./vendor/asr/telephony/lte-telephony/apps/Android.mk ...
vendor/asr/telephony/lte-telephony/apps/atcmd_server/Android.mk:142: warning: "Disable Labtool AT commands for now on 4.2/4.3"
[1057/1057] including ./vendor/nxp/Android.mk ...
No private recovery resources for TARGET_DEVICE aquilac_evb
platform_testing/build/tasks/tests/instrumentation_metric_test_list.mk: warning: continuous_instrumentation_metric_tests: Unknown installed file for module perf-setup.sh 
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module RecyclerViewTests 
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module SettingsFunctionalTests 
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module LauncherFunctionalTests 
platform_testing/build/tasks/tests/instrumentation_test_list.mk: warning: continuous_instrumentation_tests: Unknown installed file for module EmergencyInfoTests 
platform_testing/build/tasks/tests/native_metric_test_list.mk: warning: continuous_native_metric_tests: Unknown installed file for module perf-setup.sh 
ninja: error: 'out/target/product/aquilac_evb/system/lib/optee_armtz/ffd2bded-ab7d-4988-95ee-e4962fff7154.ta', needed by 'out/target/product/aquilac_evb/obj/optee/ta/vendor_asr_optee_optee_test_ta_os_test/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta', missing and no known rule to make it
11:08:14 ninja failed with: exit status 1

#### failed to build some targets (01:24 (mm:ss)) ####

chaozhu@chaozhu-ChengMing-3967:~/phone_android8.1$

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
