### ISSUE TITLE
TEEC_ERROR_BAD_STATE when running regression_1003 test

### ISSUE THREAD

**Issue by yag1hc** [OP-TEE/optee_test#303]
Hi all,

I tried to run the xtest in a Linux ARM aarch64 board.
There already a tee-supplicant running by root
```
root@[device-name]:~# ps -aux | grep tee-supplicant
root      1175  0.0  0.0   2112   468 ?        Ss   06:07   0:00 /usr/bin/tee-supplicant
root      2246  0.0  0.0   1800   400 pts/0    S+   08:35   0:00 grep tee-supplicant'
```

The driver is also loaded
```
root@[device-name]:~# dmesg | grep tee
[    1.558729] optee: probing for conduit method from DT.
[    1.559978] optee: initialized driver
root@[device-name]:~# ls /dev/tee*
/dev/tee0      /dev/teepriv0
```

But I got the error TEEC_ERROR_BAD_STATE when running xtest 1003 and it caused a segmentation fault.
```
optee_test/host/xtest/regression_1000.c:459: arg[n].res has an unexpected value: 0xffff0007 = TEEC_ERROR_BAD_STATE, expected 0x0 = TEEC_SUCCESS
error origin 42
```

Could you please check and let me know the reason? Thanks a lot.
[OPTEE_failed_log.zip](https://github.com/OP-TEE/optee_test/files/2277417/OPTEE_failed_log.zip)

**Comment by jbech-linaro** [comment]
> I tried to run the xtest in a Linux ARM aarch64 board.

What board?

Looking at the log it seems like everything fails, which makes me wonder if it's a something generic missing, but since both tee-supplicant is and the TEE driver/framework has been loaded, that part should at least be OK.
