### ISSUE TITLE
Get UUID.ta from TA code

### ISSUE THREAD

**Issue by SarahL21** [OP-TEE/optee_test#304]
Hi, 
I am working on the secure storage TA. How can I compile its code to get the .ta file in the /lib/optee_armtz directory? 
Thanks,

**Comment by SarahL21** [comment]
Hello, 
Sorry for reopening this issue, but I still cannot find out how to compile my TA. I have read through https://github.com/linaro-swg/optee_examples/blob/master/docs/TA_basics.md#21-devkit-makefile-requirements but I'm still confused. 
Can anyone help? 
Thanks,

**Comment by jbech-linaro** [comment]
Hi @SarahL21 ,

The easiest for you is to simply clone a full QEMU setup according to https://github.com/OP-TEE/build#7-get-and-build-the-solution (even shorter explanation [here](https://github.com/OP-TEE/optee_website/blob/master/faq/README.md#what-is-the-quickest-and-easiest-way-to-try-op-tee)). With that everything will compile for you and later on when you are making changes to any of the files in optee_example. You either run `make optee-examples-common` if you are just interested in compiling or you run `make run` to compile it all and deploy it to the root fs.

**Comment by SarahL21** [comment]
Great explanation! Thank you very much Joakim !!

**Comment by SarahL21** [comment]
The 'make optee-examples-common' returns an error message: 'No rule to make target optee-client, needed by 'optee-examples-common' . Do you have an idea what this could be due to? 
Thanks,

**Comment by jbech-linaro** [comment]
Seems to work here on my side, did you build the entire solution? The optee_examples code depends on both optee_client libs/h-files as well as TA-dev-kit from optee_os. Ideally the Makefile should figure that out by itself, but there might be a missing dependency.

**Comment by SarahL21** [comment]
I have built the entire solution, no issue with that, but when I try to build the app, it gives me the previous error message. And when booting optee, I cannot see my [secure-storage]uuid.ta file in the ~/lib folder..

**Comment by jbech-linaro** [comment]
As long as you follow the same "folder structure" (see below) as the other examples in optee_examples and you are writing the corresponding `CMakeLists.txt` (host part) in your own TA-app folder, things should just work, since the [optee_examples.mk](https://github.com/OP-TEE/build/blob/master/br-ext/package/optee_examples/optee_examples.mk#L10-L24) builds and installs the TA's automatically for you.

To rule out a couple of potential problems, simply just run `make run` whenever you need to test your TA.

Folder structure:
```bash
$ tree -d
.
├── acipher
│   ├── host
│   └── ta
├── aes
│   ├── host
│   └── ta
├── hello_world
│   ├── host
│   └── ta
├── hotp
│   ├── host
│   └── ta
├── random
│   ├── host
│   └── ta
└── secure_storage
    ├── host
    └── ta
```

**Comment by SarahL21** [comment]
Yes I got it !1 Thank you very much for your support !!
