### ISSUE TITLE
OP-TEE stuck at rainbow screen on CM3

### ISSUE THREAD

**Issue by SarahL21** [OP-TEE/optee_test#305]
Hello,
I am trying to deploy OP-TEE on a CM3 to have access to usb boot and rpmb features. The problem is, Op-tee doesn't boot on the Compute Module 3. I have tried to set the LOG_LEVEL at 10 for debugging; while booting the same image on a RPi3, it boots and I have an output on the serial console, which is not the case with the CM3: Rainbow screen + no output on the serial console. (PS: the pins I am using are correct I guess : 14 and 15 since I have already had an output for Raspbian on the same platform). 
Does anyone have an idea about that or had to boot optee on a CM3 before? Is it due to compatibility problems between optee and the CM3? (I don't think so since CM3 and RPi3 have the same chip  (I suppose) with some more features on the CM3: suppressing eMMC/SD boot and forcing USB boot and so on...)
Thanks,

**Comment by jbech-linaro** [comment]
> I am trying to deploy OP-TEE on a CM3 to have access to usb boot and rpmb features. The problem is, Op-tee doesn't boot on the Compute Module 3.

We haven't tested running the RPi3 build using CM3. We've only been using it with the RPi3 (and not the the Model B+). Some people have reported issues with the B+ also, so I wouldn't be surprised if CM3 also differs a bit which makes fail during boot. At the moment we have no time to spare to work with newer revisions of RPi's and RPi derivatives, so the best we can do here is trying to assist by answer questions by reading boot logs, build configurations etc. 

> I have tried to set the LOG_LEVEL at 10 for debugging

[OP-TEE's log level is in the interval 0-4](https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/include/trace_levels.h), so setting it higher than 4 doesn't make sense.
