### ISSUE TITLE
xtext failed in 1015 

### ISSUE THREAD

**Issue by vsivanagulu** [OP-TEE/optee_test#306]
I am using linnx kernel 4.8 and optee  OS, client , Xtest  versions are 3.2.0. when i run **XTEST**  in board **xtest** showing below logs at regression_1015.

> * regression_1015 FS hash-tree corner cases
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001              # is this  an ERROR or just log.
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001               # I am not aware of this test logs.
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
> E/TC:0 do_range:229 error: res = 0xf0100001
>   regression_1015 OK
>  
> * regression_1016 Test TA to TA transfers (in/out/inout memrefs on the stack)
>   regression_1016 OK
>  
> * regression_1017 Test coalescing memrefs
>   regression_1017 OK
>  
> * regression_1018 Test memref out of bounds
>   regression_1018 OK
>  
> * regression_1019 Test dynamically linked TA
> E/TC:0 
> E/TC:0 TA panicked with code 0x0

and at the end of xtest showing all test are passed 

> +-----------------------------------------------------
> 16081 subtests of which 0 failed
> 74 test cases of which 0 failed
> 0 test case was skipped
> TEE test application done!

Is this an error or just a function log. Please clarify this doubt???

**Comment by jforissier** [comment]
Not an error, just a function log as you said.

**Comment by vsivanagulu** [comment]
thanks you.
