### ISSUE TITLE
Optee_test for GP testsuite v2.1.0

### ISSUE THREAD

**Issue by ncpsa** [OP-TEE/optee_test#308]
Hi,

To build and validate GP testsuite v2.1.0,
As mentioed in the README.md, I will have to CFG_GP_PACKAGE_PATH to my testsuite xml files and build xtest application.
Does it work?.
I have seen "**# Note that only TEE_Initial_Configuration-Test_Suite_v1_1_0_4-2014_11_07 is supported**" in optee_test's Makefile.
Does it compatible to testsuite v2.1.0?

Please clarify.

Thanks in Advance.

**Comment by jforissier** [comment]
Hi @ncpsa,

No, test suite v2.1.0 will not work "right out of the box", but if you are willing to spend time to make it work, patches are certainly welcome :))

**Comment by jforissier** [comment]
I don't know how different is the new test suite from the old one, so it's hard to say.
You can try to use the existing `TEE.xsl`, and see how it applies to the new source. Then make the needed changes as you meet issues. If it turns out to be impractical, then we'll have to find another way ;-)
