### ISSUE TITLE
Issue faced while running xtest 

### ISSUE THREAD

**Issue by vikaspot** [OP-TEE/optee_test#336]
Hi I am facing issue while running xtest.

xtest
xtest: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by xtest)

Can you please help what could be issue ?

**Comment by jforissier** [comment]
Hi @vikaspot ,

It means the `libc.so` that is in the root FS of your board is older than the one that was used to link  `xtest` (which comes with the cross-compiler, typically).
I see two ways to fix this: either upgrade your root FS, or use an older cross-compiler.

**Comment by vikaspot** [comment]
But how come hello_world app is also using same library and no issue in runtime ?

**Comment by jforissier** [comment]
I guess it depends on the functions it pulls from the library (it is the symbols that are versioned).
