### ISSUE TITLE
about gp testsuite patch

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_test#34]
Dear all:
I want to build gp test suite. so i need to apply the patch. but when i do this, it can't apply.

my shell shows:
#!/bin/bash

export TA_DEV_KIT_DIR=******/optee/tdk/ta_export
export CFG_GP_TESTSUITE_ENABLE=y
export CFG_DEV_PATH=******/optee
export CFG_GP_PACKAGE_PATH=******/optee/optee_test/package/testsuite/global_platform/api_1.0/TEE_Initial_Configuration-Test_Suite_v1_1_0_4-2014_11_07

export CFG_GP_XSL_PACKAGE_PATH=******/optee/optee_test/package/testsuite/global_platform/api_1.0/TEE_Initial_Configuration-Test_Suite_v1_1_0_4-2014_11_07
make patch

and I have change the name "GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM"  to "TEE_Initial_Configuration-Test_Suite_v1_1_0_4-2014_11_07"

how can i go next?
thanks in advance!

**Comment by pascal-brand-st-dev** [comment]
I am preparing a pull-request with an updated readme about this.

Note that you need to purchase the GP test suite from https://www.globalplatform.org/store.asp

**Comment by pascal-brand-st** [comment]
#35 has been merged. GP tests inclusion has been refactored as well as the documentation. Please let us know if we can close this issue.

**Comment by neil1899** [comment]
thanks so much!
