### ISSUE TITLE
Regression Tests on Python 2.7

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_test#345]
I try to build OP-TEE with Python3 but it fails on OP-TEE tests due to this line: https://github.com/OP-TEE/optee_test/blob/e4f6f76b4cb5763112f4722981f84a26f4ac7e55/scripts/file_to_c.py#L32
because python 2 and 3 behaves differently here.
Since Python 2.7 will be soon deprecated (jan, 2020) is there any plan to update regression tests (and all other scripts) to Python 3?

**Comment by jenswi-linaro** [comment]
Patches are welcome! :-)

**Comment by sbranden** [comment]
It should be fixed here:
https://github.com/OP-TEE/optee_test/commit/6271160639002a2580d80b75b5397a96d56329f2
