### ISSUE TITLE
TA not found

### ISSUE THREAD

**Issue by PratikGajera** [OP-TEE/optee_test#355]
Dear Team,

I am executing below test case on imx6ull board and getting error **"TA not found"**. As per my understanding, no need to required TA application in user space for this test case, because PTA application is already in optee os.  Is TA application required in User space (`/lib/optee-armtz`)?
```
$ xtest --stats --pager

DBG [458] TEES:spawn_thread:553: Spawning a new thread
DBG [458] TEES:process_one_request:586: looping
DBG [678] TEES:process_one_request:586: looping
DBG [458] TEES:process_one_request:586: looping
DBG [678] TEES:spawn_thread:553: Spawning a new thread
DBG [458] TEES:process_one_request:586: looping
DBG [678] TEES:process_one_request:586: looping
DBG [679] TEES:process_one_request:586: looping
DBG [458] TEES:process_one_request:586: looping
DBG [458] TEES:process_one_request:586: looping
DBG [458] TEES:process_one_request:586: looping
DBG [678] TEES:process_one_request:586: looping
DBG [679] TEES:process_one_request:586: looping
DBG [458] TEES:process_one_request:586: looping
DBG [678] TEES:process_one_request:586: looping
DBG [679] TEES:process_one_request:586: looping
DBG [458] TEES:process_one_request:586: looping
DBG [678] TEES:try_load_secure_module:118: Attempt to load /lib/optee_armtz/d96a5b40-e2c7-b1af-8794-1002a5d5c61b.ta
DBG [678] TEES:try_load_secure_module:127: failed to open the ta /lib/optee_armtz/d96a5b40-e2c7-b1af-8794-1002a5d5c61b.ta TA-file
DBG [678] TEES:try_load_secure_module:118: Attempt to load /lib/optee_armtz/d96a5b40-e2c7-b1af-87941002a5d5c61b.ta
DBG [678] TEES:try_load_secure_module:127: failed to open the ta /lib/optee_armtz/d96a5b40-e2c7-b1af-87941002a5d5c61b.ta TA-file
ERR [678] TEES:load_ta:274:   TA not found
DBG [678] TEES:process_one_request:586: looping
DBG [679] TEES:process_one_request:586: looping
xtest: TEEC_OpenSession: res 0xffff0008 err_orig 0x3
```
Please suggest me, what are the things missing here.

Thanks,
PG

**Comment by PratikGajera** [comment]
@vchong thanks for providing suggestion.
I used this variable CFG_WITH_STATS=y while building OPTEE os. But, still getting same error.

**Comment by vchong** [comment]
@PratikGajera you're welcome.
Please provide details about the build process, commands, image updates and logs, else there's no way to troubleshoot.

**Comment by PratikGajera** [comment]
I am working on imx6ull board and please find following software details:

U-boot version: 2.8.5
OPTEE version: 3.5.0
Kernel version: 4.9.144

Building and deploying optee os with the following command:

Build:

make V=1 PLATFORM=imx-mx6ulevk ARCH=arm CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x81000000 CFG_DT=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_TEE_TA_LOG_LEVEL=4 CFG_WITH_STATS=y

Deploy:
[Bootup_log.txt](https://github.com/OP-TEE/optee_test/files/3395972/Bootup_log.txt)

Boot optee os from U-boot as below command and you can see bootup log also attached here.

$ bootm {optee_add_r} {fdt_add_r}

Also compiled optee_client (tee-supplicant and libteec) using make command.

After getting console:
First, run tee-supplicant as daemon
second, run xtest --stats --pager.

@vchong Can you provide me complete PTA demo example like (optee_example: https://github.com/linaro-swg/optee_examples) that how to call PTA application from OPTEE?
So that, better way to understand PTA application execution flow.

Thanks,
PG

**Comment by vchong** [comment]
Do you have logs from the `optee_os` side when you run `xtest`? Something like below?
```
D/TC:? 0 tee_ta_init_pseudo_ta_session:280 Lookup pseudo TA d96a5b40-e2c7-b1af-8794-1002a5d5c61b
D/TC:? 0 tee_ta_init_pseudo_ta_session:293 Open stats.ta
D/TC:? 0 tee_ta_init_pseudo_ta_session:307 stats.ta : d96a5b40-e2c7-b1af-8794-1002a5d5c61b
D/TC:? 0 tee_ta_close_session:496 csess 0xe16b8d0 id 1
D/TC:? 0 tee_ta_close_session:515 Destroy session
```

It still feels like your `optee_os` doesn't contain the PTA. You can verify this by running `strings tee.bin | grep "stats\.ta"` and see if it returns empty.

> Can you provide me complete PTA demo example like (optee_example: https://github.com/linaro-swg/optee_examples) that how to call PTA application from OPTEE?

The way to call PTA app is the same for a user mode TA, so that doesn't seem like your problem. Anyway, there's no PTA demo in `optee_examples`, but you can refer to https://github.com/OP-TEE/optee_test/blob/master/host/xtest/stats.c instead which is a complete and straightforward example. https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_1000.c also calls a PTA but is a bit harder to read due to wrapper APIs.

**Comment by PratikGajera** [comment]
> Do you have logs from the `optee_os` side when you run `xtest`? Something like below?

No, this is also one issue. I can't see any logs on user space after enabling CFG_TEE_TA_LOG_LEVEL=4 variable in optee os.

> It still feels like your `optee_os` doesn't contain the PTA. You can verify this by running `strings tee.bin | grep "stats\.ta"` and see if it returns empty.

Yes, it returned empty. stats object file is present in this directory out/arm-plat-imx/core/arch/arm/pta/. It means that it build successfully. Now, I confused, why stats PTA application is not part of tee.bin.

**Comment by vchong** [comment]
> No, this is also one issue. I can't see any logs on user space after enabling CFG_TEE_TA_LOG_LEVEL=4 variable in optee os.

In your Bootup_log.txt file, there's a line that says `I/TC: Switching off console` after `optee_os` is finished booting, so you'll have to find out why it's doing that on the platform.

> Now, I confused, why stats PTA application is not part of tee.bin.

Do you see "stats.c" in your out/arm/core/tee.map? I'm not sure how else to proceed either. Maybe you can try building the qemu or qemuv8 example and compare the build logs with yours to see what the differences are.

**Comment by PratikGajera** [comment]
> In your Bootup_log.txt file, there's a line that says `I/TC: Switching off console` after `optee_os` is finished booting, so you'll have to find out why it's doing that on the platform.

I guess this line is indicated to switch log from optee to kernel. When i used  previous optee commit: 1a4fa97dca1dd980b615f7e8355a3fbeed4b4509, then the same line getting and optee log has been printed on serial console while executing optee_examples. 

> Do you see "stats.c" in your out/arm/core/tee.map?

No.

> DBG [678] TEES:try_load_secure_module:118: Attempt to load /lib/optee_armtz/d96a5b40-e2c7-b1af-8794-1002a5d5c61b.ta
> DBG [678] TEES:try_load_secure_module:127: failed to open the ta /lib/optee_armtz/d96a5b40-e2c7-b1af-8794-1002a5d5c61b.ta TA-file
> DBG [678] TEES:try_load_secure_module:118: Attempt to load /lib/optee_armtz/d96a5b40-e2c7-b1af-87941002a5d5c61b.ta
> DBG [678] TEES:try_load_secure_module:127: failed to open the ta /lib/optee_armtz/d96a5b40-e2c7-b1af-87941002a5d5c61b.ta TA-file

Go back to first comment, indicate below logs that tee-supplicant application is trying to load TA application from system file-system (/lib/optee_armtz), but actual no TA on user space (when PTA application concept, right) for this Host application, so it is giving error. I think something wrong from here.

**Comment by vchong** [comment]
> I guess this line is indicated to switch log from optee to kernel. When i used previous optee commit: 1a4fa97dca1dd980b615f7e8355a3fbeed4b4509, then the same line getting and optee log has been printed on serial console while executing optee_examples.

Ok.

> Go back to first comment, indicate below logs that tee-supplicant application is trying to load TA application from system file-system (/lib/optee_armtz), but actual no TA on user space (when PTA application concept, right) for this Host application, so it is giving error. I think something wrong from here.

I don't see what's wrong here. The system tries to load the PTA first, doesn't find it and so moves on to trying load it from the regular file system.

Anyway, I just tried a build on master and it seems fine.
```
make PLATFORM=imx-mx6ulevk ARCH=arm CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x81000000 CFG_DT=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_TEE_TA_LOG_LEVEL=4 CFG_WITH_STATS=y CROSS_COMPILE=/path/to/arm-linux-gnueabihf- CROSS_COMPILE_core=/path/to/arm-linux-gnueabihf- CROSS_COMPILE_ta_arm32=/path/to/arm-linux-gnueabihf-

for i in tee-pager.bin tee.bin tee.elf; do echo $i; strings $i | grep "stats\.ta"; done
tee-pager.bin
stats.ta
tee.bin
stats.ta
tee.elf
stats.ta
TA_NAME "stats.ta"
```

**Comment by PratikGajera** [comment]
@vchong Thanks for your suggestion.
In order to update latest optee vesrion v3 (146a256b264a275a5930efa3989205b04216e984), stats PTA application is executed in optee os while calling from non-secure os using stats host application.
