### ISSUE TITLE
xtest 2000 cases failed when running tee-supplicant as non-root

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_test#356]
When running tee-supplicant as non-root, other xtest cases are all OK except xtest 2000 family cases.

Calling socket() in sock_connect in optee-client tee_socket.c will return permission denied.
Anyone met this issue? How to fix it?

I have changed the following things:
chmod 666 /dev/tee0
chmod 666 /dev/teepriv0
chown -R xxxx:xxxx /data/tee (xxxx:xxxx are non-root user and group)
chmod -R 760 /data/tee

**Comment by jenswi-linaro** [comment]
The function `socket()` fails so that means that the process isn't privileged to create sockets.

**Comment by vchong** [comment]
@jingdlu Try referring to https://github.com/OP-TEE/build/blob/master/br-ext/package/optee_client/S30optee for more details.

**Comment by jingdlu** [comment]
> The function `socket()` fails so that means that the process isn't privileged to create sockets.

Thanks for response.
However, in xtest 2001, tee-supplicant is responsible for creating sockets. How does tee-supplicant have that privilege? I change tee-supplicant as the following:
# chown xxxx:xxxx tee-supplicant (xxxx:xxxx are non-root user and group)
# ls -la /usr/sbin/ | grep tee
-rwxr-xr-x    1 xxxxx        xxxxx           191016 Jul 10  2019 tee-supplicant

Does your tee-supplicant have root:root?

**Comment by jenswi-linaro** [comment]
Perhaps an issue with SELinux or some other access control mechanism?

**Comment by jingdlu** [comment]
Thanks for suggestion, I will do more investigation. Just close this issue for now.
