### ISSUE TITLE
Not able to create Object in secure_storage in OP-TEE

### ISSUE THREAD

**Issue by zineb-creator** [OP-TEE/optee_test#361]
after compilation of the example secure_storage the logs of the secure world display this error : E/TA:  create_raw_object:133 TEE_CreatePersistentObject failed 0xffff000c 
and i don't know why ?
if someone can help i'll be grateful .

**Comment by jbech-linaro** [comment]
Device? Setup? More logs? Our [HiKey](https://optee.mooo.com:5000/logs/OP-TEE/optee_os/3260/315946186/ef475f1356cfc6ecf8cd94dc67c9e9837a62a4fa#end-01-hikey6220-test) regression testing seems happy with it (no errors) and I cannot recall hearing other people having issues with this.

**Comment by zineb-creator** [comment]
At first i test it on Qemu and it works well , But on bcm96xxx it doesn't i just have these logs :
Prepare session with the TA                                                     
                                                                                
Test on object "object#1"                                                       
- Create and load object in the TA secure storage                               
M/TC:0 entry_invoke_command:419 invoke: client_id 1549 process_id 1549 

### when i type ctrl+c : 
^CE/TA:  create_raw_object:131 je suis l�à aussi5                               
E/TA:  create_raw_object:133 TEE_CreatePersistentObject failed 0xffff000c

**Comment by zineb-creator** [comment]
At first i test it on Qemu and it works well , But on bcm96xxx it doesn't i just have these logs :
Prepare session with the TA

Test on object "object#1"

    Create and load object in the TA secure storage
    M/TC:0 entry_invoke_command:419 invoke: client_id 1549 process_id 1549

when i type ctrl+c :

^CE/TA: create_raw_object:133 TEE_CreatePersistentObject failed 0xffff000c

**Comment by zineb-creator** [comment]
At first i test it on Qemu and it works well , But on bcm96xxx it doesn't i just have these logs :

Prepare session with the TA
Test on object "object#1"
Create and load object in the TA secure storage
M/TC:0 entry_invoke_command:419 invoke: client_id 1549 process_id 1549

when i type ctrl+c :

^CE/TA: create_raw_object:133 TEE_CreatePersistentObject failed 0xffff000c
