### ISSUE TITLE
Optee test 1011 uses a 0-second timeout while INFINITE_TIMEOUT should probably be better suited.

### ISSUE THREAD

**Issue by c-auger** [OP-TEE/optee_test#362]
Hi, in `ta/rpc_test/ta_rpc.c`, timeouts provided to TEE_OpenTASession and other TA entrypoints are 0 milliseconds timeout.

According to the GP specification, this could end up with a TEE_ERROR_CANCEL returned, and the test expects TEE_SUCCESS.

I think, that it should be safer to replace these invocations with TEE_TIMEOUT_INFINITE as timeouts.

See section 4.10 of TEE Internal Core API Specification:

If the operation has not reached the TA yet but has been queued in the TEE, then it SHALL be retired from the queue and fail with the return code:
o For an REE Client, TEEC_ERROR_CANCEL and the origin TEEC_ORIGIN_TEE;
o For a TEE Client, TEE_ERROR_CANCEL and the origin TEE_ORIGIN_TEE.

0 is no special value. TEE_TIMEOUT_INFINITE is specified as being 0xFFFFFFFF.

Thus a conformant application should probably fail in this test.

An easy fix would be to replace all 0 timeouts with TEE_TIMEOUT_INFINITE.

**Comment by jenswi-linaro** [comment]
I agree. Would you mind creating a pull request?

**Comment by c-auger** [comment]
Fixed in pull request #367.
