### ISSUE TITLE
Test 4009 uses invalid key pair for ECDSA operation

### ISSUE THREAD

**Issue by c-auger** [OP-TEE/optee_test#363]
In test 4009, some implementations might want to check the provided keypair, and fail while doing so.

>		/*
>		 * The public value is not used. This is why we provide
>		 * another buffer
>		 */
>		xtest_add_attr(&param_count, params,
>				TEE_ATTR_ECC_PUBLIC_VALUE_X,
>			       pt->private, size_bytes);
>		xtest_add_attr(&param_count, params,
>				TEE_ATTR_ECC_PUBLIC_VALUE_Y,
>			       pt->private, size_bytes);

Public_x and Public_y are not allowed to be random values for a usable key.
Thus if the cryptographic library in use perform some validation test, then it will fail and the key creation might be rejected.

According to specification of TEE_PopulateTransientObject,

> The Implementation can attempt to detect whether the attribute values are consistent;
> for example, if the numbers supposed to be prime are indeed prime.
> However, it is not required to do these checks fully and reliably.
> If it detects invalid attributes, it SHALL return the error code TEE_ERROR_BAD_PARAMETERS and SHALL NOT panic.
> If it does not detect any inconsistencies, it SHALL be able to later proceed with all operations associated with the object without error.
> In this case, it is not required to make sensible computations, but all computations SHALL terminate and output some result.

Thus, I would tend to think that using legitimate values for public_x and public_y should be better for a non regression test. Such x and y can be obtained simply from `pt->public_x` and `pt->public_y`. If other values than this x and this y should be tested, then it should be possible to generate an other key and extract x and y from it.

**Comment by jenswi-linaro** [comment]
A pull request is welcome! :-)

**Comment by c-auger** [comment]
Fixed in P-R #365
