### ISSUE TITLE
Passing NULL as object pointer to TEE_CreatePersistentObject

### ISSUE THREAD

**Issue by c-auger** [OP-TEE/optee_test#364]
In `ta/storage/storage.c`, the function `ta_storage_cmd_create_overwrite` calls `TEE_CreatePersistentObject` with `NULL` as pointer to a `TEE_ObjectHandle`.

The GP Specification does not seem to allow this, and the only interpretation I can make of the specification is to panic.

I would suggest replacing

>TEE_Result ta_storage_cmd_create_overwrite(uint32_t param_types,
>					   TEE_Param params[4])
>{
>	TEE_Result res;
>
>	ASSERT_PARAM_TYPE(TEE_PARAM_TYPES
>			  (TEE_PARAM_TYPE_MEMREF_INPUT,
>			   TEE_PARAM_TYPE_VALUE_INPUT,
>			   TEE_PARAM_TYPE_NONE,
>			   TEE_PARAM_TYPE_NONE));
>
>	res = TEE_CreatePersistentObject(params[1].value.a,
>		 params[0].memref.buffer, params[0].memref.size,
>		 TEE_DATA_FLAG_OVERWRITE,
>		 NULL, NULL, 0, NULL);
>	return res;
>}

 with

>TEE_Result ta_storage_cmd_create_overwrite(uint32_t param_types,
>					   TEE_Param params[4])
>{
>	TEE_Result res;
>	TEE_ObjectHandle o;
>
>	ASSERT_PARAM_TYPE(TEE_PARAM_TYPES
>			  (TEE_PARAM_TYPE_MEMREF_INPUT,
>			   TEE_PARAM_TYPE_VALUE_INPUT,
>			   TEE_PARAM_TYPE_NONE,
>			   TEE_PARAM_TYPE_NONE));
>
>	res = TEE_CreatePersistentObject(params[1].value.a,
>		 params[0].memref.buffer, params[0].memref.size,
>		 TEE_DATA_FLAG_OVERWRITE,
>		 NULL, NULL, 0, &o);
>	TEE_CloseObject(o);
>	return res;
>}

which has clearer semantics.

The semantics tells that in case of success the object handle pointed by `object` should be set to a new opened object handle. Setting it to `NULL` thus cannot make the operation successful.
You can also see this as a `NULL` pointer dereference, and it seems to fit in the panic reasons of the specification.

**Comment by etienne-lms** [comment]
You are write.Yes, you are right.
Maybe also update `TEE_CreatePersistentObject()`: according to the spec, the function should panic the TA.
Could you create a P-Rs with changes proposal? One in optee_examples with your proposal that looks right. A P-R in optee_os to fix `TEE_CreatePersistentObject()`.

**Comment by c-auger** [comment]
Fixed in #368
