### ISSUE TITLE
clang support

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_test#370]
@jforissier Is it possible to 'extend' the clang support you're working on for `optee_os` to `ta/` here as well? We know the CA code here can already be built using clang, but the TA code hasn't been tested at all so far.

**Comment by jforissier** [comment]
Hi @vchong,

You're right, in https://github.com/OP-TEE/optee_os/pull/3268 I haven't considered the "TA Dev kit" makefiles. I'll look into it.

**Comment by jforissier** [comment]
@vchong new patch pushed to https://github.com/OP-TEE/optee_os/pull/3268.

**Comment by vchong** [comment]
@jforissier Awesome! Will test building both `optee_os` and TAs using clang in AOSP when the PR is merged. Thanks!
