### ISSUE TITLE
 xtest_teec_open_session Segmentation fault

### ISSUE THREAD

**Issue by da1234cao** [OP-TEE/optee_test#407]
Hello,
My environment : ubuntu18.04+qemu_v8 3.3
I have successfully built it.

Then I apply the pathes:[optee_fuzzer](https://github.com/Riscure/optee_fuzzer).
Build it successfully.
Run xtest

There is an error.
```shell
Welcome to Buildroot, type root or test to login
buildroot login: root
# xtest 
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################
 
* regression_1001 Core self tests
  regression_1001 OK
 
* regression_1002 PTA parameters
  regression_1002 OK
 
* regression_1003 Core internal read/write mutex
    Number of parallel threads: 6 (2 writers and 4 readers)
    Max read concurrency: 2
    Max read waiters: 1
    Mean read concurrency: 1.4375
    Mean read waiting: 1
  regression_1003 OK
 
* regression_1004 Test User Crypt TA
o regression_1004.1 AES encrypt
  regression_1004.1 OK
o regression_1004.2 AES decrypt
  regression_1004.2 OK
o regression_1004.3 SHA-256 test, 3 bytes input
  regression_1004.3 OK
o regression_1004.4 AES-256 ECB encrypt (32B, fixed key)
  regression_1004.4 OK
o regression_1004.5 AES-256 ECB decrypt (32B, fixed key)
  regression_1004.5 OK
  regression_1004 OK
 
* regression_1005 Many sessions
  regression_1005 OK
 
* regression_1006 Test Basic OS features
  regression_1006 OK
 
* regression_1007 Test Panic
  regression_1007 OK
 
* regression_1008 TEE internal client API
o regression_1008.1 Invoke command
  regression_1008.1 OK
o regression_1008.2 Invoke command with timeout
  regression_1008.2 OK
o regression_1008.3 Create session fail
n = 0
n = 1
n = 2
n = 3
n = 4
n = 5
n = 6
n = 7
n = 8
n = 9
n = 10
n = 11
n = 12
n = 13
n = 14
n = 15
n = 16
n = 17
n = 18
n = 19
n = 20
n = 21
n = 22
n = 23
n = 24
n = 25
n = 26
n = 27
n = 28
n = 29
n = 30
n = 31
n = 32
n = 33
n = 34
n = 35
n = 36
n = 37
n = 38
n = 39
n = 40
n = 41
n = 42
n = 43
n = 44
n = 45
n = 46
n = 47
n = 48
n = 49
n = 50
n = 51
n = 52
n = 53
n = 54
n = 55
n = 56
n = 57
n = 58
n = 59
n = 60
n = 61
n = 62
n = 63
n = 64
n = 65
n = 66
n = 67
n = 68
n = 69
n = 70
n = 71
n = 72
n = 73
n = 74
n = 75
n = 76
n = 77
n = 78
n = 79
n = 80
n = 81
n = 82
n = 83
n = 84
n = 85
n = 86
n = 87
n = 88
n = 89
n = 90
n = 91
n = 92
n = 93
n = 94
n = 95
n = 96
n = 97
n = 98
n = 99
  regression_1008.3 OK
o regression_1008.4 Load corrupt TA
regression_1000.c:634: xtest_teec_open_session(&session, &uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
Segmentation fault


**It says "Segmentation fault"**


```shell
 ps -aux | grep tee-supplicant
dacao     8440  0.0  0.0  21532  1004 pts/3    S+   09:59   0:00 grep --color=auto tee-supplicant



```shell
dmesg | grep optee
[    2.520510] optee: probing for conduit method from DT.
[    2.521750] optee: revision 3.3 (ee595e95)
[    2.527857] optee: dynamic shared memory is enabled
[    2.528371] optee: initialized driver

**Comment by jbech-linaro** [comment]
You can try run it with strace for example, that might give some clues. Alternatively fire up GDB ([instructions](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#gdb-normal-world)) and debug it. Maybe @MartijnB can chime in to say whether this is something known to him.

**Comment by jforissier** [comment]
@jbech-linaro +1 and to be honest this does not surprise me much because the main focus for `xtest` has always been regression testing. So, it expect things will mostly go well, and as a result error handling and cleanup is sometimes a bit lacking ;-) But it doesn't have to be like that of course and fixes are welcome.

**Comment by da1234cao** [comment]
Thanks. I try GDB to watch the strace,later.

**Comment by jbech-linaro** [comment]
> @jbech-linaro +1 and to be honest this does not surprise me much because the main focus for `xtest` has always been regression testing.

I've been subjected to Googletest recently, I took some time to get used to it, but I've actually started to like it. It has some nice features, the filtering works really nice, you can disable tests (without having to to ifdef), you can shuffle the tests to run in a random order, you can group tests into different fixtures with different setup and tear down functions. There are also support "death tests" that can catch when things are going really bad. I'm not proposing to rewrite/replace xtest, but I've learnt that there are candidates out there that are a bit more flexible (and robust).

**Comment by jforissier** [comment]
> I'm not proposing to rewrite/replace xtest

Well, why not :wink: Could be an nice project, although a bit tedious I'm afraid!

**Comment by jbech-linaro** [comment]
> > I'm not proposing to rewrite/replace xtest
> 
> Well, why not  Could be an nice project, although a bit tedious I'm afraid!

Mostly because the "a bit tedious I'm afraid!" part :) I guess it'll take a month to rewrite it for Googletest and make it work. Then there is probably one more month trying to upstream changes (Buildroot, IBART etc etc). An alternative would be to do changes incrementally. But as said, I'm not going to push for it :)

**Comment by da1234cao** [comment]
**The `xtest question`  may be about gcc version.**
**I change the gcc version. The xtest question no longer appear.**

First, Reference this article: [GDB - Normal world](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#gdb-normal-world) .

`rm -rf <qemu-v8-project>/out-br`
`make  run GDBSERVER=y`

Before `make run` ,I hava to modify the Makefile to rebuild.
because , after apply the patches, the Makefile `all`  target has changed.
```shell
#after apply the patches
#all: arm-tf	afl afl-tee

#change it now
all: arm-tf qemu soc-term linux buildroot optee-client afl afl-tee
```

_However, build to buildroot, there is question._
```shell
Makefile:849: recipe for target 'all' failed
make[3]: *** [all] Error 2
package/pkg-generic.mk:229: recipe for target '/home/dacao/exercise/optee_v8/out-br/build/host-binutils-2.29.1/.stamp_built' failed
make[2]: *** [/home/dacao/exercise/optee_v8/out-br/build/host-binutils-2.29.1/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: 离开目录“/home/dacao/exercise/optee_v8/out-br”
common.mk:201: recipe for target 'buildroot' failed
```

I google the question.  I find this is a question about gcc. [index : buildroot](https://git.buildroot.net/buildroot/commit/?id=78af2a63625a0893259ceb2f6cfb5b6ab1431419) 
My gcc version is gcc-7.
**So I use `update-alternatives` changing to gcc-5 to rebuild .**


After rebuild ---> run xtest  --->xtest without any fault .
So I think the question maybe about gcc version.
Now this is the no fault xtest.
```shell
* regression_1008 TEE internal client API
o regression_1008.1 Invoke command
  regression_1008.1 OK
o regression_1008.2 Invoke command with timeout
  regression_1008.2 OK
o regression_1008.3 Create session fail
n = 0
n = 1
n = 2
n = 3
n = 4
n = 5
n = 6
n = 7
n = 8
n = 9
n = 10
n = 11
n = 12
n = 13
n = 14
n = 15
n = 16
n = 17
n = 18
n = 19
n = 20
n = 21
n = 22
n = 23
n = 24
n = 25
n = 26
n = 27
n = 28
n = 29
n = 30
n = 31
n = 32
n = 33
n = 34
n = 35
n = 36
n = 37
n = 38
n = 39
n = 40
n = 41
n = 42
n = 43
n = 44
n = 45
n = 46
n = 47
n = 48
n = 49
n = 50
n = 51
n = 52
n = 53
n = 54
n = 55
n = 56
n = 57
n = 58
n = 59
n = 60
n = 61
n = 62
n = 63
n = 64
n = 65
n = 66
n = 67
n = 68
n = 69
n = 70
n = 71
n = 72
n = 73
n = 74
n = 75
n = 76
n = 77
n = 78
n = 79
n = 80
n = 81
n = 82
n = 83
n = 84
n = 85
n = 86
n = 87
n = 88
n = 89
n = 90
n = 91
n = 92
n = 93
n = 94
n = 95
n = 96
n = 97
n = 98
n = 99
  regression_1008.3 OK
  regression_1008 OK
 
* regression_1009 TEE Wait
o regression_1009.1 TEE Wait 0.1s
  regression_1009.1 OK
o regression_1009.2 TEE Wait 0.5s
  regression_1009.2 OK
o regression_1009.3 TEE Wait 2s cancel
  regression_1009.3 OK
o regression_1009.4 TEE Wait 2s
  regression_1009.4 OK
  regression_1009 OK
......
......
regression_2004 OK
+-----------------------------------------------------
16011 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```


---
It can xtest normal, It is good message for me.
I'm not going to reproduce the problem. 

One word, I must said:' Thank you very much'.
This is my second time to creat issua. Thank you for your prompt reply.
:smile:

**Comment by da1234cao** [comment]
**Here I want to ask a question : how to run myself ta/ca in the system ?**

**I have known how to creat simple ta/ca and build it .**
Reference :[GlobalPlatform API](https://optee.readthedocs.io/en/latest/architecture/globalplatform_api.html#introduction)、[GlobalPlatform API](https://optee.readthedocs.io/en/latest/architecture/globalplatform_api.html)

**But I dont know how to run ca.**
1. First try: [Host-Guest folder sharing ---qeum](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8)
* I put myself ta/ca into folder share_folder so that computer can find it in normal world.
* I put uuid.ta(uuid is numbers.uuid.ta is the binary ta file name) into `/out-br/target/lib/optee_armtz`
* when I run the executable ca .This make error.

2. Second try: read the Makefile and common.mk 
Maybe I know the basic way to apply the ta/ca into linux/optee. But I fail.
* In Makefile : I add my target.
```shell
#optee_mytest
optee_mytest: optee_mytest-common
optee_mytest-clean: optee_mytest-clean-common

all: all: arm-tf qemu soc-term linux buildroot optee-client optee_mytest-common
clean: arm-tf-clean edk2-clean　linux-clean optee-os-clean qemu-clean \
	soc-term-clean check-clean buildroot-clean optee-client-clean optee_mytest-clean-common
```

* In common.mk: I add target 
```shell
#add path
OPTEE_MYTEST_PATH ?= $(ROOT)/optee_my_test

###########################################################################
#add build process
# optee_my_test
###########################################################################
OPTEE_MYTEST_COMMON_FLAGS ?= HOST_CROSS_COMPILE=$(CROSS_COMPILE_NS_USER)\
TA_CROSS_COMPILE=$(CROSS_COMPILE_S_USER) \
TA_DEV_KIT_DIR=$(OPTEE_OS_TA_DEV_KIT_DIR) \
TEEC_EXPORT=$(OPTEE_CLIENT_EXPORT)
.PHONY: optee_my_test-common
optee_my_test-common: optee-os optee-client
$(MAKE) -C $(OPTEE_MYTEST_PATH) $(OPTEE_MYTEST_COMMON_FLAGS)
OPTEE_MYTEST_CLEAN_COMMON_FLAGS ?= TA_DEV_KIT_DIR=$(OPTEE_OS_TA_DEV_KIT_DIR
.PHONY: optee_my_test-clean-common
optee_my_test-clean-common:
$(MAKE) -C $(OPTEE_MYTEST_PATH) $(OPTEE_MYTEST_CLEAN_COMMON_FLAGS) clean

#add to filelist-tee-common target
filelist-tee-common: optee-client xtest optee-examples optee_my_test

#add to clean target
optee-os-clean-common: xtest-clean optee-examples-clean optee_my_test-clean

#add to filelist-tee-commom
@echo "#optee_mytest " >> $(fl)
@if [ -e $(OPTEE_MYTEST_PATH)/host/my_test ]; then \
        echo "file /bin/my_test" \
       "$(OPTEE_MYTEST_PATH)/host/my_test 755 0 0" >> $(fl); \
        echo "file /lib/optee_armtz/uuid.ta" \
        "$(OPTEE_MYTEST_PATH)/ta/uuid.ta 444 0 0 " >> $(fl); \ 
fi
```
**4. by the way：in my $(root) file , I dont have `busybox`  and `gen_roots` dir.**

**5. here is the build answer. I find ca/ta has been build. However the last setp(`#add to filelist-tee-commom`): apply to system not carried out**　

```shell
#my ca build out name is dacao_aes;my ta build out name is 06cdfe9b-6cda-46a7-b599-#d3b0b1877f71.ta
make -C /home/dacao/exercise/optee_v8/build/../dacao_aes HOST_CROSS_COMPILE="/usr/bin/ccache /home/dacao/exercise/optee_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" TA_CROSS_COMPILE="/usr/bin/ccache /home/dacao/exercise/optee_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" TA_DEV_KIT_DIR=/home/dacao/exercise/optee_v8/build/../optee_os/out/arm/export-ta_arm64 TEEC_EXPORT=/home/dacao/exercise/optee_v8/build/../optee_client/out/export
make[1]: 进入目录“/home/dacao/exercise/optee_v8/dacao_aes”
make -C host CROSS_COMPILE="/usr/bin/ccache /home/dacao/exercise/optee_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" --no-builtin-variables
make[2]: 进入目录“/home/dacao/exercise/optee_v8/dacao_aes/host”
/usr/bin/ccache /home/dacao/exercise/optee_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc -Wall -I../ta/include -I./include -I/home/dacao/exercise/optee_v8/build/../optee_client/out/export/include -c main.c -o main.o
/usr/bin/ccache /home/dacao/exercise/optee_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc -o dacao_aes main.o -lteec -L/home/dacao/exercise/optee_v8/build/../optee_client/out/export/lib
make[2]: 离开目录“/home/dacao/exercise/optee_v8/dacao_aes/host”
make -C ta CROSS_COMPILE="/usr/bin/ccache /home/dacao/exercise/optee_v8/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" LDFLAGS=""
make[2]: 进入目录“/home/dacao/exercise/optee_v8/dacao_aes/ta”
  CC      dacao_aes_ta.o
  CC      user_ta_header.o
  CPP     ta.lds
  LD      06cdfe9b-6cda-46a7-b599-d3b0b1877f71.elf
  OBJDUMP 06cdfe9b-6cda-46a7-b599-d3b0b1877f71.dmp
  OBJCOPY 06cdfe9b-6cda-46a7-b599-d3b0b1877f71.stripped.elf
  SIGN    06cdfe9b-6cda-46a7-b599-d3b0b1877f71.ta
make[2]: 离开目录“/home/dacao/exercise/optee_v8/dacao_aes/ta”
make[1]: 离开目录“/home/dacao/exercise/optee_v8/dacao_aes”
make run-only

```

**Comment by da1234cao** [comment]
Environment: qemu_v8 3.3.0

**The error result by not carrieding out `update_rootfs-common` target.**

Because, I dont have  `busybox` and `gen_roots` dir.
I cant make the `update_rootfs-common` target.

In my `manifest.xml` and `project.list`。There is no  `busybox` and `gen_roots`.

Thus I dont how to result this question.

**Comment by jbech-linaro** [comment]
> In my `manifest.xml` and `project.list`。There is no `busybox` and `gen_roots`.

We got rid of busy_box and gen_rootfs quite some time ago (and started using buildroot instead). Can't remember the exact version, but by looking at git log in manifest.git you should be able to figure it out.

**Comment by da1234cao** [comment]
> We got rid of busy_box and gen_rootfs quite some time ago (and started using buildroot instead).

So, target `buildroot` can apply myself ta/ca into system?
Is there other way run self ta/ca in the  system?
I will read `buildroot` target  later.

**Comment by da1234cao** [comment]
Maybe this is the time:got rid of busy_box and gen_rootfs 
[qemu: build using buildroot](https://github.com/OP-TEE/manifest/commit/07ac85cd9043856a3f09af98c4b60b652f32efbe)

Meanwhile, In optee 3.3.0 , it has used buildroot. [manifest 3.3.0](https://github.com/OP-TEE/manifest/releases/tag/3.3.0)

**Comment by da1234cao** [comment]
oh,I am sorry . I look at target error.
`filelist-tee-common` target is uesd to apply self ca/ta into system, rather then  `update_rootfs-common` target.

**Comment by da1234cao** [comment]
I will try later.

**Comment by da1234cao** [comment]
I have no relevant development experience.
Here  is the way how I feel could add ca/ta into system.
I hava add ca/ta into system now , but the way may not be good.

* Add proper package into `build/br-ext/package` and modify common.mk
* Use existed package ,for eample `build/br-ext/package/optee_examples` .  Put the ca/ta dir into `optee_example` 。However, the ca commond name must start by `optee_example`
* cp the  ca/ta  which has been built into the proper of site of `out-br` ,directly.

**Comment by da1234cao** [comment]
Thanks for your commont. If no thing is additon temporarily. I will close the issue,later.
