### ISSUE TITLE
xtest regression_1018 failing with CFG_CORE_DYN_SHM=n

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_test#410]
Test-case added via [commit](https://github.com/OP-TEE/optee_test/commit/84382b31d3a3758fcd52f2751bb52ed4138a4281) fails with `CFG_CORE_DYN_SHM=n`.

The reason seems to be allocation from dma_buf shared memory to be page aligned (see [PAGE_SHIFT](https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/core.c#L504) as min_alloc_order). This leads to actual allocation of 8192 bytes instead of expected 6001 bytes leading to out of bounds issue being undetected.

So I would like to hear views about how to fix it? Maybe set `min_alloc_order=1 byte`?

**Comment by jenswi-linaro** [comment]
There's two problems here.
The test depends on a certain implementation to get the `TEEC_ORIGIN_COMMS` error origin, this error doesn't have to be caught at this level.

When we're using the reserved memory pool instead we're hitting this code path in Client API:
https://github.com/OP-TEE/optee_client/blob/abc05e61872a9ae2cd08c885c7b523df5ba1a26b/libteec/src/tee_client_api.c#L274-L281

There's a check missing that we're not out of bounds, if there would be such a check the error origin should be `TEEC_ORIGIN_API`.

So the test need to be updated to accept `TEEC_ORIGIN_API` as a valid error origin and Client API need to be update with the missing check.

**Comment by etienne-lms** [comment]
Agree regarding the error origin. I think the test should only ensure the origin is _not_ the TA itself, whatever it being the API, the comms or the TEE.

**Comment by b49020** [comment]
@jenswi-linaro 

> When we're using the reserved memory pool instead we're hitting this code path in Client API:

Its true when we use `TEEC_RegisterSharedMemory` but not hit when we use `TEEC_AllocateSharedMemory` with reserved memory pool.

So in general, I agree with the check for out of bounds in `optee-client` but I think it should be common check [here](https://github.com/OP-TEE/optee_client/blob/abc05e61872a9ae2cd08c885c7b523df5ba1a26b/libteec/src/tee_client_api.c#L273).

**Comment by jenswi-linaro** [comment]
Yeah, and here too: https://github.com/OP-TEE/optee_client/blob/abc05e61872a9ae2cd08c885c7b523df5ba1a26b/libteec/src/tee_client_api.c#L232

**Comment by b49020** [comment]
BTW, do we need to add a CI test for `CFG_CORE_DYN_SHM=n`? Maybe QEMU with `CFG_CORE_DYN_SHM=n` and hikey with `CFG_CORE_DYN_SHM=y`? So that in future we can avoid corresponding xtest failures?

**Comment by etienne-lms** [comment]
There are so many configuration switches that we will hardly test all of them with CI :(
CFG_CORE_RESERVED_SHM, CFG_CORE_DYN_SHM, CFG_TA_DYNLINK, CFG_ULIBS_SHARED, CFG_VIRTUALIZATION, CFG_WITH_PAGER, CFG_WITH_VFP, CFG_WITH_LPAE ...

**Comment by jenswi-linaro** [comment]
Actually, we could if we really wanted to. But it's more than just an afternoons work.

**Comment by etienne-lms** [comment]
For info, test passes with these 2 changes:
```patch
--- a/libteec/src/tee_client_api.c
+++ b/libteec/src/tee_client_api.c
@@ -271,6 +272,9 @@ static TEEC_Result teec_pre_process_partial(uint32_t param_type,
 	if ((shm->flags & req_shm_flags) != req_shm_flags)
 		return TEEC_ERROR_BAD_PARAMETERS;
 
+	if (memref->offset + memref->size > shm->size)
+		return TEEC_ERROR_BAD_PARAMETERS;
+
 	/*
 	 * We're using a shadow buffer in this reference, copy the real buffer
 	 * into the shadow buffer if needed. We'll copy it back once we've
```
```patch
--- a/host/xtest/regression_1000.c
+++ b/host/xtest/regression_1000.c
@@ -1388,7 +1388,7 @@ static void invoke_1byte_out_of_bounds(ADBG_Case_t *c, TEEC_Session *session,
 	ret = TEEC_InvokeCommand(session, TA_OS_TEST_CMD_PARAMS,
 				 &op, &ret_orig);
 
-	ADBG_EXPECT(c, TEEC_ORIGIN_COMMS, ret_orig);
+	ADBG_EXPECT_COMPARE_UNSIGNED(c, ret_orig, !=, TEEC_ORIGIN_TRUSTED_APP);
 	if (ret != TEEC_ERROR_BAD_PARAMETERS && ret != TEEC_ERROR_GENERIC) {
 		ADBG_EXPECT(c, TEEC_ERROR_BAD_PARAMETERS, ret);
 		ADBG_EXPECT(c, TEEC_ERROR_GENERIC, ret);
@@ -1451,7 +1451,7 @@ static void xtest_tee_test_1018(ADBG_Case_t *c)
 	ret = TEEC_InvokeCommand(&session, TA_OS_TEST_CMD_PARAMS, &op,
 				 &ret_orig);
 
-	ADBG_EXPECT(c, TEEC_ORIGIN_COMMS, ret_orig);
+	ADBG_EXPECT_COMPARE_UNSIGNED(c, ret_orig, !=, TEEC_ORIGIN_TRUSTED_APP);
 	if (ret != TEEC_ERROR_BAD_PARAMETERS && ret != TEEC_ERROR_GENERIC) {
 		ADBG_EXPECT(c, TEEC_ERROR_BAD_PARAMETERS, ret);
 		ADBG_EXPECT(c, TEEC_ERROR_GENERIC, ret);
```
Yet, that does not mean current test coverage if sufficient.

I don't think it is needed in optee_client `teec_pre_process_whole()` (suggested by https://github.com/OP-TEE/optee_test/issues/410#issuecomment-610903085) since the _memref_whole_ case does not care about the offset/size fields of the shm.

**Comment by etienne-lms** [comment]
> Actually, we could if we really wanted to. But it's more than just an afternoons work.

If I remember well Shippable/Travis have constraints on duration of the tests and I think we currently can't test many setups for each P-R update.

**Comment by b49020** [comment]
> > Actually, we could if we really wanted to. But it's more than just an afternoons work.
> 
> If I remember well Shippable/Travis have constraints on duration of the tests and I think we currently can't test many setups for each P-R update.

I didn't meant to increase duration of tests. IIRC, CI setup tests on two platforms (QEMU, hikey). I just suggested to use this test setup only more efficiently i.e. QEMU with `CFG_CORE_DYN_SHM=n` and hikey with `CFG_CORE_DYN_SHM=y`. As I also think these are platform specific configurations which we could test.

**Comment by jforissier** [comment]
> > Actually, we could if we really wanted to. But it's more than just an afternoons work.

True!

> If I remember well Shippable/Travis have constraints on duration of the tests and I think we currently can't test many setups for each P-R update.

True! :)

For completeness: Shippable performs the build tests, Travis just runs `checkpatch` and `pycodestyle`, while IBART is responsible for running `xtest` on HiKey and QEMU.

**Comment by jforissier** [comment]
@b49020 
> [...] QEMU with CFG_CORE_DYN_SHM=n [...]

Not a bad idea IMO.

**Comment by b49020** [comment]
@etienne-lms 

> For info, test passes with these 2 changes:

Could you create PR for these changes?

**Comment by etienne-lms** [comment]
OK

**Comment by etienne-lms** [comment]
https://github.com/OP-TEE/optee_client/pull/203 & https://github.com/OP-TEE/optee_test/pull/411
