### ISSUE TITLE
Regression_1025 may fail if TEE_GEN_CAP_MEMREF_NULL is not supported

### ISSUE THREAD

**Issue by mhiramat** [OP-TEE/optee_test#415]
Hello,

I'm helping Socionext engineers to upstream OP-TEE for Akebi96 96board.

Since the current OP-TEE implementation doesn't set the shared-memory virtual address in utee_params if mem.size is 0 (in [tee_mmu_map_param()@core/arch/arm/mm/tee_mmu.c](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/tee_mmu.c#L877)), user TA will always see params[n].memref.buffer == NULL buffer when params[n].memref.size == 0. (Otherwise memref.buffer != NULL if memref.size != 0)

With the recent commit [9d2e798360b5b8dd2f5032cc020bb2bb6f7c3f06](https://github.com/OP-TEE/optee_os/commit/9d2e798360b5b8dd2f5032cc020bb2bb6f7c3f06) on optee_os changes above behavior, it checks mem.mobj is set instead of mem.size. But anyway, since the user-space libteec allocates shared memory for all parameters whether tmpref.buffer is set or not (*), in this case the memref.buffer always !NULL regerdless the memref.size.

Thus, in both case, in [ta_entry_null_memref()@optee_test/ta/os_test/os_test.c](https://github.com/OP-TEE/optee_test/blob/master/ta/os_test/os_test.c#L1071)
```
        if (!params[0].memref.buffer || params[0].memref.size ||
            params[1].memref.buffer || params[1].memref.size ||
            !params[2].memref.buffer || params[2].memref.size ||
            params[3].memref.buffer || params[3].memref.size) {
```

This check always fails.
Maybe we should skip this test it if the OPTEE driver doesn't support TEE_GEN_CAP_MEMREF_NULL feature yet.

BTW, this does NOT mean current OPTEE doesn't follow the TEE Client API specification v1.0c, because it only requires that the implementation must support memref.buffer == NULL case (null Memory Reference for variable length buffer). But it does NOT require the implementation must pass the mapped buffer address even if size == 0.

(*) Even if the user-space application (like xtest) sets NULL to tmpref.buffer with tmpref.size = 0, [teec_pre_process_tmpref()@optee_client/libteec/src/tee_client_api.c](https://github.com/OP-TEE/optee_client/blob/master/libteec/src/tee_client_api.c#L169) always allocates a buffer on shared memory if !ctx->memref_null. And since Linux OPTEE driver doesn't support TEE_GEN_CAP_MEMREF_NULL, ctx->memref_null always be cleared on Linux.

This means the OPTEE has no way to distinguish whether the memref parameter is originally NULL or set because the client library always set a shared memory on invoke function parameter. (It can only distinguish the size parameter differences)

**Comment by etienne-lms** [comment]
Do you mean using latest optee_os/optee_client/optee_test with MEMREF_NULL support and mainline Linux kernel that does not support MEMREF_NULL, then xtest 1025 fails?

**Comment by mhiramat** [comment]
Yes, since the optee_client/libteec checks MEMREF_NULL support via IOC_GET_VERSION and that ioctl implementation in the Linux OPTEE driver doesn't check the capability of OPTEE (see optee_get_version() in drivers/tee/optee/core.c, get_caps only sets TEE_GEN_CAP_GP and TEE_GEN_CAP_REG_MEM.)

Actually, I'm not so sure how 1025 can pass the test without MEMREF_NULL support...
We don't touch the optee_os itself except for the platform driver, but only this #1025 test case doesn't pass. So I traced it and found this doesn't depend on the platform part.

**Comment by etienne-lms** [comment]
Our apologies, indeed this looks a regression to me in the xtest suite.
I think we could fix it. the `TEEC_Context` returned to client application from `TEEC_InitializeContext()` tells whether MEMREF_NULL is supported from boolean field `memref_null`. If Linux OP-TEE driver does not support the feature, this boolean should be `false`. Xtest regression 1025 could test it to run or not the NULL MEMREF tests.
I'll give a try and propose a P-R.

**Comment by etienne-lms** [comment]
Please see https://github.com/OP-TEE/optee_test/pull/416.

**Comment by mhiramat** [comment]
Thank you! I confirmed the test 1025 is correctly skipped with you patch.

```
# xtest 1025
Test ID: 1025
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################
 
* regression_1025 Test memref NULL and/or 0 bytes size
Skip test: MEMREF_NULL capability not supported
  regression_1025 OK
+-----------------------------------------------------
Result of testsuite regression filtered by "1025":
regression_1025 OK
+-----------------------------------------------------
0 subtests of which 0 failed
1 test case of which 0 failed
98 test cases were skipped
TEE test application done!
```
