### ISSUE TITLE
Don't use C reserved symbols

### ISSUE THREAD

**Issue by rossburton** [OP-TEE/optee_test#453]
Quoting from the C specification (emphasis mine)

> In addition to the names documented in this manual, reserved names include all external identifiers (global functions and variables) that begin with an underscore (‘_’) and **all identifiers regardless of use that begin with either two underscores** or an underscore followed by a capital letter are reserved names. This is so that the library and header files can define functions, variables, and macros for internal purposes without risk of conflict with names in user programs.

All uses of `__unused` in optee-test should be replaced with another variable name.  This is not a hypothetical problem, `__unused` is used by musl and as such we can't build optee-test with musl.

**Comment by jforissier** [comment]
Would https://github.com/OP-TEE/optee_test/pull/454 be a proper fix?

**Comment by rossburton** [comment]
Looks right to me.

**Comment by etienne-lms** [comment]
@jforissier, do you think we'll face sooner or later the same issue in trusted applications source code?

**Comment by jforissier** [comment]
> @jforissier, do you think we'll face sooner or later the same issue in trusted applications source code?

No, because as I wrote in the commit message the C library is provided by OP-TEE.
