### ISSUE TITLE
Xtest stuck in regression Test 1004

### ISSUE THREAD

**Issue by Bharat-FSL** [OP-TEE/optee_test#459]
Hi All,

I am working on adding optee support for one of Marvell platform.  For testing same I am using standalone compilation of xtest using https://github.com/jbech-linaro/optee_standalone (switched to latest optee_client,  optee_os,  optee_test) 

Optee Bootlog is:
TC:00    get_aslr_seed:1374 Warning: no ASLR seed                                                                                                         
D/TC:00    add_phys_mem:558 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x7fb000000 size 0x000a4000                                                                     
D/TC:00    add_phys_mem:558 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x7fb0a4000 size 0x0015c000                                                                     
D/TC:00    add_phys_mem:558 TA_RAM_START type TA_RAM 0x7fb200000 size 0x00e00000                                                                             
D/TC:00    add_phys_mem:558 TEE_SHMEM_START type NSEC_SHM 0x01000000 size 0x00400000                                                                         
D/TC:00    add_phys_mem:558 ROUNDDOWN(0x87E028000000ll, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x87e028000000 size 0x00200000                                      
D/TC:00    add_va_space:597 type RES_VASPACE size 0x00a00000                                                                                                 
D/TC:00    add_va_space:597 type SHM_VASPACE size 0x02000000                                                                                                 
D/TC:00    dump_mmap_table:709 type IO_SEC       va 0x7f6c00000..0x7f6dfffff pa 0x87e028000000..0x87e0281fffff size 0x00200000 (pgdir)                       
D/TC:00    dump_mmap_table:709 type TA_RAM       va 0x7f6e00000..0x7f7bfffff pa 0x7fb200000..0x7fbffffff size 0x00e00000 (pgdir)                             
D/TC:00    dump_mmap_table:709 type NSEC_SHM     va 0x7f7e00000..0x7f81fffff pa 0x01000000..0x013fffff size 0x00400000 (pgdir)                               
D/TC:00    dump_mmap_table:709 type SHM_VASPACE  va 0x7f8200000..0x7fa1fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)                               
D/TC:00    dump_mmap_table:709 type RES_VASPACE  va 0x7fa400000..0x7fadfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)                               
D/TC:00    dump_mmap_table:709 type TEE_RAM_RX   va 0x7fb000000..0x7fb0a3fff pa 0x7fb000000..0x7fb0a3fff size 0x000a4000 (smallpg)                           
D/TC:00    dump_mmap_table:709 type TEE_RAM_RW   va 0x7fb0a4000..0x7fb1fffff pa 0x7fb0a4000..0x7fb1fffff size 0x0015c000 (smallpg)                           
D/TC:00    core_mmu_entry_to_finer_grained:751 xlat tables used 1 / 8                                                                                        
D/TC:00    core_mmu_entry_to_finer_grained:751 xlat tables used 2 / 8                                                                                        
I/TC:                                                                                                                                                        
I/TC: OP-TEE version: 3.11.0-35-gd9277feb-dev (gcc version 7.3.0 (Marvell Inc. Version: Marvell GCC7 build 249.0)) #19 Tue Nov  3 04:09:23 UTC 2020 aarch64  
I/TC: Primary CPU initializing                                                                                                                               
D/TC:00 00 paged_init_primary:1232 Executing at offset 0 with virtual load address 0x7fb000000                                                               
D/TC:00 00 call_initcalls:21 level 1 register_time_source()                                                                                                  
D/TC:00 00 call_initcalls:21 level 1 teecore_init_pub_ram()                                                                                                  
D/TC:00 00 call_initcalls:21 level 3 init_user_ta()                                                                                                          
D/TC:00 00 call_initcalls:21 level 3 check_ta_store()                                                                                                        
D/TC:00 00 check_ta_store:651 TA store: "Secure Storage TA"                                                                                                  
D/TC:00 00 check_ta_store:651 TA store: "REE"                                                                                                                
D/TC:00 00 call_initcalls:21 level 3 verify_pseudo_tas_conformance()                                                                                         
D/TC:00 00 call_initcalls:21 level 3 mobj_mapped_shm_init()                                                                                                  
D/TC:00 00 mobj_mapped_shm_init:434 Shared memory address range: 7f8200000, 7fa200000                                                                        
D/TC:00 00 call_initcalls:21 level 3 tee_cryp_init()                                                                                                         
D/TC:00 00 call_initcalls:21 level 4 tee_fs_init_key_manager()                                                                                               
D/TC:00 00 call_initcalls:21 level 6 mobj_init()                                                                                                             
D/TC:00 00 call_initcalls:21 level 6 default_mobj_init()                                                                                                     
I/TC: Primary CPU switching to normal world boot       

Xtest log:
---------
Test 1001, 1002 and 1003 pass while it is stuck in test 1004 (control-c" returns back)

* regression_1004 Test User Crypt TA                                                                                                                         
D/TC:?? 00 tee_ta_init_pseudo_ta_session:298 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b                                                           
D/TC:?? 00 load_ldelf:719 ldelf load address 0x40006000                                                                                                      
D/LD:   ldelf:134 Loading TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b                                                                                            
D/TC:?? 00 tee_ta_init_pseudo_ta_session:298 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc                                                           
D/TC:?? 00 tee_ta_init_pseudo_ta_session:311 Open system.pta                                                                                                 
D/TC:?? 00 tee_ta_init_pseudo_ta_session:328 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc                                                               
D/TC:?? 00 system_open_ta_binary:257 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)

==== on pressing CTRL-C:

D/TC:?? 00 system_open_ta_binary:260 res=0xffff000c                                                                                                        
D/TC:?? 00 tee_ta_invoke_command:801 Error: ffff000c of 4                                                                                                    
E/LD:   init_elf:438 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)                                                                                   
E/TC:?? 00 init_with_ldelf:257 ldelf failed with res: 0xffff000c                                                                                             
D/TC:?? 00 tee_ta_close_session:497 csess 0x7fb0da3c0 id 1                                                                                                   
D/TC:?? 00 tee_ta_close_session:515 Destroy session                                                                                                          
D/TC:?? 00 tee_ta_open_session:699 init session failed 0xffff000c  

Looking for some help.

Thanks
-Bharat

**Comment by etienne-lms** [comment]
Hi Bharat,
Check if **tee-supplicant** is running before you start **xtest**.

**Comment by jbech-linaro** [comment]
> I am working on adding optee support for one of Marvell platform. For testing same I am using standalone compilation of xtest using https://github.com/jbech-linaro/optee_standalone (switched to latest optee_client, optee_os, optee_test)

Just want to emphasize what I wrote in the README, that the work I did there isn't meant to replace existing build. Likewise it's nothing that I've tried to update and support. However, after giving a quick check I believe what I did back then still should work and your issue is run time issues and not compiler issues. I'd do this:

1) Run a debugger on OP-TEE core to see why it hangs. Since it's not loading any TA or get stuck on a TA, it could be the communication with the non-secure side that fails.
``` 
D/TC:?? 00 system_open_ta_binary:257 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
```
2) Try to make a build based on the official setup ([port to another platform]).(https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-port-op-tee-to-another-platform).
3) When you know that is working, you could eventually strip down things and go with a "standalone" setup similar to what I did.

**Comment by Bharat-FSL** [comment]
> Hi Bharat,
> Check if **tee-supplicant** is running before you start **xtest**.

tee-supplicant was not running. Now when running tee-supplicant it does not stuck there.

While the test report says:
    869 subtests of which 432 failed                                                                                                                             
    91 test cases of which 83 failed                                                                                                                             
    0 test cases were skipped                                                                                                                                    
    TEE test application done!  

I will look into why failing and comeback.

Thank you very much
-Bharat

**Comment by Bharat-FSL** [comment]
> > I am working on adding optee support for one of Marvell platform. For testing same I am using standalone compilation of xtest using https://github.com/jbech-linaro/optee_standalone (switched to latest optee_client, optee_os, optee_test)
> 
> Just want to emphasize what I wrote in the README, that the work I did there isn't meant to replace existing build. Likewise it's nothing that I've tried to update and support. However, after giving a quick check I believe what I did back then still should work and your issue is run time issues and not compiler issues. I'd do this:
> 
> 1. Run a debugger on OP-TEE core to see why it hangs. Since it's not loading any TA or get stuck on a TA, it could be the communication with the non-secure side that fails.
> 
> ```
> D/TC:?? 00 system_open_ta_binary:257 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
> ```
> 
> 1. Try to make a build based on the official setup ([port to another platform]).(https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-port-op-tee-to-another-platform).
> 2. When you know that is working, you could eventually strip down things and go with a "standalone" setup similar to what I did.

Sure I will try to build using official build mechanism for a new platform

**Comment by Bharat-FSL** [comment]
Here is the test log for 1004 after running tee-supplicant:

* regression_1004 Test User Crypt TA                                                                                                                         
D/TC:?? 00 tee_ta_init_pseudo_ta_session:298 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b                                                           
D/TC:?? 00 load_ldelf:719 ldelf load address 0x40006000                                                                                                      
D/LD:   ldelf:134 Loading TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b                                                                                            
D/TC:?? 00 tee_ta_init_session_with_context:590 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc                                                              
D/TC:?? 00 system_open_ta_binary:257 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)                                             
D/TC:?? 00 system_open_ta_binary:260 res=0xffff0008                                                                                                          
D/TC:?? 00 system_open_ta_binary:257 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (REE)                                                           
_**ERR [2846] TEES:load_ta:284:   TA not found**_                                                                                                                  
D/TC:?? 00 system_open_ta_binary:260 res=0xffff0008                                                                                                          
D/TC:?? 00 tee_ta_invoke_command:801 Error: ffff0008 of 4                                                                                                    
E/LD:   init_elf:438 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)                                                                                   
E/TC:?? 00 init_with_ldelf:257 ldelf failed with res: 0xffff0008                                                                                             
D/TC:?? 00 tee_ta_close_session:497 csess 0x7fb0d9a60 id 1                                                                                                   
D/TC:?? 00 tee_ta_close_session:515 Destroy session                                                                                                          
D/TC:?? 00 tee_ta_open_session:699 init session failed 0xffff0008                                                                                            
/home/bharat/upstream/OPTEE/optee_standalone/optee_test/host/xtest/regression_1000.c:435: xtest_teec_open_session( &session, &crypt_user_ta_uuid, ((void *)0S
  regression_1004 FAILED                


Error is TA now found, seems like some issue in loading TA, I will debug this first.

Any quick hint on what I should look at will be helpful.

Thanks
-Bharat

**Comment by jforissier** [comment]
@Bharat-FSL check that your TA (the `*.ta` file) is in `/lib/optee_armtz`. The `/lib`part is `CFG_TEE_CLIENT_LOAD_PATH` ([here](https://github.com/OP-TEE/optee_client/blob/3.11.0/config.mk#L34)) and `optee_armtz` is hardcoded [here](https://github.com/OP-TEE/optee_client/blob/3.11.0/tee-supplicant/src/tee_supplicant.c#L445).

**Comment by Bharat-FSL** [comment]
> @Bharat-FSL check that your TA (the `*.ta` file) is in `/lib/optee_armtz`. The `/lib`part is `CFG_TEE_CLIENT_LOAD_PATH` ([here](https://github.com/OP-TEE/optee_client/blob/3.11.0/config.mk#L34)) and `optee_armtz` is hardcoded [here](https://github.com/OP-TEE/optee_client/blob/3.11.0/tee-supplicant/src/tee_supplicant.c#L445).

After putting TA at /lib/optee_armtz/ TAs are loading. Here is the final test result. 6 tests are still failing out of 91.
I will dig into this now.

23268 subtests of which 11 failed                                                                                                                            
91 test cases of which 6 failed                                                                                                                              
0 test cases were skipped                                                                                                                                    
TEE test application done! 

Thank you very much 
-Bharat
