### ISSUE TITLE
xtest 1033 fails due to file permission issues

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_test#494]
QEMU, `xtest` run while logged in as user `test`:
```
o regression_1033.2 Pass array to a plugin
regression_1000.c:2420: fp has an unexpected value: (nil), expected not NULL
  regression_1033.2 FAILED
```
The same test passes when logged in as `root`. The problem is, `xtest` tries to open, read and delete a file created by `tee-supplicant` and permissions do not allow this.

**Comment by jforissier** [comment]
@anisyanka why use a file? Could a simple request/response mechanism to tee-supplicant be used instead?

**Comment by jforissier** [comment]
@jbech-linaro shouldn't IBART use the `test` user rather than `root` to run `xtest`?

**Comment by jbech-linaro** [comment]
> @jbech-linaro shouldn't IBART use the `test` user rather than `root` to run `xtest`?

Can't argue against that comment. But what I'm doing in IBART is what we tell users to do in the docs. If we want to run as `test` by default, then I think we should update build-scripts, docs etc accordingly. But, as indicated, running as `test` sounds like sane approach.

**Comment by anisyanka** [comment]
> @anisyanka why use a file? Could a simple request/response mechanism to tee-supplicant be used instead?

Yes, we can use request/response to test the ability to pass arrays to a plugin. Therefore we can drop the logic with a file.
Or we can just change permissions for a temp file. It's created with 0600 with the help of `mkstemp()`.
What if I will add `chmod(file, 0644)` after creating the file?

**Comment by jforissier** [comment]
I'd rather remove the file logic entirely, it is more complex than needed and subject to unrelated failures.

**Comment by anisyanka** [comment]
> I'd rather remove the file logic entirely, it is more complex than needed and subject to unrelated failures.

OK, I will prepare PR today
