### ISSUE TITLE
when buildroot loading version 3.11.0 compilation error showed because of TEE_ATTR_FLAG_VALUE not defined

### ISSUE THREAD

**Issue by coldcl** [OP-TEE/optee_test#495]

**Comment by etienne-lms** [comment]
Are you building from a buildroot repo?
```bash
git clone http://git.buildroot.net/buildroot
cd buildroot && make xxxxxx_defconfig && make
```
or from an OP-TEE manifest?
```bash
repo init -u https://github.com/OP-TEE/manifest.git -m xxxxx.xml -b 3.11.0 && repo sync
cd build && make toolchains && make
```

**Comment by etienne-lms** [comment]
Also to mention: if you are using opteee_os 3.11.0, please use optee_test 3.11.0.
Kernel versions related the 3.11.0 or above are fine.
Same for optee_client, can be 3.11.0 or above. Maybe 3.11.0 would be preferred, I think, but it should not, no?
