### ISSUE TITLE
undefined references in ta_entry

### ISSUE THREAD

**Issue by tpimh** [OP-TEE/optee_test#499]
I'm building 3.10.0.imx as a part of yocto build for an iMX6 board. Getting the following errors which is strange as it looks like those symbols were defined:

    | arm-poky-linux-gnueabi-ld.bfd: /tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/optee-test/3.10.0.imx-r0/build/ta/os_test/ta_entry.o: in function `TA_InvokeCommandEntryPoint':
    | /usr/src/debug/optee-test/3.10.0.imx-r0/git/ta/os_test/ta_entry.c:133: undefined reference to `ta_entry_cxx_ctor_main'
    | arm-poky-linux-gnueabi-ld.bfd: /usr/src/debug/optee-test/3.10.0.imx-r0/git/ta/os_test/ta_entry.c:136: undefined reference to `ta_entry_cxx_ctor_shlib'
    | arm-poky-linux-gnueabi-ld.bfd: /usr/src/debug/optee-test/3.10.0.imx-r0/git/ta/os_test/ta_entry.c:139: undefined reference to `ta_entry_cxx_ctor_shlib_dl'
    | arm-poky-linux-gnueabi-ld.bfd: /usr/src/debug/optee-test/3.10.0.imx-r0/git/ta/os_test/ta_entry.c:142: undefined reference to `ta_entry_cxx_exc_main'
    | arm-poky-linux-gnueabi-ld.bfd: /usr/src/debug/optee-test/3.10.0.imx-r0/git/ta/os_test/ta_entry.c:145: undefined reference to `ta_entry_cxx_exc_mixed'

Anyone else getting the same error?

**Comment by jforissier** [comment]
Hi @tpimh ,

Something must have gone wrong with conditional compilation. These symbols are related to C++ support and tests are enabled for some toolchains and not others, this was a bit buggy in the past. See in particular https://github.com/OP-TEE/optee_test/commit/5c20a5b which enables those tests only in "our" build environment (https://github.com/OP-TEE/build/) where we know the toolchain is supported. Perhaps you can apply this patch.

**Comment by tpimh** [comment]
Thank you very much! Currently, I just removed `os_test` from the list of targets, so it's not being built. I will try applying your patch instead.

**Comment by tpimh** [comment]
The issue was resolved with the patch above, thank you!
