### ISSUE TITLE
static libcrypto.a for Cortex-A9 built without -fPIC

### ISSUE THREAD

**Issue by wamserma** [OP-TEE/optee_test#507]
The precompiled `libcrypto.a` provided for Cortex-A9 (see here https://github.com/OP-TEE/optee_test/commit/13d805a0bd3f1051e3c6cc48bca4c3a8248ad5f6) is built without PIC support.
Hence, xtest fails to link when hardening is used in Project-Wide build flags.
An exemplary linker error taken from the build log is:
```
ld: ../openssl/lib/arm/libcrypto.a(bio_asn1.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
```

Proposed solution: 
- rebuild with

   ```
    git clone https://github.com/openssl/openssl.git
    cd openssl
    git checkout OpenSSL_1_0_2o
    ./Configure linux-generic32 -mcpu=cortex-a9 no-shared \
                --cross-compile-prefix=arm-linux-gnueabihf- \
               -fPIC
    make build_libcrypto
   ```
- put the new binary in optee_test and have the commit message reflect the new build instructions.

Adding the `pic` flag to `./Configure` solved the linker issue for us (using release tag 3.12), but I cannot make a PR from that development network. (Note `./Configure` says the flag is `pic`/`no-pic` but we had to use `-fPIC`.)
@jforissier Could you kindly create the PR?

**Comment by Emantor** [comment]
FWIW for my BSP builds I don't use the precompiled openssl library and instead set `OPTEE_OPENSSL_EXPORT` to a directory which contains a cross-compiled openssl lib for my target architecture.

**Comment by wamserma** [comment]
@Emantor Sure, but having this work out-of-the box is nice, too. :)

**Comment by wamserma** [comment]
Closed by https://github.com/OP-TEE/optee_test/pull/508.
