### ISSUE TITLE
gp_40178 random failures

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_test#510]
```
# QEMUv8
$ make GP_PACKAGE=/path/to/TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z run
```
```
Welcome to Buildroot, type root or test to login
buildroot login: test
$ xtest gp_40178
Test ID: gp_40178
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression+gp+pkcs11
#
######################################################

* gp_40178 ce-7b-17
Segmentation fault
$
```

See also https://github.com/OP-TEE/optee_os/pull/4552#issuecomment-827563612.

**Comment by jforissier** [comment]
The problematic line in `xtest_tee_40178()`:
```C
    Test_Tool_Erase_Persistent_Time(c, SESSION01, CMD_TEE_SetTAPersistentTime_and_GetTAPersistentTime);
```
At this point, SESSION01 is not open.

In fact, the whole test is not applicable because OP-TEE provides no external tool to erase the persistent time of a TA.
Who knows how to exclude a test from the GP test suite? @jenswi-linaro @etienne-lms

**Comment by etienne-lms** [comment]
Thanks for the investigation. I agree we should disable this test.
