### ISSUE TITLE
`xtest` fails at the very beginning

### ISSUE THREAD

**Issue by aleksandarn-ee** [OP-TEE/optee_test#521]
We have the following setup deployed:
* OP-TEE OS **3.12.0**. Compiled with log level 3 and `CFG_UNWIND`.
* OPTEE test **3.12.0**.
* Linux Kernel is a bit older **4.4.41**.

However, starting `xtest` hangs **at the very beginning** with a weird debug output (below). I have googled a little bit and some similar issues points to a deadlock, however I am not sure. Any help is highly appreciated. (I didn't want to reformat the output, so it remains as printed out, I can though if necessary).

```
TEE test application started oveD/TC:? 1 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
r default TEE instance
########################D/TC:? 1 ldelf_load_ldelf:91 ldelf load address 0x104000
##############################
#
D/LD:  ldelf:134 Loading TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
 

#
############################################D/TC:? 1 ldelf_syscall_open_bin:140 Lookup user TA ELF d96a5b40-c3e5-21e3-8794-1002a5d5c61b (Secure Storage TA)
##########
 

* regression_1001 Core self testsD/TC:? 1 __wq_rpc:38 sleep thread 1 0x9003bfe8
```

**Comment by aleksandarn-ee** [comment]
A bit more info on the topic. Could those "warnings" be the reason for the problem?

```
# dmesg | grep "tee"
[    5.010686] optee firmware:optee: probing for conduit method from DT.
[    5.041381] optee firmware:optee: initialized driver
[   14.293793]  remoteproc0: THE BINARY FORMAT IS NOT YET FINALIZED, and backward compatibility isn't yet guaranteed.
[   14.890408]  remoteproc1: THE BINARY FORMAT IS NOT YET FINALIZED, and backward compatibility isn't yet guaranteed.
[   15.090390]  remoteproc2: THE BINARY FORMAT IS NOT YET FINALIZED, and backward compatibility isn't yet guaranteed.
```

**Comment by jenswi-linaro** [comment]
> * Linux Kernel is a bit older **4.4.41**.

No kidding, this is prehistoric! :-)
You've obviously cherry-picked patches from somewhere since there's no OP-TEE driver in that version, perhaps you missed some.

**Comment by aleksandarn-ee** [comment]
>No kidding, this is prehistoric! :-)
I know, but I am not the one deciding when to update :) 

Either way the kernel will be upgraded later this year and I hope our problems are gone with the upgrade. So I'll close this issue.
