### ISSUE TITLE
8102 and 8103 MbedTLS related test cases can't run successfully 

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_test#522]
https://github.com/OP-TEE/optee_test/blob/444e15178dce00b16de17bb289c5b7b4b63bc706/host/xtest/regression_8100.c#L49

Current 8102 and 8103 test cases both use myasprintf function, but this function seems have some issue.  Anyone verified these two test cases?

**Comment by jforissier** [comment]
What's the problem?
```
$ make -j10 run
...
Welcome to Buildroot, type root or test to login
buildroot login: test
$ xtest 8102
Test ID: 8102
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression
#
######################################################

* regression_8102 TA mbedTLS test cert chain
  regression_8102 OK
+-----------------------------------------------------
Result of testsuite regression filtered by "8102":
regression_8102 OK
+-----------------------------------------------------
4 subtests of which 0 failed
1 test case of which 0 failed
92 test cases were skipped
TEE test application done!
$ xtest 8103
Test ID: 8103
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression
#
######################################################

* regression_8103 TA mbedTLS process certificate request
  regression_8103 OK
+-----------------------------------------------------
Result of testsuite regression filtered by "8103":
regression_8103 OK
+-----------------------------------------------------
24 subtests of which 0 failed
1 test case of which 0 failed
92 test cases were skipped
TEE test application done!
```

**Comment by jingdlu** [comment]
Thanks for your reply.

Let's take 8103 as an example. The test code invokes myasprintf to generate csr, but the current myasprintf function will mess up the content in  csr buffer. It will cause the following TEEC_InvokeCommand returning TEEC_ERROR_BAD_FORMAT.

After I put va_start and va_end before and afeter every vsnprintf in myasprintf function, the csr buffer content is correct.

Since you said current 8103 is running well, is it caused by different version libc function?

Thanks,
Jingdong

**Comment by jforissier** [comment]
> Thanks for your reply.
> 
> Let's take 8103 as an example. The test code invokes myasprintf to generate csr, but the current myasprintf function will mess up the content in csr buffer. It will cause the following TEEC_InvokeCommand returning TEEC_ERROR_BAD_FORMAT.
> 
> After I put va_start and va_end before and afeter every vsnprintf in myasprintf function, the csr buffer content is correct.

Got it. You are right, the value of `va_list ap` is undefined after a call to `vsnprintf(char *str, size_t size, const char *format, va_list ap);`.

> Since you said current 8103 is running well, is it caused by different version libc function?

Probably, yes.
Would you like to submit a PR to fix this bug?
Thanks.

> Thanks,
> Jingdong

**Comment by jingdlu** [comment]
Submit a PR as below:
https://github.com/OP-TEE/optee_test/pull/523

Thanks,
Jingdong
