### ISSUE TITLE
uuid parsing issue while compiling a TA(already part of optee-test) with different uuid value

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_test#539]
I modified the uuid of a particular TA that is already part of the optee test code base.
Later, tried to compile and faced the below issue:

> usage: sign.py [-h] --uuid UUID [--version VERSION] --key KEY --in INF --out OUT
> sign.py: error: argument --uuid: invalid uuid_parse value: '5b9e0e40-2636-11e1-ad9e-130285d5c51c.ta'
> 
> Error: make optee_test failed.

Not sure why the signing python script complains that it is an invalid uuid value.

So, later I generated an uuid using http://www.itu.int/ITU-T/asn1/uuid.html. But, i still get the same error.
Could i get some leads here please?

**Comment by vchong** [comment]
Try with just the numbers, i.e. without the '.ta'

**Comment by vchong** [comment]
Also, you might want to check that you're using compatible versions of optee_{os,client,test} repos. `sign.py` is now `sign_encrypt.py`.

**Comment by Hussain1811** [comment]
removing the .ta works.
But, i was confused because other files did indeed use .ta suffix in "Android.mk" and "Makefile" in the respective TA folders
