### ISSUE TITLE
Questions on ADBG framework

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_test#543]
1)What does ADBG stand for?

2)Is it a dedicated test-framework only for OPTEE?

3)I have seen that the ADBG framework doesn't support execution at sub test-case level. Can the ADBG framework be extended for this use-case?

**Comment by jenswi-linaro** [comment]
> 1)What does ADBG stand for?

I don't think anyone remembers anymore.

> 2)Is it a dedicated test-framework only for OPTEE?

I suppose you could say that.

> 3)I have seen that the ADBG framework doesn't support execution at sub test-case level. Can the ADBG framework be extended for this use-case?

I'm not sure that would make much sense. Perhaps you can divide the tests you have into smaller tests instead? Or did you have something particular in mind?

**Comment by Hussain1811** [comment]
> > 1)What does ADBG stand for?
> 
> I don't think anyone remembers anymore.
> 
> > 2)Is it a dedicated test-framework only for OPTEE?
> 
> I suppose you could say that.
> 
> > 3)I have seen that the ADBG framework doesn't support execution at sub test-case level. Can the ADBG framework be extended for this use-case?
> 
> I'm not sure that would make much sense. Perhaps you can divide the tests you have into smaller tests instead? Or did you have something particular in mind?

We have a test-execution platform which has the capability to run each sub test that are under a parent test too.

**Comment by Hussain1811** [comment]
@jenswi-linaro does this use-case seem reasonable?

**Comment by jenswi-linaro** [comment]
> @jenswi-linaro does this use-case seem reasonable?

Sure, but how will this affect the already present test code?

**Comment by Hussain1811** [comment]
@jenswi-linaro you mean the ADBG framework code? or the xtest code?

**Comment by jenswi-linaro** [comment]
The test cases in the xtest code.
