### ISSUE TITLE
Invalid module format error

### ISSUE THREAD

**Issue by roman3017** [OP-TEE/optee_test#55]
I have compiled the modules but when trying to insert them I get invalid format errors. Have you seen it before?

-bash-3.2# uname -r
3.10.88

-bash-3.2# modinfo -F vermagic optee.ko                                                   
3.10.88 preempt mod_unload modversions ARMv7 p2v8 
 
-bash-3.2# insmod optee.ko 
[12029.023267] optee: disagrees about version of symbol module_layout
insmod: error inserting 'optee.ko': -1 Invalid module format

-bash-3.2# modinfo -F vermagic optee_armtz.ko 
3.10.88 preempt mod_unload modversions ARMv7 p2v8

-bash-3.2# insmod optee_armtz.ko 
[12132.090255] optee_armtz: disagrees about version of symbol module_layout
insmod: error inserting 'optee_armtz.ko': -1 Invalid module format

**Comment by jbech-linaro** [comment]
Hi @roman3017 , what device have you been building for? The problem is most likely a mismatch between your kernel version in use and the kernel version that you have been using when building the modules. Make sure that we rebuild the kernel modules if you have been updated the kernel.

// Regards Joakim

**Comment by roman3017** [comment]
I run uname and modinfo to show I am running the same versions. I have used the same compiler for both kernel and modules. Also, modprobe would figure out module dependencies but with insmod one has to insert all dependencies manually. I am trying to get this working on a Broadcom platform. Thanks for your reply.

**Comment by roman3017** [comment]
I see, it is not enough to have the same versions of kernel and compiler. After recompiling and flashing the kernel, I recompiled the modules using the same .config file and the build environment. Afterwards I was able to insert them. Thanks for your help.
