### ISSUE TITLE
xtest pkcs11_1010 fails

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_test#551]
Test platform: QEMUv8
```
$ make -j10 CFG_PKCS11_TA=y CFG_IN_TREE_EARLY_TAS=pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee run
...
buildroot login: test
$ xtest pkcs11_1010
[...]
o pkcs11_1010.3 Generate Generic Secret Key - Try Signing
pkcs11_1000.c:2295: rv has an unexpected value: 0x68 = CKR_KEY_FUNCTION_NOT_PERMITTED, expected 0x0 = CKR_OK
  pkcs11_1010.3 FAILED
```

Bisected, the culprit seems to be da1e3aaa8e0fb3502c45903d3be30ecdd77af5e7.

Version info:
```
optee_client          3.14.0-17-g1828743
optee_os              3.14.0-110-g4137952d
```

@vchong @etienne-lms

**Comment by vchong** [comment]
@jforissier Sorry about that. I'll check and report back.

**Comment by jforissier** [comment]
@vchong no worries, the regression slipped in due to IBART being down and me not making the effort to manually test before merging :-/

**Comment by etienne-lms** [comment]
Discussed with @vchong. Fix proposal in https://github.com/OP-TEE/optee_test/pull/552.
