### ISSUE TITLE
Usage of VAL2HANDLE & HANDLE2VAL macros

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_test#564]
We can see different definitions of these macros in ta/crypt/storage.c and in ta/crypt/crypt_taf.c
ta/storage/storage.c:
`#define VAL2HANDLE(v) (void *)(uintptr_t)(v)`

ta/crypt/crypt_taf.c:
```
extern const void *ta_head;
#define VAL2HANDLE(v) (void *)(uintptr_t)(v == TEE_HANDLE_NULL ? v : v + (uintptr_t)&ta_head)
#define HANDLE2VAL(h) (uint32_t)(h == TEE_HANDLE_NULL ? (uintptr_t)h : (uintptr_t)((uintptr_t)h - (uintptr_t)&ta_head))
```
Is there any reason for this difference?

Also, at times, we do the following in ta/storage/storage.c:
```
TEE_ObjectHandle o = TEE_HANDLE_NULL;
o = (TEE_ObjectHandle)(uintptr_t)params[0].value.a;
```

And, sometimes we do `o = VAL2HANDLE(params[0].value.a)`
is there any reason for this too?

**Comment by jenswi-linaro** [comment]
All this is test code with the objective to test the TEE Internal Core API. The hacks with these handles are just that, hacks. They serve their purposes though and that's good enough here. I suppose that in the example that you bring up from the storage TA that `VAL2HANDLE()` should have been used instead.

**Comment by Hussain1811** [comment]
Alright.
Thank you.
