### ISSUE TITLE
xtest 2004 random failures with IBART

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_test#569]
https://optee.mooo.com:5000/logs/OP-TEE/optee_os/5006/789674667/9c6f3a725d69daecfea96274e9dd6b84c43f89cc (search for "socket_recv"):

```
  1362:  * regression_2004 UDP iSocket API tests
  1363:  o regression_2004.1 Start server
  1364:    regression_2004.1 OK
  1365:  o regression_2004.2 UDP Socket open
  1366:    regression_2004.2 OK
  1367:  o regression_2004.3 Normal send and receive
  1368:  o regression_2004.3.1 UDP Socket send
  1369:    regression_2004.3.1 OK
  1370:  o regression_2004.3.2 UDP Socket recv
  1371:    regression_2004.3.2 OK
  1372:    regression_2004.3 OK
  1373:  o regression_2004.4 UDP Socket truncated recv
  1374:  o regression_2004.4.1 UDP Socket send
  1375:    regression_2004.4.1 OK
  1376:  o regression_2004.4.2 UDP Socket recv
  1377:  regression_2000.c:697: socket_recv(session, sh, buf, &blen, 0xFFFFFFFF, &ret_orig) has an unexpected value: 0xf1007003 = TEE_ISOCKET_ERROR_TIMEOUT, expected 0x0 = TEEC_SUCCESS
  1378:  regression_2000.c:779: test_2004_send_recv(c, &server_iostate, &local_iostate, &session, &sh, 64, 32) has an unexpected value: 0x0 = false, expected 0x1 = true
  1379:    regression_2004.4.2 FAILED
  1380:    regression_2004.4 FAILED
  1381:    regression_2004 FAILED
```

Doesn't seem to always happen. I could not reproduce the issue with QEMUv8. I gave a quick look at the code in tee-supplicant ([tee_socket.c](https://github.com/OP-TEE/optee_client/blob/e532a51ec020fd652dc1f83b4a5a0311afeab246/tee-supplicant/src/tee_socket.c#L501)), could the `recvmsg()` call fail with `errno==EINTR` in `tee_socket_recv()`->`read_with_timeout()`->`recv_with_out_flags()`->`recvmsg()`?

Update: Issue also happened with QEMUv8 / Xen / DomU in optee_os CI ([link](https://dev.azure.com/OPTEE/optee_os/_build/results?buildId=1695&view=logs&j=705748f3-7146-5e86-79af-1c0266d20a8c&t=d3458a7d-1a81-5639-8e63-8927d807e53a&l=14778)).

**Comment by jenswi-linaro** [comment]
Hmm, let's try adding some special treatment for `EINTR` with `recv_with_out_flags()`.

**Comment by jenswi-linaro** [comment]
See PR https://github.com/OP-TEE/optee_client/pull/292

**Comment by jenswi-linaro** [comment]
And PR https://github.com/OP-TEE/optee_test/pull/571

**Comment by jforissier** [comment]
Both PR are now merged, thanks for the quick turnaround.
