### ISSUE TITLE
[Security] Workflow stale_issue.yml is using vulnerable action actions/stale

### ISSUE THREAD

**Issue by qazaqstan2025** [OP-TEE/optee_test#576]
The workflow stale_issue.yml is referencing action actions/stale using references v3.0.10. However this reference is missing the commit [af4072615903a8b031f986d25b1ae3bf45ec44d4](https://github.com/actions/stale/commits/af4072615903a8b031f986d25b1ae3bf45ec44d4) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by jenswi-linaro** [comment]
@jbech-linaro would you mind taking a look at this?

**Comment by jbech-linaro** [comment]
> @jbech-linaro would you mind taking a look at this?

Yes, I'll take care of this and in the other gits as well. I've seen identical reports elsewhere, hence I guess this is some kind of automated tool that people are running.
