### ISSUE TITLE
TA: Creating a library for common code

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_test#578]
Hello,
i have the below folder structure
```
ta
   crypto_test
   secure_storage_test
   include
   common.c
   CMakeLists.txt
   Makefile
   ta_common.mk
```
My use-case: The function definitions and their prototypes present in "common.c" & "include" need to be used by the source files present under "memory_test" and "crypto_test"

So, i tried the below structure:
```
ta
   crypto_test
   secure_storage_test
   common_lib
              include
              common.c
              Makefile
              sub.mk
   CMakeLists.txt
   Makefile
   ta_common.mk
```
So i was trying to compile common.c only once. But, i was finding it a bit difficult to link the generated common..o object file to the other folders as the build process expects me to give a "BINARY = ..." entry for the common folder. But, i don't want to make a separate TA binary for the common folder.

Could i get some help w.r.t this?

**Comment by Hussain1811** [comment]
i tried a library sort of an approach similar to what is being done for `os_test_lib` and `os_test_lib_dl` where `os_test` is linking to.
But i get a linking error as below:
```
Building /home/saddy/project/optee_qemu_3.13/out-br/build/optee_test_extensions-1.0/ta/secure_storage_test/Makefile
  CC      out/ta_sec_storage_entry.o
  CC      out/test_ta_SecStorage.o
  CPP     out/ta.lds
  CC      out/user_ta_header.o
  LD      out/cbcf9c6c-a65c-4f2e-ba23-f75970de5d30.elf
/home/saddy/project/optee_qemu_3.13/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: cannot find -lcommon
/home/saddy/project/optee_qemu_3.13/optee_os/out/arm/export-ta_arm64/mk/link.mk:116: recipe for target 'out/cbcf9c6c-a65c-4f2e-ba23-f75970de5d30.elf' failed
make[3]: *** [out/cbcf9c6c-a65c-4f2e-ba23-f75970de5d30.elf] Error 1
package/pkg-generic.mk:247: recipe for target '/home/saddy/project/optee_qemu_3.13/out-br/build/optee_test_extensions-1.0/.stamp_built' failed
make[2]: *** [/home/saddy/project/optee_qemu_3.13/out-br/build/optee_test_extensions-1.0/.stamp_built] Error 2
Makefile:23: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/saddy/project/optee_qemu_3.13/out-br'
common.mk:294: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

```
NOTE:cbcf9c6c-a65c-4f2e-ba23-f75970de5d30 is the UUID of memory_test TA

**Comment by jforissier** [comment]
Check the -L argument. It looks like it's not good. You may build with V=1 to see the full command.

**Comment by Hussain1811** [comment]
after a lot of debugging, i was able to fix the issue.
I just had to do as below in build/common.mk in the QEMU build folder structure:
OPTEE_TEST_EXT_TAS = common_lib secure_storage_test crypto_test *

**Comment by Hussain1811** [comment]
Actually, the compilation is working perfectly but the run-time fails as i don't have the `CFG_TA_DYNLINK` option set in the OPTEE that i currently use.

I was thinking if i could compile "common_lib" as a static library instead.
Any suggestions?

**Comment by jforissier** [comment]
> How can the TA use libcommon.a?

- The same command you used for a shared library (libcommon.so) should work for a static library, too (libcommon.a):
  ```
  LDADD = -L$(subst secure_storage_test,common_lib,$(abspath $(link-out-dir))) -lcommon
  ```
- A static library may also be given as a file (like an object), so this should work too:
  ```
  LDADD = $(subst secure_storage_test,common_lib,$(abspath $(link-out-dir)))/libcommon.a
  ```
- You may also use `libnames` and `libdirs` as documented in https://optee.readthedocs.io/en/latest/building/trusted_applications.html#sub-mk-directives.

**Comment by Hussain1811** [comment]
> > How can the TA use libcommon.a?
> 
> * The same command you used for a shared library (libcommon.so) should work for a static library, too (libcommon.a):
>   ```
>   LDADD = -L$(subst secure_storage_test,common_lib,$(abspath $(link-out-dir))) -lcommon
>   ```
i tried this - but error is _ld.bfd: cannot find -lcommon_

**Comment by jforissier** [comment]
Check the link line (`make V=1`), list the content of the expanded path after `-L`, it should contain `libcommon.a`.

**Comment by Hussain1811** [comment]
looks like libcommon.a isn't getting written to the required path.
i guess there is something w.r.t the way i have generated the static library

**Comment by Hussain1811** [comment]
while compiling as a dynamic library, libcommon.so is indeed written to the out/ta/... path
But, libcommon.a doesn't get written to this path surprisingly
