### ISSUE TITLE
Failure of large TA (test case 1034)

### ISSUE THREAD

**Issue by ChrisChi11** [OP-TEE/optee_test#580]
I'm pretty new to optee-os / optee-test
Regarding test case 1034: loading large TA.

This test case can pass If I run this one only. However, if I run a sequence of test case first (EX: xtest _1 or xtest -t regression)
It'll have chance (not 100%) to fail on this testcase, open session failed with TEEC_ERROR_SECURITY response.
Also once it failed, it can't become pass again unless reboot system. (even run this test case 1034 only)
Would it relate to memory not enough? Would ldelf automatically check bin size & rest of mem space to make sure it can be loaded correctly? Also I thought each TA would be freed after test case finish (close session)

**Comment by jenswi-linaro** [comment]
It sounds like a problem with fragmented memory. More likely fragmented physical TA memory than a fragmented heap though.

**Comment by ChrisChi11** [comment]
It turns out it was truly out of memory. I got a print_oom log.
May I ask how do I know OOM is happened on which region?
Not sure which one should be enlarged. TEE_RAM_RX, TEE_RAM_RW, TA_RAM

**Comment by jenswi-linaro** [comment]
It's the heap, `CFG_CORE_HEAP_SIZE`.

**Comment by ChrisChi11** [comment]
Really thanks for your reply. It works! 
I didn't come up it was  not enough core heap. I thought once TA has been loaded, it will use their own heap, which is declared by TA_DATA_SIZE. Also this test case 1034 actually did nothing but declare a lager const data, so it doesn't truly need much heap but TA image size instead. That's why I thought the issue was caused by load TA failed or some sort of that. Did I miss something? Thanks for your answer again.
