### ISSUE TITLE
PTA_INVOKE_TESTS_CMD_MEMREF_NULL error while compiling project

### ISSUE THREAD

**Issue by trriger** [OP-TEE/optee_test#583]
When I compile xtest, the error happen. It show that
`/home/rock/optee_test-3.15.0/host/xtest/regression_1000.c: In function 'xtest_te                         e_test_1025':
/home/rock/optee_test-3.15.0/host/xtest/regression_1000.c:2032:12: error: 'PTA_I                         NVOKE_TESTS_CMD_MEMREF_NULL' undeclared (first use in this function); did you me                         an 'PTA_INVOKE_TESTS_CMD_SELF_TESTS'?
 2032 |            PTA_INVOKE_TESTS_CMD_MEMREF_NULL,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
How can I fix it?

**Comment by jforissier** [comment]
Hi @trriger,

It looks like your `optee_os` is too old compared to your `optee_test`. In other words, for `optee_test` 3.15.0 you need `optee_os` 3.15.0.

**Comment by trriger** [comment]
Thank your reply. The problem was solved after changing optee_os version.
