### ISSUE TITLE
A way to list all ta applications and their status?

### ISSUE THREAD

**Issue by hariszukanovic** [OP-TEE/optee_test#588]
Using some 3rd party ta applications for DRM with optee on Android AOSP... I am having trouble and frankly no clue about what is wrong.
I was wondering how to do a basic sanity checkup and verify that their apps are signed correctly and have loaded successfully and are good to run... ?

Did not find anything in the docs about this... so it there is please point me to it. Thank you in advance

**Comment by jenswi-linaro** [comment]
Enabling debug prints in OP-TEE is a good start. Log entries for a successfully loaded TA in test case `xtest 1004` looks like:
```
D/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/LD:  ldelf:168 ELF (cb3e5ba0-adf1-11e0-998b-0002a5d5c51b) at 0x4005b000
```
The last line is printed by ldelf as a report of what has been successfully loaded.

You can play a bit with the different test cases in the 1xxx series of test in xtest to get a feeling for what's good and what's bad.

**Comment by hariszukanovic** [comment]
Thanx for the pointer. Looks like exactly what I am looking for except, I am not able to find where to enable debug prints.
Perhaps my version is too old? I have to use 2.4.0 in my case
In the attachment, the only system info I was able to dig out
![Screenshot from 2022-02-17 14-38-56](https://user-images.githubusercontent.com/1234728/154493626-ac29ea33-7db4-45ba-8d62-c3650abbf37c.png)

**Comment by jforissier** [comment]
@hariszukanovic in case you haven't figured it out yet: the debug prints that Jens mentioned are enabled at build time of OP-TEE OS (for example, by adding `CFG_TEE_CORE_LOG_LEVEL=3` to the `make` command line), and they are sent to the secure console (typically some serial port on the board). If you cannot compile OP-TEE by yourself, you should ask the people who provided the binary.
Note that OP-TEE version 2.4 is somewhat old now (latest is 3.16) so the traces will definitely look different from the above. You should still find similar information on which TA UUID the TEE is trying to load.

**Comment by hariszukanovic** [comment]
Thank you.
