### ISSUE TITLE
deprecated-declarations for openssl call

### ISSUE THREAD

**Issue by cpriouzeau** [OP-TEE/optee_test#599]
Context: 
Try to compile optee-test with Openembedded/yocto Kirkstone which have openssl-3.0.0

During the compilation of host/xtest/regression_1000.c there is some warning with deprecated opennsl usage. 
By default the compilation transform this kind of warning on error.

Optee-test are compiled with define OPENSSL_FOUND.

Trace of build: 
CC host/xtest/regression_1000.c
| host/xtest/regression_1000.c: In function 'check_signature':
| host/xtest/regression_1000.c:2736:9: error: 'SHA256_Init' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2736 |         SHA256_Init(&ctx);
|       |         ^~~~~~~~~~~
| In file included from host/xtest/regression_1000.c:14:
| recipe-sysroot/usr/include/openssl/sha.h:73:27: note: declared here
|    73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
|       |                           ^~~~~~~~~~~
| host/xtest/regression_1000.c:2737:9: error: 'SHA256_Update' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2737 |         SHA256_Update(&ctx, nonce, nonce_size);
|       |         ^~~~~~~~~~~~~
| In file included from host/xtest/regression_1000.c:14:
| recipe-sysroot/usr/include/openssl/sha.h:74:27: note: declared here
|    74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
|       |                           ^~~~~~~~~~~~~
| host/xtest/regression_1000.c:2738:9: error: 'SHA256_Update' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2738 |         SHA256_Update(&ctx, ta_hash, SHA256_DIGEST_LENGTH);
|       |         ^~~~~~~~~~~~~
| In file included from host/xtest/regression_1000.c:14:
| recipe-sysroot/usr/include/openssl/sha.h:74:27: note: declared here
|    74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
|       |                           ^~~~~~~~~~~~~
| host/xtest/regression_1000.c:2739:9: error: 'SHA256_Final' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2739 |         SHA256_Final(digest, &ctx);
|       |         ^~~~~~~~~~~~
| In file included from host/xtest/regression_1000.c:14:
| recipe-sysroot/usr/include/openssl/sha.h:76:27: note: declared here
|    76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
|       |                           ^~~~~~~~~~~~
| host/xtest/regression_1000.c:2741:9: error: 'RSA_public_decrypt' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2741 |         st = RSA_public_decrypt(att_key_size, sig, decr, att_key,
|       |         ^~
| In file included from host/xtest/regression_1000.c:13:
| recipe-sysroot/usr/include/openssl/rsa.h:288:5: note: declared here
|   288 | int RSA_public_decrypt(int flen, const unsigned char *from, unsigned char *to,
|       |     ^~~~~~~~~~~~~~~~~~
| host/xtest/regression_1000.c:2744:9: error: 'RSA_verify_PKCS1_PSS_mgf1' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2744 |         st = RSA_verify_PKCS1_PSS_mgf1(att_key, digest, EVP_sha256(),
|       |         ^~
| In file included from host/xtest/regression_1000.c:13:
| recipe-sysroot/usr/include/openssl/rsa.h:433:5: note: declared here
|   433 | int RSA_verify_PKCS1_PSS_mgf1(RSA *rsa, const unsigned char *mHash,
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~
| host/xtest/regression_1000.c: In function 'free_att_key':
| host/xtest/regression_1000.c:2751:9: error: 'RSA_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2751 |         RSA_free(att_key);
|       |         ^~~~~~~~
| In file included from host/xtest/regression_1000.c:13:
| recipe-sysroot/usr/include/openssl/rsa.h:293:28: note: declared here
|   293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
|       |                            ^~~~~~~~
| host/xtest/regression_1000.c: In function 'set_att_key':
| host/xtest/regression_1000.c:2788:9: error: 'RSA_new' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2788 |         att_key = RSA_new();
|       |         ^~~~~~~
| In file included from host/xtest/regression_1000.c:13:
| recipe-sysroot/usr/include/openssl/rsa.h:201:28: note: declared here
|   201 | OSSL_DEPRECATEDIN_3_0 RSA *RSA_new(void);
|       |                            ^~~~~~~
| host/xtest/regression_1000.c:2799:9: error: 'RSA_set0_key' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|  2799 |         st = RSA_set0_key(att_key, bn_n, bn_e, BN_new());
|       |         ^~
| In file included from host/xtest/regression_1000.c:13:
| recipe-sysroot/usr/include/openssl/rsa.h:207:27: note: declared here
|   207 | OSSL_DEPRECATEDIN_3_0 int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
|       |                           ^~~~~~~~~~~~
| cc1: all warnings being treated as errors

The issue are seen only with host/xtest/regression_1000.c

**Comment by etienne-lms** [comment]
keep alive
Could be tag as a Bug.

**Comment by jforissier** [comment]
Well, not supporting future incompatible versions of a third-party library is hardly a bug. I agree it may be an issue for some people, who are welcome to submit patches :)
