### ISSUE TITLE
bundled libcrypto.a for arm does not work with musl.

### ISSUE THREAD

**Issue by kraj** [OP-TEE/optee_test#607]
this version committed in [1] contains calls to fortified functions from libc `__sprintf_chk` which only works with glibc and not musl. So make it more compatible perhaps -fPIC is ok but maybe not use `-D_FORTIFY_SOURCE=2` while compiling libcrypto.a
Can we get a newer version of this library which can work across musl and glibc.

Current errors are like
```
arm-yoe-linux-musleabi/gcc/arm-yoe-linux-musleabi/12.1.0/ld: ../openssl/lib/arm/libcrypto.a(dso_dlfcn.o): in function `dlfcn_name_converter':
dso_dlfcn.c:(.text+0x19e): undefined reference to `__sprintf_chk'
```
[1] https://github.com/OP-TEE/optee_test/commit/83a79bd130521db1dd114adeb286b8d0fb484800

**Comment by jforissier** [comment]
Hi @kraj,

The solution you are proposing seems valid, but I am reluctant to update `libcrypto.a`. In fact I'd rather remove it altogether. Having a pre-compiled binary in the source tree is not good ; it takes significant space, does not scale as new architectures are added, may cause compatibility issues with some environments (like this Musl libc issue which can fortunately be addressed in a Glibc-compatible way it seems, but it could be different). There is a way to specify a path to the library already via `OPTEE_OPENSSL_EXPORT` so it should not be hard for people who still depend on this pre-compiled library to update their build.

FYI you can pass `-U_FORTIFY_SOURCE` to the OpenSSL `Configure` script like so:
```bash
git clone -b OpenSSL_1_0_2o https://github.com/openssl/openssl.git
cd openssl
./Configure linux-generic32 -mcpu=cortex-a9 no-shared \
             --cross-compile-prefix=arm-linux-gnueabihf- \
            -fPIC -U_FORTIFY_SOURCE
make -j$(nproc) build_libcrypto
```

**Comment by kraj** [comment]
Yes not using precompiled blobs is always better for maintainable code. I have infact suggested same solution in yocto see https://git.yoctoproject.org/meta-arm/commit/?id=31452ae4cf0be3d2d78a4019e44f9370b9e93fbb

but I suggested that for only musl since defaults are still to use captured library 

I would suggest to make that not default but a fallback
