### ISSUE TITLE
 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c on ls1046afrwy

### ISSUE THREAD

**Issue by jiang-12345678** [OP-TEE/optee_test#609]
Hi Team,
I'm struggling with running Regression 1004 on LS1046afrwy for several days.

```
root@localhost:~# xtest -t regression 1004
Test ID: 1004
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression
#
######################################################
 
* regression_1004 Test User Crypt TA


^CE/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
```

I have no clue about why ldelf_init_with_ldelf error happened.

Any comment is appreciated!
Thanks,
feng

**Comment by jforissier** [comment]
Hi @jiang-12345678,

The error shows that the user space loader (ldelf) received error `TEE_ERROR_OUT_OF_MEMORY` (0xffff000c) when it called the TEE core to open the TA binary. `sys_open_ta_bin()` failed in function `init_elf()` at line 437, see file `ldelf/ta_elf.c`. 
Please enable debug logs with `CFG_TEE_CORE_LOG_LEVEL=3` to get more messages. The issue could be in the TEE core or in the Normal World.

**Comment by jiang-12345678** [comment]
root@localhost:~# xtest -t regression 1004
Test ID: 1004
RD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
un test suite wiD/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
th level=0

TED/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
E test applicatiD/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
on started over default TEE instance
######################################################
#
# regression
#
######################################################
 
* regression_1004 Test User Crypt TA



^CD/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff000c
E/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:718 init session failed 0xffff000c

**Comment by jiang-12345678** [comment]
D/TC:? 0 tee_ta_open_session:721 init session failed 0xffff000c
struct tee_ta_session *s = calloc(1, sizeof(struct tee_ta_session));

 *  +----------------------------------+ <-- CFG_TZSRAM_START
 *  | TEE core secure RAM (TEE_RAM)    |   | CFG_TZSRAM_SIZE
 *  +----------------------------------+ --'
 *
 *  +----------------------------------+  <- CFG_TZDRAM_START
 *  | TA RAM / Pagestore (TA_RAM)      |
 *  |----------------------------------+ <---- align with CORE_MMU_PGDIR_SIZE
 *  |----------------------------------+ <--
 *  | SDP test memory (optional)       |   | CFG_TEE_SDP_MEM_SIZE
 *  +----------------------------------+ <-+ CFG_TZDRAM_START + CFG_TZDRAM_SIZE
 *
 *  +----------------------------------+ <-- CFG_SHMEM_START
 *  | Non-secure static SHM            |   |
 *  +----------------------------------+   v CFG_SHMEM_SIZE

which address is used to allocate ?

**Comment by jforissier** [comment]
The message is logged by the TEE core (`D/TC` means "Debug, TEE Core") so it is TEE_RAM.

**Comment by jiang-12345678** [comment]
Hello,
 *  +----------------------------------+ <-- 
 *  | TEE core secure RAM (TEE_RAM)    |   | CFG_TZSRAM_SIZE
 *  +----------------------------------+ --'

How to set  the address of CFG_TZSRAM_START?
I have configured several addresses and they all went wrong.

CFG_TZDRAM_START = 0xfc000000
CFG_TZDRAM_SIZE = 0x3e00000
CFG_SHMEM_START= 0xffe00000
CFG_SHMEM_SIZE = 0x20000

**Comment by jforissier** [comment]
I don't know, maybe someone familiar with `plat-ls` can help.

**Comment by jiang-12345678** [comment]
* TEE RAM layout without CFG_WITH_PAGER
 *_
 *  +----------------------------------+ <-- CFG_TZDRAM_START
 *  | TEE core secure RAM (TEE_RAM)    |
 *  +----------------------------------+
 *  | Trusted Application RAM (TA_RAM) |
 *  +----------------------------------+
 *  | SDP test memory (optional)       |
 *  +----------------------------------+ <-- CFG_TZDRAM_START + CFG_TZDRAM_SIZE
 *
 *  +----------------------------------+ <-- CFG_SHMEM_START
 *  | Non-secure static SHM            |
 *  +----------------------------------+ <-- CFG_SHMEM_START + CFG_SHMEM_SIZE

TEE_RAM  has memory, why malloc failed?

**Comment by jiang-12345678** [comment]
xtest -t regression 1004 -l 3
Run test suite wD/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
ith level=3

TD/TC:? 0 create_ta:384 create entry point for pseudo TA "invoke_tests.pta"
EE test applicatD/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
ion started overD/TC:? 0 tee_ta_close_session:512 csess 0xfc0fbd70 id 1
 default TEE insD/TC:? 0 tee_ta_close_session:531 Destroy session
tance
#########D/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
################D/TC:? 0 destroy_ta:390 destroy entry point for pseudo ta "invoke_tests.pta"
################D/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
#############
#D/TC:? 0 create_ta:384 create entry point for pseudo TA "invoke_tests.pta"

# regression
D/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
#
#############D/TC:? 0 test_entry_params:179 expect memref params: 0xf4801000/16384 - 0x0/0zu - 0x0/0zu - 0x0/0zu
################D/TC:? 0 tee_ta_close_session:512 csess 0xfc0fbd70 id 1
################D/TC:? 0 tee_ta_close_session:531 Destroy session
#########
 
* D/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
regression_1001 D/TC:? 0 destroy_ta:390 destroy entry point for pseudo ta "invoke_tests.pta"
D/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b

  regression_10D/TC:? 0 create_ta:384 create entry point for pseudo TA "invoke_tests.pta"
01 OK
 
* regrD/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
ession_1002 PTA D/TC:? 0 tee_ta_close_session:512 csess 0xfc0fbd70 id 1
parameters
  reD/TC:? 0 tee_ta_close_session:531 Destroy session
gression_1002 OKD/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"

 
* regressioD/TC:? 0 destroy_ta:390 destroy entry point for pseudo ta "invoke_tests.pta"
n_1003 Core inteD/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
*D/TC:? 2 __wq_rpc:38 sleep thread 2 0xfc0d12c8
*D/TC:? 1 __wq_rpc:38 sleep thread 1 0xfc0d12c8
*D/TC:? 3 __wq_rpc:38 sleep thread 3 0xfc0d12c8
*D/TC:? 0 __wq_rpc:38 wake  thread 1 0xfc0d12c8
rnal read/write D/TC:? 0 create_ta:384 create entry point for pseudo TA "invoke_tests.pta"
*D/TC:? 1 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
*D/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 1 __wq_rpc:38 wake  thread 2 0xfc0d12c8
*D/TC:? 0 __wq_rpc:38 wake  thread 3 0xfc0d12c8
*D/TC:? 2 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
*D/TC:? 1 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 3 __wq_rpc:38 sleep thread 3 0xfc0d12c8
*D/TC:? 0 __wq_rpc:38 sleep thread 0 0xfc0d12c8
*D/TC:? 2 __wq_rpc:38 wake  thread 3 0xfc0d12c8
*D/TC:? 1 __wq_rpc:38 wake  thread 0 0xfc0d12c8
*D/TC:? 3 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
*D/TC:? 0 __wq_rpc:38 sleep thread 0 0xfc0d12c8
*D/TC:? 2 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 1 __wq_rpc:38 sleep thread 1 0xfc0d12c8
*D/TC:? 3 __wq_rpc:38 wake  thread 0 0xfc0d12c8
*D/TC:? 2 __wq_rpc:38 wake  thread 1 0xfc0d12c8
*D/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
*D/TC:? 3 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 1 __wq_rpc:38 sleep thread 1 0xfc0d12c8
*D/TC:? 2 __wq_rpc:38 sleep thread 2 0xfc0d12c8
*D/TC:? 0 __wq_rpc:38 wake  thread 1 0xfc0d12c8
*D/TC:? 3 __wq_rpc:38 wake  thread 2 0xfc0d12c8
*D/TC:? 1 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
*D/TC:? 2 __wq_rpc:38 sleep thread 2 0xfc0d12c8
*D/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 3 __wq_rpc:38 sleep thread 3 0xfc0d12c8
*D/TC:? 1 __wq_rpc:38 wake  thread 2 0xfc0d12c8
*D/TC:? 0 __wq_rpc:38 wake  thread 3 0xfc0d12c8
*D/TC:? 1 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 2 __wq_rpc:38 wake  thread 0 0xfc0d1410
*D/TC:? 0 __wq_rpc:38 sleep thread 0 0xfc0d1410
*D/TC:? 3 __wq_rpc:38 sleep thread 3 0xfc0d1410
*D/TC:? 1 __wq_rpc:38 wake  thread 3 0xfc0d1410
*D/TC:? 2 tee_ta_close_session:512 csess 0xfc0fbc80 id 2
*D/TC:? 0 tee_ta_close_session:512 csess 0xfc0fb930 id 5
*D/TC:? 3 __wq_rpc:38 wake  thread 1 0xfc0d1410
*D/TC:? 1 __wq_rpc:38 sleep thread 1 0xfc0d1410
*D/TC:? 2 tee_ta_close_session:531 Destroy session
*D/TC:? 0 tee_ta_close_session:531 Destroy session
*D/TC:? 3 __wq_rpc:38 wake  thread 1 0xfc0d1410
*D/TC:? 1 __wq_rpc:38 sleep thread 1 0xfc0d1410
*D/TC:? 2 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 3 __wq_rpc:38 wake  thread 1 0xfc0d1410
*D/TC:? 1 __wq_rpc:38 sleep thread 1 0xfc0d1410
*D/TC:? 2 tee_ta_close_session:512 csess 0xfc0fbb90 id 3
*D/TC:? 0 __wq_rpc:38 wake  thread 3 0xfc0d1410
*D/TC:? 3 __wq_rpc:38 sleep thread 3 0xfc0d1410
*D/TC:? 1 __wq_rpc:38 wake  thread 0 0xfc0d1410
*D/TC:? 2 tee_ta_close_session:531 Destroy session
*D/TC:? 0 __wq_rpc:38 sleep thread 0 0xfc0d1410
*D/TC:? 3 tee_ta_close_session:512 csess 0xfc0fbaa0 id 4
*D/TC:? 1 tee_ta_close_session:512 csess 0xfc0fb800 id 6
*D/TC:? 2 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 0 tee_ta_close_session:512 csess 0xfc0fbd70 id 1
*D/TC:? 3 tee_ta_close_session:531 Destroy session
*D/TC:? 1 tee_ta_close_session:531 Destroy session
*D/TC:? 0 tee_ta_close_session:531 Destroy session
*D/TC:? 3 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 1 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
*D/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
mutex
D/TC:? 0 destroy_ta:390 destroy entry point for pseudo ta "invoke_tests.pta"
    Number of paD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
rallel threads: D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
6 (2 writers andD/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
 4 readers)
   D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
 Max read concurrency: 2
    Max read waiters: 3
    Mean read concurrency: 1.0625
    Mean read waiting: 1.625
  regression_1003 OK
 
* regression_1004 Test User Crypt TA


^CD/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff000c
E/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:718 init session failed 0xffff000c

**Comment by jiang-12345678** [comment]
xtest -t regression 1004
Test ID: 1004
RD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
un test suite wiD/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
th level=0
* regression_1004 Test User Crypt TA
TED/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
E test applicatiD/TC:? 0 ldelf_syscall_open_bin:145 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
on started over default TEE instance

^CD/TC:? 0 tee_tadb_open:247 res=0xffff000c
D/TC:? 0 tee_tadb_ta_open:652 res=0xffff000c
D/TC:? 0 secstor_ta_open:22 res=0xffff000c
D/TC:? 0 ldelf_syscall_open_bin:149 res=0xffff000c
E/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:721 init session failed 0xffff000c

failure:
 struct tee_tadb_dir *db = calloc(1, sizeof(*db));
if (!db)
    {           
		return TEE_ERROR_OUT_OF_MEMORY;
    }

**Comment by jforissier** [comment]
Hi @jiang-12345678,

Have you tried increasing `CFG_CORE_HEAP_SIZE`? Try `CFG_CORE_HEAP_SIZE=131072` for instance.

**Comment by jiang-12345678** [comment]
optee_os/core/arch/arm/plat-ls/conf.mk

CFG_CORE_HEAP_SIZE ?= 131072

**Comment by jforissier** [comment]
> in file optee_os/core/arch/arm/plat-ls/conf.mk CFG_CORE_HEAP_SIZE?= 131072
> 
> now CFG_CORE_HEAP_SIZE is 131072

And...? Does it make a difference?

**Comment by jiang-12345678** [comment]
root@localhost:~# xtest -t regression 1004
Test ID: 1004
RD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
un test suite wiD/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
th level=0

TED/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
E test applicatiD/TC:? 0 ldelf_syscall_open_bin:145 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
on started over default TEE instance
######################################################
#
# regression
#
######################################################
 
* regression_1004 Test User Crypt TA


^CD/TC:? 0 tee_tadb_open:247 res=0xffff000c
D/TC:? 0 tee_tadb_ta_open:652 res=0xffff000c
D/TC:? 0 secstor_ta_open:22 res=0xffff000c
D/TC:? 0 ldelf_syscall_open_bin:149 res=0xffff000c
E/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:721 init session failed 0xffff000c

the same failure

**Comment by jforissier** [comment]
Then I'm afraid you will have to further debug this by yourself.

**Comment by jiang-12345678** [comment]
static TEE_Result tadb_open(struct tee_tadb_dir **db_ret)
{
	TEE_Result res;
	struct tee_tadb_dir *db = calloc(1, sizeof(*db));
	struct tee_pobj po = {
		.obj_id = (void *)tadb_obj_id,
		.obj_id_len = sizeof(tadb_obj_id)
	};

	if (!db)
    {   
        DMSG("res=%#"PRIx32, res);
	    return TEE_ERROR_OUT_OF_MEMORY;
    }

	db->ops = tee_svc_storage_file_ops(TEE_STORAGE_PRIVATE);

	res = db->ops->open(&po, NULL, &db->fh);
	if (res == TEE_ERROR_ITEM_NOT_FOUND)
		

	if (res)
	{
	       DMSG("res=%#"PRIx32, res);
		   free(db);
	}
	else
		*db_ret = db;

	return res;
}
location failure:
res = db->ops->create(&po, false, NULL, 0, NULL, 0, NULL, 0,
				      &db->fh);
create failed!

**Comment by jiang-12345678** [comment]
root@localhost:~# xtest -t regression 1004
Test ID: 1004
RD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
un test suite wiD/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
th level=0

TED/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
E test applicatiD/TC:? 0 ldelf_syscall_open_bin:145 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
on started over D/TC:? 0 tee_svc_storage_file_ops:33 CFG_REE_FS!
default TEE instD/TC:? 0 ree_fs_open_primitive:415 create =0
ance
##########D/TC:? 0 rpc_shm_mobj_alloc:292 entry 1
################D/TC:? 0 get_rpc_arg:424 params[0].attr is 0x1!
################D/TC:? 0 get_rpc_arg:426 params[0].vlue.a is 0x0!
############
D/TC:? 0 get_rpc_arg:428 params[0]vlue.b is 0x1000!

# regression
#D/TC:? 0 get_rpc_arg:430 params[0].vlue.c  is 0x8!

##############D/TC:? 0 get_rpc_arg:469 arg->params[0].attr  is 1!
################D/TC:? 0 get_rpc_arg:471 arg->ret  is -65536!
################D/TC:? 0 thread_rpc_alloc:631 entry  thread_rpc_alloc
########
 
* regression_1004 Test User Crypt TA


^CD/TC:? 0 get_rpc_alloc_res:562 arg->num_params is 1
D/TC:? 0 get_rpc_alloc_res:563 arg->ret  is 0xffff000c
D/TC:? 0 get_rpc_alloc_res:567 arg is null
D/TC:? 0 thread_rpc_shm_cache_alloc:1682 mobj null!
D/TC:? 0 operation_open_dfh:44 TTEEEE_EERRRR_OOUUTT_MMMM
D/TC:? 0 ree_fs_open_primitive:421 res=0xffff000c
D/TC:? 0 tee_fs_dirfile_open:131 res=0xffff000c
D/TC:? 0 tee_fs_dirfile_open:168 res=0xffff000c
D/TC:? 0 get_dirh:570 res=0xffff000c
D/TC:? 0 ree_fs_open:622 res=0xffff000c
D/TC:? 0 ree_fs_open:655 res=0xffff000c
D/TC:? 0 tadb_open:234 res=0xffff000c
D/TC:? 0 tee_tadb_open:253 res=0xffff000c
D/TC:? 0 tee_tadb_ta_open:658 res=0xffff000c
D/TC:? 0 secstor_ta_open:22 res=0xffff000c
D/TC:? 0 ldelf_syscall_open_bin:149 res=0xffff000c
E/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:721 init session failed 0xffff000c
