### ISSUE TITLE
modified xtest 4003 encountered TEE_ERROR_BAD_PARAMETERS

### ISSUE THREAD

**Issue by sting47** [OP-TEE/optee_test#61]
I tried to modify cipher_init in xtest 4003 (xtest_4000.c), but I got TEE_ERROR_BAD_PARAMETERS.
I was trying to use the third param, so I wrote something like: 
  op.params[2].tmpref.buffer = (void *)tmp_iv;
in ta_crypt_cmd_cipher_init function's if (iv != NULL). And malloc space for tmp_iv and modified correspoding paramTypes like: 
  op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_INPUT,
                               TEEC_MEMREF_TEMP_INPUT,
                               TEEC_MEMREF_TEMP_INPUT, TEEC_NONE);

Then I got the TEE_ERROR_BAD_PARAMETERS returned from "tee_ta_invoke_command."
I have noticed that it comes from "optee_os/core/arch/arm/kernel/tee_ta_manager.c"'s tee_ta_invoke_command -> tee_user_ta_enter -> thread_enter_user_mode.
The return value of thread_enter_user_mode has been already the bad_para error.
But thread_enter_user_mode is assembly code, so I am wondering which function will be called by thread_enter_user_mode in this case (cipher_init)?
Or how can I fix this return error?

BTW, I have tried to add a return TEE_ERROR_BAD_FORMAT at the beginning of ta_entry_cipher_init (optee_test/ta/crypt/cryp_taf.c), but I still got bad_para error.
So I think the problem is not at the cryp_taf.c.

**Comment by jenswi-linaro** [comment]
Hi,

Without looking at your changes I can't say where the error is.

`thread_enter_user_mode` calls the user space function supplied in the `user_func` parameter.

Regards,
Jens

**Comment by sting47** [comment]
I've found that it's my error to put new .ta file in the incorrect path. So different paramTypes can't pass the examination.
Thanks for your help!

**Comment by vchong** [comment]
Thanks for sharing the problem + solution.
