### ISSUE TITLE
Question about the execution result

### ISSUE THREAD

**Issue by shumeigiku** [OP-TEE/optee_test#620]
Hi all,

I try to run xtest on my board. I test **aes-perf** with running ```xtest --aes-perf``` and some parameters.
Then I get the execution result. It has four parameters: (1)min (2) max (3)mean (4)stddev
I think the "mean" can be useful to represent the performance, but I am not sure what is the meaning of the "mean". 
For example, the printed result tells me that ```mean=5595.32us```. But actually when I finish a test, it costs many seconds, much larger than this time.

Now I have three groups of questions:

(1) Does it indicate that such AES test runs multiple times?
(2) If yes, where can I find the number of execution times? Can I configure this number?
(3) For the calculated time, what is it composed of? Only AES codes in secure world, or including the normal world and context switching?

**Comment by jforissier** [comment]
Hello @shumeigiku,

> I try to run xtest on my board. I test **aes-perf** with running `xtest --aes-perf` and some parameters. Then I get the execution result. It has four parameters: (1)min (2) max (3)mean (4)stddev I think the "mean" can be useful to represent the performance, but I am not sure what is the meaning of the "mean". For example, the printed result tells me that `mean=5595.32us`. But actually when I finish a test, it costs many seconds, much larger than this time.
> 
> Now I have three groups of questions:
> 
> (1) Does it indicate that such AES test runs multiple times?

Yes

>(2) If yes, where can I find the number of execution times? Can I configure this number? 

The encryption is run 5000 times by default. See the parameters `-l` (default: 1) and `-n` (default: 5000).

> (3) For the calculated time, what is it composed of? Only AES codes in secure world, or including the normal world and context switching?

The latter. It is the duration of the `TEEC_InvokeCommand()` call which runs 1 encryption of the buffer (this value can be changed with `-l`). The test is run 5000 times by default (the value of `-n`) in order to produce meaningful results (mean, standard deviation).

I suggest you take a look at:
- https://github.com/OP-TEE/optee_test/blob/3.18.0/host/xtest/aes_perf.c#L498-L518
- https://github.com/OP-TEE/optee_test/blob/3.18.0/ta/aes_perf/ta_aes_perf.c#L83-L168
- The help text for `--aes-perf`:

```
$ xtest --aes-perf --help
Usage: --aes-perf [-h]
Usage: --aes-perf [-d] [-i] [-k SIZE] [-l LOOP] [-m MODE] [-n LOOP] [-r|--no-inited] [-s SIZE] [-v [-v]] [-w SEC]
AES performance testing tool for OP-TEE

Options:
  -d            Test AES decryption instead of encryption
  -h|--help     Print this help and exit
  -i|--in-place Use same buffer for input and output (decrypt in place)
  -k SIZE       Key size in bits: 128, 192 or 256 [128]
  -l LOOP       Inner loop iterations [1]
  -m MODE       AES mode: ECB, CBC, CTR, XTS, GCM [ECB]
  -n LOOP       Outer test loop iterations [5000]
  --not-inited  Do not initialize input buffer content.
  -r|--random   Get input data from /dev/urandom (default: all zeros)
  -s SIZE       Test buffer size in bytes [1024]
  -u UNIT       Divide buffer in UNIT-byte increments (+ remainder)
                (0 to ignore) [0]
  -v            Be verbose (use twice for greater effect)
  -w|--warmup SEC  Warm-up time in seconds: execute a busy loop before
                   the test to mitigate the effects of cpufreq etc. [2]
```
