### ISSUE TITLE
ED25519 constants undeclared

### ISSUE THREAD

**Issue by Jonas-July** [OP-TEE/optee_test#622]
#### General context
I'm building OpTEE for the Xilinx Versal VMK180 FPGA. To that end, I followed the [guide in the docs](https://optee.readthedocs.io/en/latest/building/devices/versal.html). The issue occurs when executing `make -j8` in the build directory.

#### What is the issue?
The compilation of optee-test fails with lots of lines similar to `regression_4000.c:3590:25: error: ‘TEE_ALG_ED25519’ undeclared here (not in a function); did you mean ‘TEE_ALG_X25519’?`. See also the attached log file.

#### When did the issue occur?
I already built the image successfully in early October, and the error mentions ED25519 which was added in mid-October. So I'd guess that those commits are the cause of this.

#### How to reproduce the issue?
I linked the guide above, but here is a relevant excerpt for reproducibility and future reference:
```
mkdir optee-proj
cd optee-proj

repo init -u https://github.com/OP-TEE/manifest.git -m versal.xml
repo sync -j4 --no-clone-bundle
cd build
make -j8 toolchains
make -j8 
```
The issue occurs at the last step.

[optee-error.log](https://github.com/OP-TEE/optee_test/files/9927990/optee-error.log)

**Comment by jforissier** [comment]
Hello @Jonas-July,

Your `optee_os` is too old for your `optee_test`. The manifest is NOT tracking upstream master ([link](https://github.com/OP-TEE/manifest/blob/master/versal.xml#L20)) which is bad because we do not bother about any kind of backwards compatibility as far as `optee_test` is concerned.

For a quick fix, cd into `optee_test` and checkout an older version.

CC @ldts.

**Comment by Jonas-July** [comment]
Thanks for the quick answer, I fixed the issue according to your suggestion by running
```
  cd optee_test
  git reset --hard eb3d01f1e3c9279948895ea79320587dded5c6da
  cd ..
```
before the `cd build`.
There is probably a good reason why `optee_os` is fixed to the old version, but I hope that this workaround won't be necessary for too long.
