### ISSUE TITLE
xtest pkcs11_1027 fails when run as "test" user

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_test#649]
PKCS#11 test 1027 fails when run as the "test" user, but passes when run as "root".
```
$ repo init https://github.com/OP-TEE/manifest -m qemu_v8.xml
$ repo sync -j10
$ cd build
$ make -j2 toolchains
$ make -j$(nproc) run
```
```
Welcome to Buildroot, type root or test to login
buildroot login: test
# xtest pkcs11_1027
[...]
* pkcs11_1027 PKCS11: Login to PKCS#11 token with ACL based authentication
o pkcs11_1027.1 C_InitToken() on uninitialized token
  pkcs11_1027.1 OK
ERR [132] LT:TEEC_OpenSession:643: TEE_IOC_OPEN_SESSION failed
ERR [132] LT:ckteec_invoke_init:304: TEEC open session failed ffff0000 from 2

pkcs11_1000.c:8692: rv has an unexpected value: 0x30 = CKR_DEVICE_ERROR, expected 0x0 = CKR_OK
  pkcs11_1027 FAILED
```
```
Welcome to Buildroot, type root or test to login
buildroot login: root
# xtest pkcs11_1027
[...]
pkcs11_1027 OK
```

On a sidenote, there seems to be missing begin/end subcase statements because from the output it looks like the test is not testing anything when it fails.

**Comment by MatthewSukyoung** [comment]
Let me check this out.

I have trouble building as below. Can I get some ideas on how to make further progress? 

In file included from fiptool.h:16,                     
                 from fiptool.c:19:
fiptool_platform.h:19:11: fatal error: openssl/sha.h: No such file or directory 
   19 | # include <openssl/sha.h>

**Comment by jforissier** [comment]
Hello @MatthewSukyoung,

You may be missing the `libssl-dev` package on your build machine. See the prerequisites here: https://optee.readthedocs.io/en/latest/building/prerequisites.html.

**Comment by MatthewSukyoung** [comment]
Hello,

I'm assuming that C_Initialize is generating an error(CKR_DEVICE_ERROR) with CKTEEC_LOGIN_TYPE as group.
Of course, C_Initialize isn't generating any error with CKTEEC_LOGIN_TYPE as user.
It's very hard to get any clue about this.
Can I get some help to figure this out?

**Comment by jforissier** [comment]
@MatthewSukyoung it is very easy to reproduce if you follow the steps I mentioned above, so it shouldn't be too difficult to figure out what's wrong. If some test absolutely needs to be run by root (not sure it is the case for this test?) then it should warn when it is not the case and not result in an error.

**Comment by MatthewSukyoung** [comment]
Yes, it's very easy to reproduce. I'd say it should also run with non-root.
But, C_Initialize is generating an error(CKR_DEVICE_ERROR) with CKTEEC_LOGIN_TYPE as group.
I make the following test code, this also generates the CKR_DEVICE_ERROR.

static void xtest_pkcs11_test_1028(ADBG_Case_t *c)
{
	CK_RV rv = CKR_GENERAL_ERROR;
	char gid_str[GID_STR_LEN] = { 0 };

	setenv("CKTEEC_LOGIN_TYPE", "group", 1);
	snprintf(gid_str, sizeof(gid_str), "%x", getegid());
	setenv("CKTEEC_LOGIN_GID", gid_str, 1);

	rv = C_Initialize(NULL);
}

If I can get some ideas on what to do, it might be helpful.
Anyway, I will keep trying to figure this out though.

**Comment by MatthewSukyoung** [comment]
Hi, 

Finally, I found the root cause and fixed it. 
Do I have only to make a review with a normal code contribution way?

BR-Matthew

**Comment by etienne-lms** [comment]
Sure @MatthewSukyoung , feel free to create a pull request, it will be happily reviewed.

**Comment by matthewchae** [comment]
OK. I created a new pull request for this.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_test/pull/664
