### ISSUE TITLE
error xtest 1008.3: create session fail

### ISSUE THREAD

**Issue by MALATTAR** [OP-TEE/optee_test#65]
Hello,
I installed optee/qemu.... When I launched the xtest 1008.3, I got an error "create session fail".
Also, when I tried to launch the hello_world example, I got a similar error.
Could you suggest some solutions for this problem? 
By the way, I added the ta by modifying filelist-tee.txt and then launch make all run, is there another way to add TAs? I think the TAs are not copied to the correct place !

Thanks!

**Comment by MALATTAR** [comment]
Here is an image of the error:
![error_img](https://cloud.githubusercontent.com/assets/12657289/12455956/0ba47bee-bf9e-11e5-826a-3fd2bc274e55.png)

I want also to mention that when I laucned make all run to build the env., I got an error related to "Check ccache" in generate-cpio-rootfs.sh. To override this issue, I committed this part of the code 
echo -n "Check ccache ..."
    #which ccache > /dev/null ; if [ ! $? -eq 0 ] ; then
    #    echo "No"
   # else
    #    echo "Yes"
        # Set $CCACHE to "ccache " only if unset
        CCACHE=${CCACHE-ccache }
   # fi
But, I do not believe that this is the cause. 
Any ideas? 
Thanks !

**Comment by pascal-brand-st-dev** [comment]
xtest 1008 is expected to return errors. Final status of the test should be OK

About ccache, did you install it (cf. https://github.com/OP-TEE/optee_os/blob/master/README.md#572-use-ccache)?

**Comment by MALATTAR** [comment]
Thank you Pascal for answering me.
Yes, the final state of the tests are OK.
I downloaded the ccache .... problem is resolved. 
I still have a problem in charging the TAs !
I modified gen_rootfs/filelist.txt and recalled run make all 
The executable (hello_world) are well charged into /bin,  but the TAs are not charged into /lib/optee_armtz/ !

**Comment by MALATTAR** [comment]
Hi again, 
I succeeded in running helloWorld and comcast_cryptoapi examples; the solution was to recompiled them. The TAs that were compiled on an older version of optee are not working for some reason !!!

**Comment by jbech-optee-adm** [comment]
There has been changes made lately and what happened if you didn't recompile the TA's was that you ended up with a panic (if I recall you would see a pager abort error and then panic). Since there is no issue anymore on your side I'm closing this issue. Feel free to re-open it again if you have more questions on the same topic.

// Joakim
