### ISSUE TITLE
xtest regression 4007_ecc and 4011 leave generated keys behind

### ISSUE THREAD

**Issue by mwasilew** [OP-TEE/optee_test#652]
When running regression 4007_ecc and regression 4011 with SE050 xtest creates key pairs in the element. These are left behind after the tests complete. After running a few iterations of xtest SE050 runs out of space for creating new keys. IMHO each test should delete the temporary objects once they're no longer used.

**Comment by jforissier** [comment]
Agreed.

**Comment by mwasilew** [comment]
Is there an easy way to fix it? I'm not very familiar with xtest code but I think the missing bit is ```ta_crypt_cmd_free_transient_object```

**Comment by mwasilew** [comment]
@jforissier I tried to fix the issue, but my knowledge of op-tee is very limited. The key pairs are generated on the se050 when tests call `TEE_GenerateKey`. This is the case in both tests (4007_ecc and 4011). I think all tests that call `ta_crypt_cmd_generate_key` will suffer from this issue. I re-ran my tests with level 1. This enables RSA key pair generation in test 4007 and it left 4 more key pairs in the se050. Could you tell me if there is an op-tee method for removing the key pairs from se050 that I can use? I searched the API and nothing stands out.

**Comment by jforissier** [comment]
I don't have an answer but I believe @ldts can help.

**Comment by ldts** [comment]
yes, it is borken with the regression xtests (not with the pkcs11 ones) : see https://github.com/OP-TEE/optee_os/issues/5086

I suggest using some tool like https://github.com/foundriesio/fio-se05x-cli to clear the device nvm until we have a proposal to the issue above..
