### ISSUE TITLE
Useless code in attestation test case.

### ISSUE THREAD

**Issue by cck-wcs** [OP-TEE/optee_test#667]
The attestation test case xtest_tee_test_1037 in regression_1000.c line 3121. I don't think xtest_teec_open_session() makes sense. session is not used, and it is not closed. please confirm it, thanks.

[https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_1000.c#L3114](url)

**Comment by jforissier** [comment]
The test needs to be skipped if the PTA is not available. That is why a session is created, to check for the PTA existence. So the only thing missing is `TEEC_CloseSession(&session);` at line 3126. Thanks.

**Comment by cck-wcs** [comment]
OK, thanks.

**Comment by etienne-lms** [comment]
@cck-wcs, do you plan to propose a fix for the issue you reported?

**Comment by cck-wcs** [comment]
> @cck-wcs, do you plan to propose a fix for the issue you reported?

Hi @etienne-lms ,I will submit a patch.

**Comment by etienne-lms** [comment]
ok, thanks.
For info, we usually close an Issue once the fix relarted to it (if applicable) is merged. That's why I was wondering if you would propose a patch or not.
