### ISSUE TITLE
TA remote attestation

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_test#681]
Hi，Does xtest have TA remote attestation test cases?

**Comment by LeiSen62** [comment]
When I run xtest 1037, the following error message is displayed:
D/TC:??? 000 ldelf_syscall_open_bin:142 Lookup user TA ELF 39800861-182a-4720-9b67-2bcd622bc0b5 (REE)                               
F/TC:??? 000 plat_prng_add_jitter_entropy:72 0xBE                                                                                   
ERR [1210] TEES:load_ta:305:   TA not found 
How can I generate this TA?

**Comment by jforissier** [comment]
Hi @LeiSen62, attestation is implemented in a PTA (pseudo TA, running in kernel mode), not in a TA. To enable it you need to build OP-TEE OS with `CFG_ATTESTATION_PTA=y`. Then `xtest 1037` should work as expected. You may want to set `CFG_ATTESTATION_PTA_KEY_SIZE=1024` too, it makes key generation faster which is good when testing in QEMU.

**Comment by LeiSen62** [comment]
Thanks!
