### ISSUE TITLE
Need to fix host/xtest/Makefile?

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_test#692]
https://github.com/OP-TEE/optee_test/blob/1013c491940a8af27fbf5dcecf1d53275bc99c60/host/xtest/Makefile#L81
https://github.com/OP-TEE/optee_test/blob/1013c491940a8af27fbf5dcecf1d53275bc99c60/host/xtest/xtest_main.c#L172

Even if I run make CFG_SECSTOR_TA_MGMT_PTA=y, CFG_SECSTOR_TA_MGMT_PTA is not  defined.

I think we need to add the following sentences to host/xtest/Makefile  (near line 95):
ifeq ($(CFG_SECSTOR_TA_MGMT_PTA),y)
CFLAGS += -DCFG_SECSTOR_TA_MGMT_PTA
endif

ifeq ($(CFG_SECURE_DATA_PATH),y)
CFLAGS += -DCFG_SECURE_DATA_PATH
endif

**Comment by jforissier** [comment]
Hi @coach-bin,

These flags are related to the OPTEE-OS configuration. You need to set them when building `optee_os`. Then then will be defined automatically by `include $(TA_DEV_KIT_DIR)/host_include/conf.mk`.

**Comment by coach-bin** [comment]
Ah! thanks for feedback!
