### ISSUE TITLE
Xtest 1039 failed!

### ISSUE THREAD

**Issue by hearyouagain** [OP-TEE/optee_test#695]
when i change the default_ta.pem with a 4096bits-RSA PEM in optee_os, the execution of xtest 1039 occur failed. i try to change the identity_subkey2.pem, top_level_subkey.pem, mid_level_subkey.pem to 4096bits, but it dont works.
Why this happend? And how to fix it?
There are the result of xtest runing:
* regression_1039 Test subkey verification
o regression_1039.1 Load TA with two levels of subkeys
/home/optee/xtest/host/xtest/regression_1000.c:3206: xtest_teec_open_session(&session, &subkey1_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff000f = TEEC_ERROR_SECURITY, expected 0x0 = TEEC_SUCCESS
  regression_1039.1 FAILED
o regression_1039.2 Load TA with identity subkey
/home/optee/xtest/host/xtest/regression_1000.c:3213: xtest_teec_open_session(&session, &subkey2_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff000f = TEEC_ERROR_SECURITY, expected 0x0 = TEEC_SUCCESS
  regression_1039.2 FAILED
  regression_1039 FAILED
+-----------------------------------------------------
Result of testsuite regression filtered by "1039":
regression_1039.1 FAILED first error at /home/optee/xtest/host/xtest/regression_1000.c:3206
regression_1039.2 FAILED first error at /home/optee/xtest/host/xtest/regression_1000.c:3213
regression_1039 FAILED

**Comment by jenswi-linaro** [comment]
Did you follow the steps in https://github.com/OP-TEE/optee_test/blob/master/ta/subkey_notes.txt?

**Comment by hearyouagain** [comment]
oh thank you！i know where the problem is, and i hadnt run the step after the genrsa key.And now it works
