### ISSUE TITLE
xtest 1027 & 1028 failed

### ISSUE THREAD

**Issue by kyoWNC** [OP-TEE/optee_test#712]
linux kernel 5.4
optee 4.0.0

I ran xtest for 1027 and 1028, but encountered failures.

xtest 1027:
/optee/4.0.0/optee_test/host/xtest/regression_1000.c:2216: memcmp(&expected_client_uuid, &client_uuid, sizeof(TEEC_UUID)) has an unexpected value: 0x1, expected 0x0
  regression_1027 FAILED

expected_client_uuid: ef0180a3,13f3,5d1c,b7f5,888c0e21059a
client_uuid: 5b9e0e40,2636,11e1,ad9e,0002a5d5c51b

xtest 1028:
/optee/4.0.0/optee_test/host/xtest/regression_1000.c:2287: memcmp(&expected_client_uuid, &client_uuid, sizeof(TEEC_UUID)) has an unexpected value: 0x1, expected 0x0
  regression_1028 FAILED

expected_client_uuid: d93bc168,f863,58d3,a1fe,bb2039421b99
client_uuid: 5b9e0e40,2636,11e1,ad9e,0002a5d5c51b

Do you know how to resolve these issues?

**Comment by etienne-lms** [comment]
You would need to backport a series of kernel commits merged after v5.8.
The list, maybe not exhaustive:
e33bcbab16d1c0dd85d72bec275308369ad901f5 "tee: add support for session's client UUID generation"
c5b4312bea5d5e5e3d4f0af640e2ef8a1c1bb167 "tee: optee: Add support for session login client UUID generation"
722939528a37aa0cb22d441e2045c0cf53e78fb0 "tee: client UUID: Skip REE kernel login method as well"
673c7aa2436bfc857b92417f3e590a297c586dde "optee: use export_uuid() to copy client UUID"

**Comment by kyoWNC** [comment]
It's working
thank you so much
