### ISSUE TITLE
Fail to build xtest with enabing SDP test cases. 

### ISSUE THREAD

**Issue by sichunqin** [OP-TEE/optee_test#716]
Fail to build xtest with SDP test due to the following error: 
optee/out-br/build/optee_test_ext-1.0/host/xtest/./sdp_basic.h:12:10: fatal error: linux/dma-heap.h: No such file or directory
   12 | #include <linux/dma-heap.h>

Configure CFG_SECURE_DATA_PATH=y to enable SDP test cases.

**Comment by jbech-linaro** [comment]
@sichunqin , this was disabled some time ago and as you've seen not working with upstream code any longer. I've created a setup that pull's NXP's dma-buf heap based patches from the mailinglist and I've re-enabled SDP code in OP-TEE. However, this should just be use as is. I.e., don't expect that this particular setup will land in official tree.
``` bash
mkdir optee-sdp && cd optee-sdp
repo init -u https://github.com/jbech-linaro/manifest.git -m qemu_v8.xml -b nxp-sdp
repo sync -j12
cd build
make toolchains
make -j24 CFG_SECURE_DATA_PATH=y CFG_CORE_ASLR=n CFG_TA_ASLR=n run
# After the boot and when reaching the shell, type: xtest --sdp-basic
```

**Comment by qazsdcx** [comment]
> @jbech-linaro Thanks a lot! I follow your above steps, and try to build the branch, but get the following error: optee-sdp/out-br/build/optee_test_ext-1.0/host/xtest/stats.c:11:10: fatal error: pta_stats.h: No such file or directory 11 | #include <pta_stats.h> | ^~~~~~~~~~~~~ compilation terminated.

I encountered the same problem, how did you solve it?

**Comment by qazsdcx** [comment]
I follow your above steps, and try to build the branch, but get the following error: optee-sdp/out-br/build/optee_test_ext-1.0/host/xtest/stats.c:11:10: fatal error: pta_stats.h: No such file or directory 11 | #include <pta_stats.h> | ^~~~~~~~~~~~~ compilation terminated.

 @sichunqin  I encountered the same problem, how did you solve it?
