### ISSUE TITLE
aes-perf: sdp test: why secure input buffer is being fed with zero/random data?

### ISSUE THREAD

**Issue by abhisk612** [OP-TEE/optee_test#725]
File: `host/xtest/aes_perf.c`

In `aes_perf_run_test`, `run_feed_input` is being called to feed zeros/random data to input secure buffer by mmap'ing it.
Why non-secure application is mmap'ing and writing to secure input buffer? Can you please clarify?

```
static void run_feed_input(void *in, size_t size, int random)
...
...
#if defined(CFG_SECURE_DATA_PATH)
        if (input_buffer == BUFFER_SHM_ALLOCATED) {
                feed_input(in, size, random);
        } else {
                char *data = mmap(NULL, size, PROT_WRITE, MAP_SHARED,
                                                input_sdp_fd, 0);

                if (data == MAP_FAILED) {
                        perror("failed to map input buffer");
                        exit(-1);
                }
                feed_input(data, size, random);
                munmap(data, size);
        }
#endif
```

**Comment by etienne-lms** [comment]
Buffers that are under the secure data path are referenced by a file descriptor (`input_sdp_fd` here) instead of a (pre-mapped) buffer virtual address (`in` here). To be able to read or write to the buffer, one must map it hence the instructions you refer to.

**Comment by abhisk612** [comment]
I understand that buffer under secure data path (i.e. secure buffer) are referenced by a fd and to access them, they must be mapped with mmap.

But, it is not clear, why secure buffer is being accessed (read/write) by non-secure aes-perf application? 

I see, it is accessed by the application just to fill zero/random data in the secure buffer; it is unmapped immediately after that. What is purpose of accessing (writing in this case) secure buffer here?

**Comment by etienne-lms** [comment]
> But,I expect secure buffer to be inaccessible to the non-secure application.

That is true but for test purpose maybe (likely in the current case) there is no effective memory firewall preventing non-secure from reading and/or writing to an SDP buffer. The xtest application here simulates an AES processing performed on a SDP buffer hence possibly feeding the SDP buffer from non-secure side before measuring how long it takes to invoke an AES processing on a SDP buffer by a TA.

**Comment by abhisk612** [comment]
Thanks for clarification. We, in fact, have a situation, where we have restricted the secure buffer access non-secure application. Based on clarification, it does not seem to be hard requirement to fill the input buffer for the speed test - hence we shall proceed by removing it.

**Comment by etienne-lms** [comment]
As AES processing (encryption or decryption) does not depend on buffer content (AFAIK) i think this perf test would still be valid even if the input buffer is never initialized. This would prevent xtest from feeding a secure buffer :)
