### ISSUE TITLE
xtest_tee_test_1014 fail (CFG_SECURE_DATA_PATH)

### ISSUE THREAD

**Issue by 408419237** [OP-TEE/optee_test#735]
Hi, excuse me.
I failed to run tee_xtest 1014.
I look at tee_register_buffer->TEEC_RegisterSharedMemoryFileDescriptor->ioctl(ctx->fd, TEE_IOC_SHM_REGISTER_FD, &data) but optee_linuxdriver does not have a TEE_IOC_SHM_REGISTER_FD definition.
I want to ask whether tee_xtest 1014 can be successfully executed?
Is the CFG_SECURE_DATA_PATH function supported?
thanks!

**Comment by 408419237** [comment]
Can you help me answer that? Thank you very much. @etienne-lms

**Comment by etienne-lms** [comment]
Hi @408419237, 
Could you tell us what do you refer to when mentioning _optee_linuxdriver_?
`CFG_SECURE_DATA_PATH` is supported in OP-TEE OS but the Linux optee driver does not especially since ION staging drive rhas been removed from the kernel source tree in v5.10. See https://github.com/linaro-swg/linux/issues/91 and https://github.com/linaro-swg/linux/pull/101.

**Comment by jenswi-linaro** [comment]
optee_linuxdriver hasn't been used in a long time. It was deprecated in 2016 and replaced by the OP-TEE driver in the mainline kernel.

**Comment by 408419237** [comment]
> Hi @408419237, Could you tell us what do you refer to when mentioning _optee_linuxdriver_? `CFG_SECURE_DATA_PATH` is supported in OP-TEE OS but the Linux optee driver does not especially since ION staging drive rhas been removed from the kernel source tree in v5.10. See [linaro-swg/linux#91](https://github.com/linaro-swg/linux/issues/91) and [linaro-swg/linux#101](https://github.com/linaro-swg/linux/pull/101).

I see TEE_IOC_SHM_REGISTER_FD in optee_client，But I didn't see it in the optee driver.only TEE_IOC_SHM_REGISTER. 
thanks.

![image](https://github.com/OP-TEE/optee_test/assets/50823725/e31e1def-77d0-4849-a0f9-b68118a99b30)
https://github.com/linaro-swg/linux/blob/optee/drivers/tee/tee_core.c

![image](https://github.com/OP-TEE/optee_test/assets/50823725/10358735-1c7d-447f-ad05-87a90bb42b3d)
https://github.com/OP-TEE/optee_client/blob/master/libteec/src/tee_client_api.c

**Comment by 408419237** [comment]
> optee_linuxdriver hasn't been used in a long time. It was deprecated in 2016 and replaced by the OP-TEE driver in the mainline kernel.

This version I'm looking at, I think it's new.Thanks.

![image](https://github.com/OP-TEE/optee_test/assets/50823725/f7b00b59-a62c-4e93-b947-bbf8b6f726f9)
https://github.com/linaro-swg/linux/blob/optee/drivers/tee/tee_core.c

**Comment by 408419237** [comment]
test ok closed.

**Comment by 408419237** [comment]
test ok closed.
