### ISSUE TITLE
Missing return value check when use fs_unlink func.

### ISSUE THREAD

**Issue by XMPengYinjie** [OP-TEE/optee_test#742]
Hi supporter:

As title, in host/xtest/regression_6000.c should  check `fs_unlink` 's return value ：
![image](https://github.com/OP-TEE/optee_test/assets/49423251/0f61d07a-edd8-4458-8755-0ed4bffc4f8a)

Also in ta/storage/storage.c  `ta_storage_cmd_unlink` should't alway rerurn `TEE_SUCCESS`. 
![image](https://github.com/OP-TEE/optee_test/assets/49423251/967ded1f-06c8-4a1f-91e3-086b011afd70)

I have tried as follow patch, could you please help to double check ?
![image](https://github.com/OP-TEE/optee_test/assets/49423251/fb6fb9c2-cc30-4478-a391-df463a63edaf)
![image](https://github.com/OP-TEE/optee_test/assets/49423251/9a22ccb2-ea4f-4017-aac8-ad6add921458)

**Comment by XMPengYinjie** [comment]
Now `check_storage_available`  will return `TEE_SUCCESS` even though ` fs_unlink--->ta_storage_cmd_unlink ` failed early in TEE.

**Comment by jenswi-linaro** [comment]
Please propose the patch in a pull request for easier reviewing.

**Comment by XMPengYinjie** [comment]
> Please propose the patch in a pull request for easier reviewing.

Hi  jenswi-linaro：
As your comment,  pelease help to review the pull reques：

https://github.com/OP-TEE/optee_test/pull/743

Thanks.
