### ISSUE TITLE
License text (BSD/GPL) is not incorporated within this repository

### ISSUE THREAD

**Issue by jamesr** [OP-TEE/optee_test#748]
The top-level LICENSE.md file for this repository states that portions are released under a BSD 2-clause license and portions are released under a GPL-2.0 license. It does so by linking to canonical copies of these licenses elsewhere on the internet:

https://github.com/OP-TEE/optee_test/blob/5bf536242b29bf5f1b578d79da076db96c46d0b7/LICENSE.md

Would it be possible to directly incorporate the applicable license text in the repository directly rather than linking to external source? A possible reading of these licenses is that the license text itself must be conveyed along with any distributions of the source and so the lack of license text is causing issues for working with this repository. Thanks!

**Comment by jenswi-linaro** [comment]
Sure, would you mind creating a pull request for it?
