### ISSUE TITLE
Cryptography tests

### ISSUE THREAD

**Issue by flowher** [OP-TEE/optee_test#76]
Hi,

It's more a  question than an issue. I'm planning to add some cryptography tests and I'm wondering if should do it in optee sources or libtomcrypt. What would you suggest?

Kris

**Comment by pascal-brand-st-dev** [comment]
In case the tests are using the Global Platform API, OP-TEE is the right place.

**Comment by jbech-linaro** [comment]
Also, if you're adding the tests to OP-TEE, you will implicitly test LibTomCrypt in the end.

**Comment by flowher** [comment]
Great, OP-TEE then, because I can use GP API. 

Thanks !
