### ISSUE TITLE
Does the TA_CONCURRENT_CMD_BUSY_LOOP test in optee-test 1013 require sca？

### ISSUE THREAD

**Issue by xtaens** [OP-TEE/optee_test#760]
I would like to ask: When testing TA_CONCURRENT_CMD_BUSY_LOOP in optee-test 1013, I did not see any encryption and decryption operations in ta, but there were sca operations in opte-os. Why is this? What is sca doing?

Thank you

**Comment by jenswi-linaro** [comment]
The function `ta_entry_busy_loop()` which is entered for `TA_CONCURRENT_CMD_BUSY_LOOP` doesn't do any encryption or decryption in the TA, it only spins a bit and then returns. I'm not sure what you mean with "sca".

**Comment by xtaens** [comment]
> The function `ta_entry_busy_loop()` which is entered for `TA_CONCURRENT_CMD_BUSY_LOOP` doesn't do any encryption or decryption in the TA, it only spins a bit and then returns. I'm not sure what you mean with "sca".

Thank you, the problem has been solved. There is sca (AES encryption and decryption) operation in the tee_fs_fek_crypt function of optee-os; even if there is no encryption and decryption call in ta, the tee fs operation will still call the encryption and decryption function. Because I am debugging AES encryption and decryption, but there is no AES call in ta, but there is actually an AES operation, so I raised this question

Thanks again

**Comment by xtaens** [comment]
The problem has been solved, the reason is as above
