### ISSUE TITLE
1004 and 1005 fail on first run

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_test#84]
Submitting for tracking. Have only seen this on HiKey so far. 1004 and 1005 will (almost) always fail on first run, but pass on 2nd and subsequent runs.

```
* XTEST_TEE_1004 Test User Crypt TA
DBG [0x0] TEE-CORE:tee_ta_init_static_ta_session:159:    Lookup for
Static TA cb3e5ba0-adf1-11e0-998b0002a5d5c51b
DBG [0x0] TEE-CORE:tee_ta_open_session:510: init session failed
0xffff0008
DBG [0x0] TEE-CORE:tee_dispatch_open_session:127:   => Error: ffff0008
of 3
/home/victor.chong/work/swg/repo20/optee_test/host/xtest/xtest_1000.c:392:
xtest_teec_open_session( &session, &crypt_usS
  XTEST_TEE_1004 FAILED

* XTEST_TEE_1005 Many sessions
DBG [0x0] TEE-CORE:tee_ta_init_static_ta_session:159:    Lookup for
Static TA 5b9e0e40-2636-11e1-ad9e0002a5d5c51b
DBG [0x0] TEE-CORE:init_session_with_signed_ta:560:    Load dynamic TA
DBG [0x0] TEE-CORE:tee_ta_open_session:510: init session failed
0xffff000f
ERR [885] TEES:write_response:447: TEE_IOC_SUPPL_SEND: Invalid
argument
DBG [0x0] TEE-CORE:tee_dispatch_open_session:127:   => Error: ffff000f
of 3
/home/victor.chong/work/swg/repo20/optee_test/host/xtest/xtest_1000.c:445:
xtest_teec_open_session(&sessions[i], &os_teS
  XTEST_TEE_1005 FAILED
```

**Comment by vchong** [comment]
Seems like if I just re-flash the images a 2nd time, the errors wouldn't happen again. Not sure how to explain this.

**Comment by vchong** [comment]
Sorry for the noise. I'm going to close this now as stupid user error.
The hikey initramfs build automatically loads the supplicant, so if I load the supplicant again before running xtest, 1004 and 1005 would fail. Now this I really can't explain, but somehow the fail would stop one of the supplicant process, leaving only one running, so all subsequent tests would pass.

**Comment by jforissier** [comment]
You are kind enough to call this a user error, I would say it is a real bug in tee-supplicant ;) It should complain and exit when started a second time and everything should work normally.

**Comment by vchong** [comment]
@jforissier Thanks for the kind comment! :)

Looking at the supplicant code, a major failure on read would end the process, so the fail must have generated it for one of the processes.

Anyway, I've submitted https://github.com/OP-TEE/optee_client/pull/49 to prevent this from happening again. Please review if available.
